 
 ############################## 
 # Country definition for CHC # 
 ############################## 
  

  
 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = CHC 
   intrinsic_gov_type     = leninist 
   extra_tc               = 7 
   capital                = 1337 # Nanjing
   # Resource Reserves 
energy                 = 240
metal                  = 120
rare_materials         = 60
   oil                    = 100 
   supplies               = 800 
   money                  = 50 
   manpower               = 220 #120 added to reinforce units 
   dissent                = 0 
   diplomacy = 
   {  relation = {  tag = JAP value = -200  } 
     relation = {  tag = MAN value = -100  } 
     relation = {  tag = CHI value = 200  } 
     relation = {  tag = CGX value = -200  } 
     relation = {  tag = CYN value = -200  } 
     # CHC protected by Shaanxi provincial governor who was secret communist
     relation = {  tag = CSX value = 200  } 
     relation = {  tag = CXB value = -100  } 
     relation = {  tag = SOV value = 100  } 
     relation = {  tag = MON value = 25  }
     relation = {  tag = U67 value = 50  } 
     relation = {  tag = SIK value = 40  }
    } 
   SpyInfo                = {  country = "CHC" NumberOfSpies = 3  } 
    ownedprovinces =      {
1335 1334 1338 1337 1343 1342 1345 1348 1346 1347 1350 1351 1358 1359 1352 1357
 	}
    controlledprovinces = {

1335 1334 1338 1337 1343 1342 1345 1348 1346 1347 1350 1351 1358 1359 1352 1357
	  }

claimedprovinces = {
#Japan
	1563
#USSR
	1119 #Tuva
	1104 #Khorugh
#India        
	1278 #Sumdo 
	1455 #Itanagar
	1458 #Mipi
	1414 #Putao

#Korea-Manchuria
 	1212 #Yanji->Jilin/Liaoyuan
 	1211 #Hunjiang->Adong/Liaoyuan
#Outer Mongolia 
	1124 #Ulaabaatar
	1123 #Olgii=>Khobdo
	1125 #Muren
	1121 #Bayankhongor
	1122 #Arvaikheer
	1120 #Choibalsan
#Inner Mongolia
	1272 #Linhe=>Bayan Nur(split)
	1270 #Bayan Hot=>Bayan Nur
	1269 #Uqai=>Yuling
	1238 #Huhehaote=>Hohot
	1239 #Jining 
 	1240 #Sili-yin Qota->Xilinhot/Erenhot
 	1237 #Ulayanqada->Xililnhot/Erenhot
 	1209 #Wulanhaote->Ulan Hot/Xilinhot
 	1206 #Haila'er
 	1198 #Butehaqi->Qiqihar
 	1200 #Human->Mohe
 	1210 #Tongliyao Hot->Chifeng
#Outer Tibet      
	1286 #Senge Khabab=>Gar
	1287 #Sger Rtse=>Nagqu
 	1288 #Rgyal Rtse=>Kagar/Xigaze
 	1289 #Lhasa
 	1290 #Ri Bo Che=>Quamdo
	1295 #Nying Khri=>Quamdo
	1294 #Chab Mdo=>Quamdo 
#Inner Tibet
	1285 #Yushu
	1384 #Luxi=>Baoshan(split)
	1389 #Baoshan
	1385 #Dali
	1292 #Ya'an
	1293 #Panzhihua=>Kangding
	1291 #Xichang=>Ya'an(split)
	1262 #Linxia=>Xining(split)
	1284 #Xining
	1283 #Ge'ermu=>Golmud
#Sinkiang        
	1279 #Kaxgar=>Kashgar
 	1274 #Qarqan=>Hotan
 	1275 #Aqsu=>Aksu
 	1280 #Ghulja
 	1273 #Aletai=>Altay
 	1276 #Karamay
#Guangxi
	1306 #Kaili
 	1381 #Bose
 	1376 #Debao->Bose
 	1382 #Hechi->Lizhou
 	1379 #Nanning
 	1374 #Pingxiang->Quinzhou
}

   nationalprovinces      = 
{
	1331 #Yantai
	1328 #Quingdao
	1329 #Weifang
	1333 #Huaiyin
	1332 #Zaozhuang
	1261 #Longnan
	1303 #Anshun
	1339 #Suzhou
	1323 #Anyang
	1321 #Xinxiang=>Anyang
	1334 #Nantong
	1336 #Xuzhou
	1340 #Hefei
	1341 #Fuyang
	1319 #Kaifeng
	1322 #Luoyang
	1324 #Zhengzhou
	1325 #Nanyang
	1326 #Xinyang
	1316 #Suizhou=>Xiangfan
	1317 #Wuhan=>Hankou
	1344 #Anqing
	1342 #Xuanzhou=>Wuhu
	1337 #Nanjing
	1338 #Shanghai
	1345 #Hangzhou
	1346 #Ningbo
	1347 #Wenzhou
	1348 #Jinhua=>Ningbo(split)
	1357 #Nanping
	1358 #Fuzhou
	1359 #Sanming
	1360 #Xiamen
	1354 #Ganzhou
	1353 #Jiujiang
	1318 #Huangshi
	1355 #Ji'an=>Zhuzhou
	1309 #Xiangtan=>Shaoyang(split)
	1311 #Chenzhou
	1312 #Hengyang
	1310 #Changde
	1304 #Zunyi
	1302 #Wanxian
	1258 #Xi'an
	1257 #Tongguan=>Xi'an(split)
	1296 #Guanxiang=>Ya'an(split)
	1297 #Chengdu
	1298 #Luzhou=>Zigong
	1305 #Guiyang
	1313 #Shashi
	1307 #Huaihua
	1308 #Changsha
	1356 #Zhangzhou=>Longyang
	1349 #Xingan=>Pingxiang
	1335 #Yancheng=>Nantong(split)
	1314 #Shiyan=>Enshi
	1315 #Yichang
	1267 #Ankang/Nancheng
	1320 #Xuchang
	1299 #Chongqing
	1343 #Huainan=>Yangzhou
	1301 #Fuling
	1350 #Jindezhen=>Quzhou
	1351 #Shangrao
	1352 #Nanchang
	1264 #Lanzhou
	1263 #Tianshui
	1256 #Baoji
#Yunnan          
	1390 #Kunming
	1386 #Pu'er=>Jinghong(split)
	1387 #Jinghong
	1388 #Gejiung
	1300 #Yibin
#Guangxi-Clique
 	1378 #Guilin
 	1380 #Liuzhou
	1383 #Wuzhou
 	1368 #Shaoguan
 	1369 #Guangzhou
 	1375 #Shantou->Chao´an
 	1370 #Lufeng->Bao´an
 	1373 #Jiangmen
 	1377 #Yulin->Maoming
 	1367 #Naoming->Zhanjiang, Maoming
 	1365 #Haikou->Hainan
#Shanxi       
	1241 #Tianjin
	1247 #Beiping
	1246 #Zhangyan=>Kalgan
	1251 #Datong
	1242 #Shijiazhuang
	1254 #Hequ=>Taiyuan
	1252 #Taiyuan
	1253 #Linfen=>Changzhi(split)
	1248 #Changzhi
	1249 #Yangquan=>Handan
	1250 #Lingqui
	1327 #Heze
	1243 #Baoding
	1244 #Changzhou=>Yucheng
	1245 #Tangshan
	1330 #Jinan 
#Manchuria
	1214 #Shenyang->Mukden
	1207 #Jilin->Xinjing
 	1202 #Jiamusi->Jixi/Jiamusi
 	1204 #Jixi
 	1205 #Mudanjiang->Jilin/Mudanjiang
 	1199 #Harbin
 	1203 #Qiqihaer
 	1213 #Baicheng->Ulan Hot
 	1220 #Dandong->Dalian
 	1218 #Panjin->Jinxi
 	1201 #Heihe
 	1208 #Changchun->Mukden
 	1215 #Fushun->Adong
 	1217 #Anshan->Dalian
 	1197 #Hegang->Heihe
 	1245 #Tangshan
 	1236 #Chengde->Changde
 	1235 #Fuxin->Changde
 	1216 #Jinzhou->Jinxi 
#Xibei san ma            
	1268 #Yinchuan
	1271 #Wuzhong=>Guyuan
	1265 #Zhangye=>Jinchang
	1266 #Yumen=>Dunhuang
	1262 #Linxia=>Xining(split)
#Sinkiang
 	1277 #Qumul=>Altay
	1281 #Urumqi
 	1282 #Xoten=>Taklimakan Desert
#Communist China      
	1259 #Yan'an
	1260 #Yulin
	1255 #Pingliang
#Japan In China     
	1219 #Port Arthur
#European Possessions     
	1371 #Hongkong
	1372 #Macao
#Taiwan     
	1361 #Gaoxiong
	1362 #Taipei
	1363 #Taizhong
	1364 #Hualian
	}
	
wartime_ic_mod       = 1.2

						# Group E 1936 techs 
   # ###################### 
   # GW fighter 
   techapps = {
		#Static Defense
		6680
  
#Interwar Fighter  
4500 4510 4520 4530 4540 4550 4010  
#Basic Armoured Car  
2860 2870 2880 2020   
#Great War Light Field Artillery  
2290  
#SW Tank 
7600 7610
#Great War Infantry Division  
1010 1020 1030 1040 1050 1060 1070 1080
#Interbellum Supply 
1910 1920 1930 1940 1950 1960
#Early Mountain Division
1160 1170 1180 1190 1200 1210 1220 1230 1240
#Great War Cavalry Division  
13060 13070 13080 1310 1320 1330 1340 
#Basic Construction Engineering 
5800 5080
#Engineers
1830 

# Great War Land Doctrines (entente)
6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6540 6910
#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010   


} 
inventions = { 3000027 }
   blueprints             = {  } 
   ai_settings = { flags = {   legitIndie = 1 } }   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 3 
     political_left    = 10 
     free_market       = 3 
     freedom           = 2 
     professional_army = 2 
     defense_lobby     = 10 
     interventionism   = 5 
    } 
   headofstate            = {  type = 9 id = 260836  } #Xiang Zhongfa
   headofgovernment       = {  type = 9 id = 260853  } #Li Lisan
   foreignminister        = {  type = 9 id = 260837  } #Xiang Zhongfa
   armamentminister       = {  type = 9 id = 260004  } 
   ministerofsecurity     = {  type = 9 id = 260005  } 
   ministerofintelligence = {  type = 9 id = 260006  } 
   chiefofstaff           = {  type = 9 id = 260007  } 
   chiefofarmy            = {  type = 9 id = 260008  } 
   chiefofnavy            = {  type = 9 id = 260009  } 
   chiefofair             = {  type = 9 id = 260010  } 
   # ###### 
   # COMMUNSIT CHINA OOB
   # 7000 from First Red Army arrived Oct 35 (15 divisions at 5% strength up to 20% by Jan 36)
   # 2 other units did not arrive until 1 year later
   # ###### 
   landunit = 
   {  location = 1343 # Yan'an 
     name     = "1. Fangmianjun" 
     id       = {  type = 24000 id = 1  } 
     Division = 
     {  experience = 60 
       id         = {  type = 24000 id = 2  } 
       name       = "1. Juntuan" 
       type       = bergsjaeger 
       strength  = 20 
       model      = 6 
      } 
     Division = 
     {  experience = 60 
       id         = {  type = 24000 id = 3  } 
       name       = "3. Juntuan" 
       type       = bergsjaeger 
       strength  = 20 
       model      = 6 
      } 
     Division = 
     {  experience = 60 
       id         = {  type = 24000 id = 4  } 
       name       = "5. Juntuan" 
       type       = bergsjaeger 
       strength  = 20 
       model      = 6 
      } 
     Division = 
     {  experience = 60 
       id         = {  type = 24000 id = 5  } 
       name       = "8. Juntuan" 
       type       = infantry 
       strength  = 20
       model      = 6 
      } 
     Division = 
     {  experience = 60 
       id         = {  type = 24000 id = 6  } 
       name       = "9. Juntuan" 
       type       = infantry 
       strength  = 20
       model      = 6 
      } 
     dig_in   = 20.000 
    } 
   landunit = 
   {  location = 1358 
     name     = "2. Fangmianjun" 
     id       = {  type = 24000 id = 7  } 
     Division = 
     {  experience = 60 
       id         = {  type = 24000 id = 8  } 
       name       = "2. Juntuan" 
       type       = infantry 
       strength  = 20
       model      = 6 
      } 
     Division = 
     {  experience = 60 
       id         = {  type = 24000 id = 9  } 
       name       = "6. Juntuan" 
       type       = infantry 
       strength  = 20
       model      = 6 
      } 
     dig_in   = 20.000 
    } 
   landunit = 
   {  location = 1350 # Xianyang 
     name     = "4. Fangmianjun" 
     id       = {  type = 24000 id = 10  } 
     Division = 
     {  experience = 60 
       id         = {  type = 24000 id = 11  } 
       name       = "4. Jun" 
       type       = infantry 
       strength  = 20
       model      = 6
      } 
     Division = 
     {  experience = 60 
       id         = {  type = 24000 id = 12  } 
       name       = "9. Jun" 
       type       = infantry 
       strength  = 20
       model      = 6
      } 
     Division = 
     {  experience = 60 
       id         = {  type = 24000 id = 13  } 
       name       = "30. Jun" 
       type       = infantry 
       strength  = 20
       model      = 6
      } 
     Division = 
     {  experience = 60 
       id         = {  type = 24000 id = 14  } 
       name       = "31. Jun" 
       type       = infantry 
       strength  = 20
       model      = 6
      } 
     dig_in   = 20.000
    } 
   landunit = 
   {  location = 1337 # Yan'an 
     name     = "15. Juntuan" 
     id       = {  type = 24000 id = 15  } 
     Division = 
     {  experience = 60 
       id         = {  type = 24000 id = 16  } 
       name       = "25. Jun" 
       type       = infantry 
       strength  = 20
       model      = 6
      } 
     Division = 
     {  experience = 60 
       id         = {  type = 24000 id = 17  } 
       name       = "26. Jun" 
       type       = infantry 
       strength  = 20
       model      = 6
      } 
     Division = 
     {  experience = 60 
       id         = {  type = 24000 id = 18  } 
       name       = "27. Jun" 
       type       = infantry 
       strength  = 20
       model      = 6 
      } 
     Division = 
     {  experience = 60 
       id         = {  type = 24000 id = 19  } 
       name       = "28. Jun" 
       type       = infantry 
       strength  = 20
       model      = 6
      } 
     dig_in   = 20.000 
    } 

   landunit = 
   {  location = 1338
     id       = {  type = 28500 id = 4501  } 
     name     = "Di'1 Fang'tien Jüntuan" 
     Division = 
     {  id       = {  type = 28500 id = 4502  } 
       name     = "1 Man'chu Lü" 
       type     = militia
		model = 4   
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 4503  } 
       name     = "2 Man'chu Lü" 
       type     = militia
		model = 4   
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 4504  } 
       name     = "3 Man'chu Lü" 
       type     = militia
		model = 4   
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 4505  } 
       name     = "4 Man'chu Lü" 
       type     = militia
		model = 4   
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 4506  } 
       name     = "5 Man'chu Lü" 
       type     = militia
		model = 4   
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 4507  } 
       name     = "6 Man'chu Lü" 
       type     = militia
		model = 4   
       strength = 50 
      } 
    } 
   landunit = 
   {  location = 1352
     id       = {  type = 28500 id = 4508  } 
     name     = "Di'2 Ji'lin Jüntuan" 
     Division = 
     {  id       = {  type = 28500 id = 4509  } 
       name     = "7 Man'chu Lü" 
       type     = militia 
	   model = 4
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 45010  } 
       name     = "8 Man'chu Lü" 
       type     = militia 
	   model = 4
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 45011  } 
       name     = "9 Man'chu Lü" 
       type     = militia 
	   model = 4
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 45012  } 
       name     = "10 Man'chu Lü" 
       type     = militia 
	   model = 4
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 45013  } 
       name     = "1 Man'chu Qi'Bing" 
       type     = cavalry 
	   model = 7
       strength = 15 
      } 
     Division = 
     {  id       = {  type = 28500 id = 45014  } 
       name     = "2 Man'chu Qi'Bing" 
       type     = cavalry 
	   model = 7
       strength = 15 
      } 
     Division = 
     {  id       = {  type = 28500 id = 45015  } 
       name     = "3 Man'chu Qi'Bing" 
       type     = cavalry 
	   model = 7
       strength = 15 
      } 
    } 
   landunit = 
   {  location = 1357
     id       = {  type = 28500 id = 45016  } 
     name     = "Di'3 Qiqihar Jüntuan" 
     Division = 
     {  id       = {  type = 28500 id = 45017  } 
       name     = "11 Man'chu Lü" 
       type     = militia 
	   model = 4
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 45018  } 
       name     = "12 Man'chu Lü" 
       type     = militia 
	   model = 4
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 45019  } 
       name     = "13 Man'chu Lü" 
       type     = militia 
	   model = 4
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 45020  } 
       name     = "14 Man'chu Lü" 
       type     = militia 
	   model = 4
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 45021  } 
       name     = "15 Man'chu Lü" 
       type     = militia 
	   model = 4
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 45022  } 
       name     = "4 Man'chu Qi'Bing" 
       type     = cavalry 
	   model = 7
       strength = 15 
      } 
    } 
   landunit = 
   {  location = 1359
     id       = {  type = 28500 id = 45023  } 
     name     = "Di'4 Harbin Jüntuan" 
     Division = 
     {  id       = {  type = 28500 id = 45024  } 
       name     = "16 Man'chu Lü" 
       type     = militia 
	   model = 4
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 45025  } 
       name     = "17 Man'chu Lü" 
       type     = militia 
	   model = 4
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 45026  } 
       name     = "18 Man'chu Lü" 
       type     = militia 
	   model = 4
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 45027  } 
       name     = "19 Man'chu Lü" 
       type     = militia 
	   model = 4
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 45028  } 
       name     = "20 Man'chu Lü" 
       type     = militia 
	   model = 4
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 45029  } 
       name     = "21 Man'chu Lü" 
       type     = militia 
	   model = 4
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 45030  } 
       name     = "22 Man'chu Lü" 
       type     = militia 
	   model = 4
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 45031  } 
       name     = "23 Man'chu Lü" 
       type     = militia 
	   model = 4
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 45032  } 
       name     = "5 Man'chu Qi'Bing" 
       type     = cavalry 
	   model = 7
       strength = 15 
      } 
    } 
   landunit = 
   {  location = 1358 
     id       = {  type = 28500 id = 45033  } 
     name     = "Di'5 Chengde Jüntuan" 
     Division = 
     {  id       = {  type = 28500 id = 45034  } 
       name     = "24 Man'chu Lü" 
       type     = militia 
	   model = 4
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 45035  } 
       name     = "25 Man'chu Lü" 
       type     = militia 
	   model = 4
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 45036  } 
       name     = "26 Man'chu Lü" 
       type     = militia 
	   model = 4
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 28500 id = 45037  } 
       name     = "6 Man'chu Qi'Bing" 
       type     = cavalry 
	   model = 7
       strength = 15 
      } 
    } 

  } 
 