##############################
# Country definition for CHI #
##############################

 
 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = CHI 
   capital                = 1317 # Wuhan
   # Resource Reserves 
energy                 = 2100
metal                  = 1050
rare_materials         = 525
   oil                    = 1000 
   supplies               = 1000 
   money                  = 10 
   manpower               = 855 
   dissent                = 0 
   transports             = 100 
   escorts                = 2 
   extra_tc               = 10 
    
   diplomacy = 
   {  relation = {  tag = CHC value = 200  }
     relation = {  tag = CGX value = 100  } 
     relation = {  tag = CSX value = 200  } 
     relation = {  tag = CYN value = -100  } 
     relation = {  tag = JAP value = -100  } 
     relation = {  tag = MAN value = -100  } 
    } 
   SpyInfo                = {  country = "CHI" NumberOfSpies = 5  } 
   # Fujian   
   claimedprovinces = {
#Japan
	1563
#USSR
	1119 #Tuva
	1104 #Khorugh
#India        
	1278 #Sumdo 
	1455 #Itanagar
	1458 #Mipi
	1414 #Putao

#Korea-Manchuria
 	1212 #Yanji->Jilin/Liaoyuan
 	1211 #Hunjiang->Adong/Liaoyuan
#Outer Mongolia 
	1124 #Ulaabaatar
	1123 #Olgii=>Khobdo
	1125 #Muren
	1121 #Bayankhongor
	1122 #Arvaikheer
	1120 #Choibalsan
#Inner Mongolia
	1272 #Linhe=>Bayan Nur(split)
	1270 #Bayan Hot=>Bayan Nur
	1269 #Uqai=>Yuling
	1238 #Huhehaote=>Hohot
	1239 #Jining 
 	1240 #Sili-yin Qota->Xilinhot/Erenhot
 	1237 #Ulayanqada->Xililnhot/Erenhot
 	1209 #Wulanhaote->Ulan Hot/Xilinhot
 	1206 #Haila'er
 	1198 #Butehaqi->Qiqihar
 	1200 #Human->Mohe
 	1210 #Tongliyao Hot->Chifeng
#Outer Tibet      
	1286 #Senge Khabab=>Gar
	1287 #Sger Rtse=>Nagqu
 	1288 #Rgyal Rtse=>Kagar/Xigaze
 	1289 #Lhasa
 	1290 #Ri Bo Che=>Quamdo
	1295 #Nying Khri=>Quamdo
	1294 #Chab Mdo=>Quamdo 
#Inner Tibet
	1285 #Yushu
	1384 #Luxi=>Baoshan(split)
	1389 #Baoshan
	1385 #Dali
	1292 #Ya'an
	1293 #Panzhihua=>Kangding
	1291 #Xichang=>Ya'an(split)
	1262 #Linxia=>Xining(split)
	1284 #Xining
	1283 #Ge'ermu=>Golmud
#Sinkiang        
	1279 #Kaxgar=>Kashgar
 	1274 #Qarqan=>Hotan
 	1282 #Xoten=>Taklimakan Desert
 	1275 #Aqsu=>Aksu
 	1280 #Ghulja
 	1281 #Urumqi
 	1277 #Qumul=>Altay
 	1276 #Karamay
 	1273 #Aletai=>Altay
#Guangxi
	1306 #Kaili
 	1381 #Bose
 	1376 #Debao->Bose
 	1382 #Hechi->Lizhou
 	1379 #Nanning
 	1374 #Pingxiang->Quinzhou
}

   nationalprovinces      = 
{
	1331 #Yantai
	1328 #Quingdao
	1329 #Weifang
	1333 #Huaiyin
	1332 #Zaozhuang
	1261 #Longnan
	1303 #Anshun
	1339 #Suzhou
	1323 #Anyang
	1321 #Xinxiang=>Anyang
	1334 #Nantong
	1336 #Xuzhou
	1340 #Hefei
	1341 #Fuyang
	1319 #Kaifeng
	1322 #Luoyang
	1324 #Zhengzhou
	1325 #Nanyang
	1326 #Xinyang
	1316 #Suizhou=>Xiangfan
	1317 #Wuhan=>Hankou
	1344 #Anqing
	1342 #Xuanzhou=>Wuhu
	1337 #Nanjing
	1338 #Shanghai
	1345 #Hangzhou
	1346 #Ningbo
	1347 #Wenzhou
	1348 #Jinhua=>Ningbo(split)
	1357 #Nanping
	1358 #Fuzhou
	1359 #Sanming
	1360 #Xiamen
	1354 #Ganzhou
	1353 #Jiujiang
	1318 #Huangshi
	1355 #Ji'an=>Zhuzhou
	1309 #Xiangtan=>Shaoyang(split)
	1311 #Chenzhou
	1312 #Hengyang
	1310 #Changde
	1304 #Zunyi
	1302 #Wanxian
	1258 #Xi'an
	1257 #Tongguan=>Xi'an(split)
	1296 #Guanxiang=>Ya'an(split)
	1297 #Chengdu
	1298 #Luzhou=>Zigong
	1305 #Guiyang
	1313 #Shashi
	1307 #Huaihua
	1308 #Changsha
	1356 #Zhangzhou=>Longyang
	1349 #Xingan=>Pingxiang
	1335 #Yancheng=>Nantong(split)
	1314 #Shiyan=>Enshi
	1315 #Yichang
	1267 #Ankang/Nancheng
	1320 #Xuchang
	1299 #Chongqing
	1343 #Huainan=>Yangzhou
	1301 #Fuling
	1350 #Jindezhen=>Quzhou
	1351 #Shangrao
	1352 #Nanchang
	1264 #Lanzhou
	1263 #Tianshui
	1256 #Baoji
#Yunnan          
	1390 #Kunming
	1386 #Pu'er=>Jinghong(split)
	1387 #Jinghong
	1388 #Gejiung
	1300 #Yibin
#Guangxi-Clique
 	1378 #Guilin
 	1380 #Liuzhou
	1383 #Wuzhou
 	1368 #Shaoguan
 	1369 #Guangzhou
 	1375 #Shantou->Chao´an
 	1370 #Lufeng->Bao´an
 	1373 #Jiangmen
 	1377 #Yulin->Maoming
 	1367 #Naoming->Zhanjiang, Maoming
 	1365 #Haikou->Hainan
#Shanxi       
	1241 #Tianjin
	1247 #Beiping
	1246 #Zhangyan=>Kalgan
	1251 #Datong
	1242 #Shijiazhuang
	1254 #Hequ=>Taiyuan
	1252 #Taiyuan
	1253 #Linfen=>Changzhi(split)
	1248 #Changzhi
	1249 #Yangquan=>Handan
	1250 #Lingqui
	1327 #Heze
	1243 #Baoding
	1244 #Changzhou=>Yucheng
	1245 #Tangshan
	1330 #Jinan 
#Sinkiang
	1277
	1281
	1282
#Manchuria
	1214 #Shenyang->Mukden
	1207 #Jilin->Xinjing
 	1202 #Jiamusi->Jixi/Jiamusi
 	1204 #Jixi
 	1205 #Mudanjiang->Jilin/Mudanjiang
 	1199 #Harbin
 	1203 #Qiqihaer
 	1213 #Baicheng->Ulan Hot
 	1220 #Dandong->Dalian
 	1218 #Panjin->Jinxi
 	1201 #Heihe
 	1208 #Changchun->Mukden
 	1215 #Fushun->Adong
 	1217 #Anshan->Dalian
 	1197 #Hegang->Heihe
 	1245 #Tangshan
 	1236 #Chengde->Changde
 	1235 #Fuxin->Changde
 	1216 #Jinzhou->Jinxi 
#Xibei san ma            
	1268 #Yinchuan
	1271 #Wuzhong=>Guyuan
	1265 #Zhangye=>Jinchang
	1266 #Yumen=>Dunhuang
	1262 #Linxia=>Xining(split)
#Communist China      
	1259 #Yan'an
	1260 #Yulin
	1255 #Pingliang
#Japan In China     
	1219 #Port Arthur
#European Possessions     
	1371 #Hongkong
	1372 #Macao
#Taiwan     
	1361 #Gaoxiong
	1362 #Taipei
	1363 #Taizhong
	1364 #Hualian
	}

   ownedprovinces         = 
{    
 	1239 #Jining
 	1238 #Huhehaote->Hohot

	1269 #Uqai=>Yuling
	1268 #Yinchuan
	1270 #Bayan Hot=>Bayan Nur
	1271 #Wuzhong=>Guyuan
	1272 #Linhe=>Bayan Nur(split)
	1265 #Zhangye=>Jinchang
	1266 #Yumen=>Dunhuang
	1283 #Ge'ermu=>Golmud
	1284 #Xining
	1262 #Linxia=>Xining(split)
	1285 #Yushu


	1259 #Yan'an
	1260 
	1255 #Pingliang
	1256 #Baoji
1261 1341 1322 1325 1326 1316 1317 1318 1302 1296 1297 1298 1313 1314 1315 1267 1320 1299 1257 1258 1263 1264 
1340 1344
} 
   controlledprovinces    = 
{
 	1239 #Jining
 	1238 #Huhehaote->Hohot

	1269 #Uqai=>Yuling
	1268 #Yinchuan
	1270 #Bayan Hot=>Bayan Nur
	1271 #Wuzhong=>Guyuan
	1272 #Linhe=>Bayan Nur(split)
	1265 #Zhangye=>Jinchang
	1266 #Yumen=>Dunhuang
	1283 #Ge'ermu=>Golmud
	1284 #Xining
	1262 #Linxia=>Xining(split)
	1285 #Yushu

	1259 #Yan'an
	1260 
	1255 #Pingliang
	1256 #Baoji
1261 1341 1322 1325 1326 1316 1317 1318 1302 1296 1297 1298 1313 1314 1315 1267 1320 1299 1257 1258 1263 1264 
1340 1344
}

						
	# NatChi 1936 techs 
	# ###################### 
	techapps = {
		#Static Defense
		6680
 

	# Manufacturing 
	5810
	# Construction Engineering 
	5800 5080
	# Agriculture
	5700 
	# Crypto
	5316
	# Medicine
	5600

	# Infantry Division  
	1010 1020 1030 1040 1050 1060 1070 1080 
	# Mountain Division
	1160 1170 1180 1190 1200 1210 1220 1230 1240 
	# Cavalry Division  
	13060 13070 13080 1310 1320 1330 1340 1350
	# Engineers
	1830 1840 
	# Supply 
	1910 1920 1930 1940 1950 1960

	# Tank 
	7600 7610 2620 2010 2630
	# Armoured Car  
	2860 2870 2880
	# Field Artillery 
	2290 2300 2310 2900 2910 2920

	# Hospital System
	14000
	# Great War Land Doctrines (entente)
	6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6540 6910
	6570  

	# Destroyers
	3010
	# Light Cruiser 
	3110 3120
	# Heavy Cruiser 
	3210 3220 3230
	# Troopships
	3810

	# Naval Doctrines
	8010 8020 8040 8050 8060 8070 8080

	# Interceptor Fighter  
	4500 4510 4520 4530 4540 4550
	# Multirole Fighter
	4300 4310 4320 
	# Tactical Bomber 
	4600 4610 4620 4630 
	# Strategic Bomber
	4800 4810 
	# Naval Bomber
	4700 

	# Air Doctrines - ww2 techs
	27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 
	} 
	
inventions = { 3000027 }
   ai_settings = { flags = {   legitIndie = 1 } }   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 4 
     political_left    = 7 
     free_market       = 5 
     freedom           = 4 
     professional_army = 4 
     defense_lobby     = 8 
     interventionism   = 5 
    } 
	wartime_ic_mod       = 1.2
   headofstate            = {  type = 9 id = 55113  } #Feng Yuxiang
   headofgovernment       = {  type = 9 id = 55060  } #Jiang Jingguo
   foreignminister        = {  type = 9 id = 55003  } 
   armamentminister       = {  type = 9 id = 55416  } 
   ministerofsecurity     = {  type = 9 id = 55417  } 
   ministerofintelligence = {  type = 9 id = 55005  } 
   chiefofstaff           = {  type = 9 id = 55006  } 
   chiefofarmy            = {  type = 9 id = 55007  } 
   chiefofnavy            = {  type = 9 id = 55009  } 
   chiefofair             = {  type = 9 id = 55010  } 
   dormant_leaders        = {  55368 55375  } 
   # CHINA 1904 Land OOB 
   landunit = 
   {  location = 1337 # Lanzhou 
     name     = "1. Jun" 
     # ## leader = # Chen Jicheng 
     id       = {  type = 22000 id = 1  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 2  } 
       name       = "1. Jun" 
       type       = infantry 
	   strength  = 60
       model     = 6
      } 
     dig_in   = 20.000 
    } 
   landunit = 
   {  location = 1257 # near Xi'an 
     name     = "7. Jun" 
     leader = 55083 # Zeng Wanzhong 
     id       = {  type = 22000 id = 18  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 19  } 
       name       = "7. Jun" 
       type       = infantry 
	   strength  = 60 
       model      = 6 
      } 
     dig_in   = 20.000 
    } 
   landunit = 
   {  location = 1358 # Fuzhou 
     name     = "14. Jun" 
     leader = 55329 # Wei Lihuang 
     id       = {  type = 22000 id = 30  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 31  } 
       name       = "14. Jun" 
       type       = infantry 
	   strength  = 60 
       model      = 5 
      } 
    } 
   landunit = 
   {  location = 1355 # Pingxiang 
     name     = "22. Jun" 
     # ## leader = # Tan Taoyuan 
     id       = {  type = 22000 id = 54  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 55  } 
       name       = "22. Jun" 
       type       = infantry 
	   strength  = 60 
       model      = 6 
      } 
    } 
   landunit = 
   {  location = 1355 # Pingxiang 
     name     = "27. Jun" 
     leader = 55209 # Liu Xing 
     id       = {  type = 22000 id = 65  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 66  } 
       name       = "27. Jun" 
       type       = infantry 
	   strength  = 60 
       model      = 6 
      } 
    } 
   landunit = 
   {  location = 1322 # Luoyang 
     name     = "30. Jun" 
     leader = 55266 # Sun Lianzhong 
     id       = {  type = 22000 id = 72  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 73  } 
       name       = "30. Jun" 
       type       = infantry 
	   strength  = 60 
       model      = 5 
      } 
     dig_in   = 20.000 
    } 
   landunit = 
   {  location = 1257 # Xi'an 
     name     = "37. Jun" 
     leader = 55242 # Mao Pingwen 
     id       = {  type = 22000 id = 90  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 91  } 
       name       = "37. Jun" 
       type       = infantry 
	   strength  = 60 
       model      = 6 
      } 
     dig_in   = 20.000 
    } 
   landunit = 
   {  location = 1337 # Baoji 
     name     = "38. Jun" 
     leader = 55270 # Sun Weiru 
     id       = {  type = 22000 id = 93  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 94  } 
       name       = "38. Jun" 
       type       = infantry 
	   strength  = 60 
       model      = 6 
      } 
     dig_in   = 20.000 
    } 
   landunit = 
   {  location = 1347 # Wenzhou 
     name     = "39. Jun" 
     leader = 55207 # Liu Heding 
     id       = {  type = 22000 id = 95  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 96  } 
       name       = "39. Jun" 
       type       = infantry 
	   strength  = 60 
       model      = 6 
      } 
    } 
   landunit = 
   {  location = 1347 # Anyang 
     name     = "40. Jun" 
     leader = 55250 # Pang Bingxun 
     id       = {  type = 22000 id = 97  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 98  } 
       name       = "40. Jun" 
       type       = infantry 
	   strength  = 60 
       model      = 6 
      } 
    } 
   landunit = 
   {  location = 1257 # near Xi'an 
     name     = "46. Jun" 
     # ## leader = # Fan Songfu 
     id       = {  type = 22000 id = 119  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 120  } 
       name       = "46. Jun" 
       type       = infantry 
	   strength  = 60 
       model      = 6 
      } 
     dig_in   = 20.000 
    } 
   landunit = 
   {  location = 1258 # Xi'an 
     name     = "51. Jun" 
     leader = 55011 # Yu Xuezhong (Zhang Xuezhong substituted) 
     id       = {  type = 22000 id = 124  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 125  } 
       name       = "51. Jun" 
       type       = infantry 
	   strength  = 60 
       model      = 5 
      } 
     dig_in   = 20.000 
    } 
   landunit = 
   {  location = 1257 # near Xi'an 
     name     = "57. Jun" 
     # ## leader = # Dong Yingbin 
     id       = {  type = 22000 id = 133  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 134  } 
       name       = "57. Jun" 
       type       = infantry 
	   strength  = 60 
       model      = 6 
      } 
     dig_in   = 20.000 
    } 
   landunit = 
   {  location = 1258 # Xi'an 
     name     = "67. Jun" 
     leader = 55319 # Wang Yizhe 
     id       = {  type = 22000 id = 138  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 139  } 
       name       = "67. Jun" 
       type       = infantry 
	   strength  = 60 
       model      = 6 
      } 
     dig_in   = 20.000 
    } 
   landunit = 
   {  location = 1337 # Lanzhou 
     name     = "1. Xin Jun" 
     leader = 55285 # Deng Baoshan 
     id       = {  type = 22000 id = 142  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 143  } 
       name       = "1. Xin Jun" 
       type       = infantry 
	   strength  = 60 
       model      = 6 
      } 
     dig_in   = 20.000 
    } 
   landunit = 
   {  location = 1348 # Quzhou 
     name     = "4. Lujun" 
     # ## leader = # 
     id       = {  type = 22000 id = 151  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 152  } 
       name       = "4. Lujun" 
       type       = infantry 
	   strength  = 60 
       model      = 5 
      } 
    } 
   landunit = 
   {  location = 1258 # Xi'an 
     name     = "4. Lujun" 
     leader = 55340 # Yang Hucheng 
     id       = {  type = 22000 id = 163  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 164  } 
       name       = "4. Lujun" 
       type       = infantry 
	   strength  = 60 
       model      = 6 
      } 
     dig_in   = 20.000 
    } 
   landunit = 
   {  location = 1352 # Nanchang 
     name     = "20. Lujun" 
     leader = 55008 # Zhang Fang 
     id       = {  type = 22000 id = 165  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 166  } 
       name       = "20. Lujun" 
       type       = infantry 
	   strength  = 60 
       model      = 6 
      } 
    } 
   landunit = 
   {  location = 1336 # Yangzhou 
     name     = "26. Lujun" 
     # ## leader = # 
     id       = {  type = 22000 id = 168  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 169  } 
       name       = "26. Lujun" 
       type       = infantry 
	   strength  = 60 
       model      = 5 
      } 
    } 
   landunit = 
   {  location = 1337 # Nanjing 
     name     = "2. Bubing Shi" 
     leader = 55044 # Zheng Dongguo 
     id       = {  type = 22000 id = 170  } 
     Division = 
     {  experience   = 20 
       id           = {  type = 22000 id = 171  } 
       name         = "2. Bubing Shi" 
       type         = infantry 
       max_strength = 80 
       strength     = 80 
       model        = 6 
      } 
     dig_in   = 20.000 
    } 
   landunit = 
   {  location = 1345 # Hangzhou 
     name     = "21. Bubing Shi" 
     leader = 55177 # Li Xianzhou 
     id       = {  type = 22000 id = 172  } 
     Division = 
     {  experience   = 20 
       id           = {  type = 22000 id = 173  } 
       name         = "21. Bubing Shi" 
       type         = infantry 
       max_strength = 50 
       strength     = 50 
       model        = 6 
      } 
    } 
   landunit = 
   {  location = 1334 # Xiangfan 
     name     = "51. Bubing Shi" 
     leader = 55326 # Wang Yaoyu 
     id       = {  type = 22000 id = 176  } 
     Division = 
     {  experience   = 20 
       id           = {  type = 22000 id = 177  } 
       name         = "51. Bubing Shi" 
       type         = infantry 
       max_strength = 50 
       strength     = 50 
       model        = 6 
      } 
    } 
   landunit = 
   {  location = 1316 # Xiangfan 
     name     = "Jiangxi Silingbu" 
     # ## leader = # 
     id       = {  type = 22000 id = 178  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 179  } 
       name       = "Jiangxi Silingbu" 
       type       = infantry 
	   strength  = 60 
       model      = 6 
      } 
    } 
   landunit = 
   {  location = 1358 # Fuzhou 
     name     = "Fujian Silingbu" 
     # ## leader = # 
     id       = {  type = 22000 id = 194  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 195  } 
       name       = "Fujian Silingbu" 
       type       = infantry 
	   strength  = 60 
       model      = 6 
      } 
    } 
   landunit = 
   {  location = 1341 # Fuyang 
     name     = "Anhui Silingbu" 
     # ## leader = # 
     id       = {  type = 22000 id = 208  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 209  } 
       name       = "Anhui Silingbu" 
       type       = infantry 
	   strength  = 60 
       model      = 6 
      } 
    } 
   landunit = 
   {  location = 1319 # Kaifeng 
     name     = "Henan Silingbu" 
     # ## leader = # 
     id       = {  type = 22000 id = 211  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 212  } 
       name       = "Henan Silingbu" 
       type       = infantry 
	   strength  = 60 
       model      = 6 
      } 
    } 
   landunit = 
   {  location = 1317 # Hankou 
     name     = "Hubei Silingbu" 
     # ## leader = # 
     id       = {  type = 22000 id = 224  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 225  } 
       name       = "Hubei Silingbu" 
       type       = infantry 
	   strength  = 60 
       model      = 6 
      } 
    } 
   landunit = 
   {  location = 1317 # Hankou 
     name     = "Xibei Silingbu" 
     # ## leader = # 
     id       = {  type = 22000 id = 232  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 233  } 
       name       = "Xibei Silingbu" 
       type       = infantry 
	   strength  = 60 
       model      = 6 
      } 
    } 
   landunit = 
   {  location = 1337 # Nanjing 
     name     = "Jiaodao Zongdui" 
     leader = 55157 # Gui Yongqing 
     id       = {  type = 22000 id = 242  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 243  } 
       name       = "Jiaodao Zongdui" 
       type       = infantry 
	   strength  = 60 
       model      = 6 
      } 
    } 
   landunit = 
   {  location = 1333 # Lianyungang 
     name     = "Suijing Zongtuan" 
     leader = 55126 # Huang Jie 
     id       = {  type = 22000 id = 244  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 245  } 
       name       = "Customs Police 1st Detachment" 
       type       = infantry 
	   strength  = 60 
       model      = 5 
      } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 246  } 
       name       = "Customs Police 2nd Detachment" 
       type       = infantry 
	   strength  = 60 
       model      = 6 
      } 
    } 
   landunit = 
   {  location = 1338 # Shanghai 
     name     = "Shanghai Jingbei" 
     leader = 55339 # Yang Hu 
     id       = {  type = 22000 id = 247  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 248  } 
       name       = "Shanghai Jingbei" 
       type       = infantry 
	   strength  = 60 
       model      = 5 
      } 
    } 
   landunit = 
   {  location = 1338 # Ningbo 
     name     = "Marine Brigade" 
     # ## leader = # 
     id       = {  type = 22000 id = 251  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 252  } 
       name       = "Marine Brigade" 
       type       = garrison 
       model      = 3
      } 
    } 
   landunit = 
   {  location = 1337 # Nanjing 
     name     = "Jiangsu Baoantui" 
     # ## leader = # 
     id       = {  type = 22000 id = 254  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 255  } 
       name       = "Jiangsu Baoantui" 
       type       = militia 
	   strength  = 60 
       model      = 3
      } 
    } 
   landunit = 
   {  location = 1344 # Anqing 
     name     = "Anhui Baoantui" 
     # ## leader = # 
     id       = {  type = 22000 id = 256  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 257  } 
       name       = "Anhui Baoantui" 
       type       = militia 
	   strength  = 60 
       model      = 3
      } 
    } 
   landunit = 
   {  location = 1345 # Hangzhou 
     name     = "Zhejiang Baoantui" 
     # ## leader = # 
     id       = {  type = 22000 id = 258  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 259  } 
       name       = "Zhejiang Baoantui" 
       type       = militia 
	   strength  = 60 
       model      = 3
      } 
    } 
   landunit = 
   {  location = 1309 # Changsha 
     name     = "Hunan Baoantui" 
     # ## leader = # 
     id       = {  type = 22000 id = 260  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 261  } 
       name       = "Hunan Baoantui" 
       type       = militia 
	   strength  = 60 
       model      = 3
      } 
    } 
   landunit = 
   {  location = 1318 # Wuchang 
     name     = "Hubei Baoantui" 
     # ## leader = # 
     id       = {  type = 22000 id = 262  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 263  } 
       name       = "Hubei Baoantui" 
       type       = militia 
	   strength  = 60 
       model      = 3
      } 
    } 
   landunit = 
   {  location = 1319 # Kaifeng 
     name     = "Henan Baoantui" 
     # ## leader = # 
     id       = {  type = 22000 id = 264  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 265  } 
       name       = "Henan Baoantui" 
       type       = militia 
	   strength  = 60 
       model      = 3
      } 
    } 
   landunit = 
   {  location = 1337 # Lanzhou 
     name     = "Gansu Baoantui" 
     # ## leader = # 
     id       = {  type = 22000 id = 268  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 269  } 
       name       = "Gansu Baoantui" 
       type       = militia 
	   strength  = 60 
       model      = 3
      } 
     dig_in   = 20.000 
    } 
   landunit = 
   {  location = 1352 # Nanchang 
     name     = "Jiangxi Baoantui" 
     # ## leader = # 
     id       = {  type = 22000 id = 274  } 
     Division = 
     {  experience = 20 
       id         = {  type = 22000 id = 275  } 
       name       = "Jiangxi Baoantui" 
       type       = militia 
	   strength  = 60 
       model      = 3
      } 
    } 
   landunit = 
   {  location = 1358 # Fuzhou 
     name     = "Fujian Baoantui" 
     # ## leader = # 
     id       = {  type = 22000 id = 276  } 
     Division = 
     {  id         = {  type = 22000 id = 278  } 
       experience = 20 
       name       = "Fujian Baoantui" 
       type       = militia 
	   strength  = 60 
       model      = 3
      } 
    } 
# zone semi-demilitarized per Japanese demands (no infantry divisions)
# However they cannot stop formation of volunteer armies
# The exact number of divisions can be adjusted for game balance as needed.
   landunit = 
   {  location = 1247 # Beiping
     name     = "3. Lujun" 
     id       = {  type = 22301 id = 1  } 
     Division = 
     {  id       = {  type = 22301 id = 2  } 
       name     = "22. Bubing Shi" 
       type     = militia 
       strength  = 40 
       model = 5
      } 
     Division = 
     {  id       = {  type = 22301 id = 3  } 
       name     = "23. Bubing Shi" 
       type     = militia 
       strength  = 40 
       model = 5
      } 
    } 
   landunit = 
   {  location = 1241 # Tianjin 
     name     = "Hebei Jingbei" 
     id       = {  type = 22301 id = 4 } 
     Division = 
     {  id       = {  type = 22301 id = 5  } 
       name     = "Hebei Baoantui" 
       type     = militia 
       strength  = 40 
       model = 5
      } 
    } 
   landunit = 
   {  location = 1242 # Baoding 
     name     = "53. Jun" 
     id       = {  type = 22001 id = 6  } 
     Division = 
     {  id    = {  type = 22001 id = 7  } 
       name  = "53. Jun" 
       type     = militia 
	   strength  = 40 
       model = 5 
      } 
    } 	
	
   # China 1904 Naval OOB 
   navalunit = 
   {  location = 1338 # Shanghai 
     base     = 1338 
     name     = "1st Fleet" 
     id       = {  type = 22000 id = 300  } 
     Division = 
     {  id    = {  type = 22000 id = 301  } 
       name  = "Ning-Hai" 
       type  = light_cruiser 
       model = 2
      } 
     Division = 
     {  id    = {  type = 22000 id = 302  } 
       name  = "Ying-Swei" 
       type  = light_cruiser 
       model = 1
      } 
     Division = 
     {  id    = {  type = 22000 id = 303  } 
       name  = "Chao-Ho" 
       type  = light_cruiser 
       model = 1
      } 
     Division = 
     {  id    = {  type = 22000 id = 304  } 
       name  = "Hai-Chen" 
       type  = light_cruiser 
       model = 1
      } 
     Division = 
     {  id    = {  type = 22000 id = 307  } 
       name  = "1. Quzujian Dadui" 
       type  = destroyer 
       model = 1
      } 
     Division = 
     {  id    = {  type = 22000 id = 308  } 
       name  = "2. Quzujian Dadui" 
       type  = destroyer 
       model = 1
      } 
     Division = 
     {  id    = {  type = 22000 id = 309  } 
       name  = "1. Yunshujian Dadui" 
       type  = transport 
       model = 0
      } 
    } 
   # China 1904 Airforce OOB 
   airunit = 
   {  location = 1352 # Nanchang 
     id       = {  type = 22000 id = 400  } 
     name     = "1. Kongjun" 
     base     = 1352 # Nanchang 
     Division = 
     {  id           = {  type = 22000 id = 401  } 
       name         = "1. Kongjun" 
       max_strength = 60 
       strength     = 54 
       type         = tactical_bomber 
       model        = 4 
      } 
    } 
   airunit = 
   {  location = 1352 # Nanchang 
     id       = {  type = 22000 id = 407  } 
     name     = "2. Kongjun" 
     base     = 1352 # Nanchang 
     Division = 
     {  id           = {  type = 22000 id = 408  } 
       name         = "2. Kongjun" 
       max_strength = 60 
       strength     = 52 
       type         = interceptor 
       model        = 4 
      } 
    } 
  } 
 