 
 ############################## 
 # Country definition for CGX # 
 ############################## 

 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = CGX 
   regular_id             = CHI 
   intrinsic_gov_type     = paternal_autocrat 
   extra_tc               = 10 
   # Resource Reserves 
energy                 = 600
metal                  = 300
rare_materials         = 150
   transports = 100
   oil                    = 100 
   supplies               = 100 
   money                  = 50 
   capital                = 1378 # Guilin 
   manpower               = 32 
   dissent                = 0 
   diplomacy = 
   {  relation = {  tag = CHC value = -200  } 
     relation = {  tag = CHI value = 100  } 
     relation = {  tag = CSX value = 200  } 
     relation = {  tag = CXB value = 200  } 
     relation = {  tag = CYN value = 200  } 
     relation = {  tag = U67 value = 150  } 
     relation = {  tag = JAP value = -75  } 
     relation = {  tag = MAN value = -75  } 
    } 
   SpyInfo                = {  country = "CGX" NumberOfSpies = 2  } 
	ownedprovinces = {
 	#Guangxi-Clique
 	1378 #Guilin
 	1380 #Liuzhou
	1383 #Wuzhou
 	1381 #Bose
 	1379 #Nanning
 	1374 #Pingxiang->Quinzhou
 	1376 #Debao->Bose
 	1382 #Hechi->Lizhou
	
	#Guangdong
 	1368 #Shaoguan
 	1369 #Guangzhou
 	1375 #Shantou->Chao´an
 	1370 #Lufeng->Bao´an
 	1373 #Jiangmen
 	1377 #Yulin->Maoming
 	1367 #Naoming->Zhanjiang, Maoming
 	1365 #Haikou->Hainan 

1360 1356 1349 1354 1355 1311 1353 1308 1309 1312 1306 1310 1307 1301 1304
	}

	controlledprovinces = {
	#Guangxi-Clique
 	1378 #Guilin
 	1380 #Liuzhou
	1383 #Wuzhou
 	1381 #Bose
 	1379 #Nanning
 	1374 #Pingxiang->Quinzhou
 	1376 #Debao->Bose
 	1382 #Hechi->Lizhou
	
	#Guangdong
 	1368 #Shaoguan
 	1369 #Guangzhou
 	1375 #Shantou->Chao´an
 	1370 #Lufeng->Bao´an
 	1373 #Jiangmen
 	1377 #Yulin->Maoming
 	1367 #Naoming->Zhanjiang, Maoming
 	1365 #Haikou->Hainan

1360 1356 1349 1354 1355 1311 1353 1308 1309 1312 1306 1310 1307 1301 1304
	}

claimedprovinces = {
#Japan
	1563
#USSR
	1119 #Tuva
	1104 #Khorugh
#India        
	1278 #Sumdo 
	1455 #Itanagar
	1458 #Mipi
	1414 #Putao

#Korea-Manchuria
 	1212 #Yanji->Jilin/Liaoyuan
 	1211 #Hunjiang->Adong/Liaoyuan
#Outer Mongolia 
	1124 #Ulaabaatar
	1123 #Olgii=>Khobdo
	1125 #Muren
	1121 #Bayankhongor
	1122 #Arvaikheer
	1120 #Choibalsan
#Inner Mongolia
	1272 #Linhe=>Bayan Nur(split)
	1270 #Bayan Hot=>Bayan Nur
	1269 #Uqai=>Yuling
	1238 #Huhehaote=>Hohot
	1239 #Jining 
 	1240 #Sili-yin Qota->Xilinhot/Erenhot
 	1237 #Ulayanqada->Xililnhot/Erenhot
 	1209 #Wulanhaote->Ulan Hot/Xilinhot
 	1206 #Haila'er
 	1198 #Butehaqi->Qiqihar
 	1200 #Human->Mohe
 	1210 #Tongliyao Hot->Chifeng
#Outer Tibet      
	1286 #Senge Khabab=>Gar
	1287 #Sger Rtse=>Nagqu
 	1288 #Rgyal Rtse=>Kagar/Xigaze
 	1289 #Lhasa
 	1290 #Ri Bo Che=>Quamdo
	1295 #Nying Khri=>Quamdo
	1294 #Chab Mdo=>Quamdo 
#Inner Tibet
	1285 #Yushu
	1384 #Luxi=>Baoshan(split)
	1389 #Baoshan
	1385 #Dali
	1292 #Ya'an
	1293 #Panzhihua=>Kangding
	1291 #Xichang=>Ya'an(split)
	1262 #Linxia=>Xining(split)
	1284 #Xining
	1283 #Ge'ermu=>Golmud
#Sinkiang        
	1279 #Kaxgar=>Kashgar
 	1274 #Qarqan=>Hotan
 	1275 #Aqsu=>Aksu
 	1280 #Ghulja
 	1273 #Aletai=>Altay
 	1276 #Karamay
#Guangxi
	1306 #Kaili
 	1381 #Bose
 	1376 #Debao->Bose
 	1382 #Hechi->Lizhou
 	1379 #Nanning
 	1374 #Pingxiang->Quinzhou
}

   nationalprovinces      = 
{
	1331 #Yantai
	1328 #Quingdao
	1329 #Weifang
	1333 #Huaiyin
	1332 #Zaozhuang
	1261 #Longnan
	1303 #Anshun
	1339 #Suzhou
	1323 #Anyang
	1321 #Xinxiang=>Anyang
	1334 #Nantong
	1336 #Xuzhou
	1340 #Hefei
	1341 #Fuyang
	1319 #Kaifeng
	1322 #Luoyang
	1324 #Zhengzhou
	1325 #Nanyang
	1326 #Xinyang
	1316 #Suizhou=>Xiangfan
	1317 #Wuhan=>Hankou
	1344 #Anqing
	1342 #Xuanzhou=>Wuhu
	1337 #Nanjing
	1338 #Shanghai
	1345 #Hangzhou
	1346 #Ningbo
	1347 #Wenzhou
	1348 #Jinhua=>Ningbo(split)
	1357 #Nanping
	1358 #Fuzhou
	1359 #Sanming
	1360 #Xiamen
	1354 #Ganzhou
	1353 #Jiujiang
	1318 #Huangshi
	1355 #Ji'an=>Zhuzhou
	1309 #Xiangtan=>Shaoyang(split)
	1311 #Chenzhou
	1312 #Hengyang
	1310 #Changde
	1304 #Zunyi
	1302 #Wanxian
	1258 #Xi'an
	1257 #Tongguan=>Xi'an(split)
	1296 #Guanxiang=>Ya'an(split)
	1297 #Chengdu
	1298 #Luzhou=>Zigong
	1305 #Guiyang
	1313 #Shashi
	1307 #Huaihua
	1308 #Changsha
	1356 #Zhangzhou=>Longyang
	1349 #Xingan=>Pingxiang
	1335 #Yancheng=>Nantong(split)
	1314 #Shiyan=>Enshi
	1315 #Yichang
	1267 #Ankang/Nancheng
	1320 #Xuchang
	1299 #Chongqing
	1343 #Huainan=>Yangzhou
	1301 #Fuling
	1350 #Jindezhen=>Quzhou
	1351 #Shangrao
	1352 #Nanchang
	1264 #Lanzhou
	1263 #Tianshui
	1256 #Baoji
#Yunnan          
	1390 #Kunming
	1386 #Pu'er=>Jinghong(split)
	1387 #Jinghong
	1388 #Gejiung
	1300 #Yibin
#Guangxi-Clique
 	1378 #Guilin
 	1380 #Liuzhou
	1383 #Wuzhou
 	1368 #Shaoguan
 	1369 #Guangzhou
 	1375 #Shantou->Chao´an
 	1370 #Lufeng->Bao´an
 	1373 #Jiangmen
 	1377 #Yulin->Maoming
 	1367 #Naoming->Zhanjiang, Maoming
 	1365 #Haikou->Hainan
#Shanxi       
	1241 #Tianjin
	1247 #Beiping
	1246 #Zhangyan=>Kalgan
	1251 #Datong
	1242 #Shijiazhuang
	1254 #Hequ=>Taiyuan
	1252 #Taiyuan
	1253 #Linfen=>Changzhi(split)
	1248 #Changzhi
	1249 #Yangquan=>Handan
	1250 #Lingqui
	1327 #Heze
	1243 #Baoding
	1244 #Changzhou=>Yucheng
	1245 #Tangshan
	1330 #Jinan 
#Manchuria
	1214 #Shenyang->Mukden
	1207 #Jilin->Xinjing
 	1202 #Jiamusi->Jixi/Jiamusi
 	1204 #Jixi
 	1205 #Mudanjiang->Jilin/Mudanjiang
 	1199 #Harbin
 	1203 #Qiqihaer
 	1213 #Baicheng->Ulan Hot
 	1220 #Dandong->Dalian
 	1218 #Panjin->Jinxi
 	1201 #Heihe
 	1208 #Changchun->Mukden
 	1215 #Fushun->Adong
 	1217 #Anshan->Dalian
 	1197 #Hegang->Heihe
 	1245 #Tangshan
 	1236 #Chengde->Changde
 	1235 #Fuxin->Changde
 	1216 #Jinzhou->Jinxi 
#Xibei san ma            
	1268 #Yinchuan
	1271 #Wuzhong=>Guyuan
	1265 #Zhangye=>Jinchang
	1266 #Yumen=>Dunhuang
	1262 #Linxia=>Xining(split)
#Sinkiang
 	1277 #Qumul=>Altay
	1281 #Urumqi
 	1282 #Xoten=>Taklimakan Desert
#Communist China      
	1259 #Yan'an
	1260 #Yulin
	1255 #Pingliang
#Japan In China     
	1219 #Port Arthur
#European Possessions     
	1371 #Hongkong
	1372 #Macao
#Taiwan     
	1361 #Gaoxiong
	1362 #Taipei
	1363 #Taizhong
	1364 #Hualian
	}

   # Guangxi 
   # ROTW Minor Tech '36 
   # Group E 1936 techs 
   # ###################### 
   # GW fighter 
   techapps = {
		#Static Defense
		6680
  
#Interwar Fighter  
4500 4510 4520 4530
#Interwar Armoured Car  
2860
#Light Field Artillery  
2290
#SW Tank 
7600 7610
#Great War Infantry Division  
1010 1020 1030 1040 1050 1060
#Interbellum 1930 Supply 
1910 1920 1930 1940 1950 1960
#1916 Cavalry Division  
13060 13070 13080 1310 1320 1330 1340 
#Early Agriculture
5700 



#Great War Destroyer 
3010 3020 3030 3040
#Early Light Cruiser 
3110 3120 3130

#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 
# Great War Land Doctrines (entente)
6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6540 6910
} 
inventions = { 3000027 }
   ai_settings = { flags = {   legitIndie = 1 } }   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 3 
     political_left    = 2 
     freedom           = 3 
     free_market       = 3 
     professional_army = 2 
     defense_lobby     = 6 
     interventionism   = 4 
    } 
   headofstate            = {  type = 9 id = 585001  } 
   headofgovernment       = {  type = 9 id = 585002  } 
   foreignminister        = {  type = 9 id = 585003  } 
   armamentminister       = {  type = 9 id = 585004  } 
   ministerofsecurity     = {  type = 9 id = 585005  } 
   ministerofintelligence = {  type = 9 id = 585006  } 
   chiefofstaff           = {  type = 9 id = 585007  } 
   chiefofarmy            = {  type = 9 id = 585008  } 
   chiefofnavy            = {  type = 9 id = 585009  } 
   chiefofair             = {  type = 9 id = 585010  } 
   # ###### 
   # GUANGXI OOB 
   # ###### 
   landunit = 
   {  location = 1369 # Guangzhou 
     name     = "1. Juntuan" 
     # ## leader = # Chen Jitang 
     id       = {  type = 22400 id = 1  } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 2  } 
       name       = "Xunlian Bubing Shi" 
       type     = militia 
       strength   = 40 
       model      = 3
      } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 3  } 
       name       = "1. Duli Bubing Shi" 
       type       = militia 
       strength   = 40 
       model      = 3
      } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 4  } 
       name       = "Jingbei Lü" 
       type       = militia 
       strength   = 40 
       model      = 3
      } 
    } 
   landunit = 
   {  location = 1383 # Shaoguan 
     name     = "1. Jun" 
     # ## leader = # Yu Hanmou 
     id       = {  type = 22400 id = 5  } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 6  } 
       name       = "1. Bubing Shi" 
       type     = garrison 
       strength   = 40 
       model      = 2
      } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 7  } 
       name       = "2. Bubing Shi" 
       type     = garrison 
       strength   = 40 
       model      = 2
      } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 8  } 
       name       = "3. Bubing Shi" 
       type       = garrison 
       strength   = 40 
       model      = 2
      } 
    } 
   landunit = 
   {  location = 1375 # Shantou 
     name     = "2. Jun" 
     # ## leader = # Chang Ta 
     id       = {  type = 22400 id = 9  } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 10  } 
       name       = "4. Bubing Shi" 
       type     = militia 
       strength   = 40 
       model      = 3
      } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 11  } 
       name       = "5. Bubing Shi" 
       type       = militia 
       strength   = 40 
       model      = 3
      } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 12  } 
       name       = "6. Bubing Shi" 
       type       = militia 
       strength   = 40 
       model      = 3
      } 
    } 
   landunit = 
   {  location = 1383 # Maoming 
     name     = "3. Jun" 
     # ## leader = # Yu Hanmou 
     id       = {  type = 22400 id = 13  } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 14  } 
       name       = "7. Bubing Shi" 
       type       = militia 
       strength   = 40 
       model      = 3
      } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 15  } 
       name       = "8. Bubing Shi" 
       type       = militia 
       strength   = 40 
       model      = 3
      } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 16  } 
       name       = "9. Bubing Shi" 
       type       = militia 
       strength   = 40 
       model      = 3
      } 
    } 
   landunit = 
   {  location = 1380 # Guilin 
     name     = "4. Juntuan" 
     # ## leader = # Li Zongren 
     id       = {  type = 22400 id = 17  } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 18  } 
       name       = "19. Lujun" 
       type       = militia 
       strength   = 30 
       model      = 3
      } 
    } 
   landunit = 
   {  location = 1382 # Liuzhou 
     name     = "7. Jun" 
     # ## leader = # Liao Lei 
     id       = {  type = 22400 id = 19  } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 20  } 
       name       = "19. Bubing Shi" 
       type       = militia 
       strength   = 40 
       model      = 3
      } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 21  } 
       name       = "21. Bubing Shi" 
       type       = militia 
       strength   = 40 
       model      = 3
      } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 22  } 
       name       = "22. Bubing Shi" 
       type       = militia 
       strength   = 40 
       model      = 3
      } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 23  } 
       name       = "24. Bubing Shi" 
       type       = militia 
       strength   = 40 
       model      = 3
      } 
    } 
   landunit = 
   {  location = 1379 # Nanning 
     name     = "15. Jun" 
     # ## leader = # Xia Wei 
     id       = {  type = 22400 id = 24  } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 25  } 
       name       = "42. Bubing Shi" 
       type       = militia 
       strength   = 40 
       model      = 3
      } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 26  } 
       name       = "43. Bubing Shi" 
       type       = militia 
       strength   = 40 
       model      = 3
      } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 27  } 
       name       = "44. Bubing Shi" 
       type       = militia 
       strength   = 40 
       model      = 3
      } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 28  } 
       name       = "45. Bubing Shi" 
       type       = militia 
       strength   = 40 
       model      = 3
      } 
    } 
   landunit = 
   {  location = 1369 # Guangzhou 
     name     = "Guangdong Jingbei" 
     id       = {  type = 22400 id = 29  } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 30  } 
       name       = "Guangdong Baoantui" 
       type       = militia 
       strength   = 40 
       model      = 3
      } 
    } 
   landunit = 
   {  location = 1380 # Guilin 
     name     = "Guangxi Jingbei" 
     id       = {  type = 22400 id = 31  } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 32  } 
       name       = "Guangdong Baoantui" 
       type       = militia 
       strength   = 40 
       model      = 3
      } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 33  } 
       name       = "Guangdong Bubing Jun" 
       type       = militia 
       strength   = 40 
       model      = 3
      } 
    } 
   landunit = 
   {  location = 1365 # Hainan 
     name     = "Hainan Jingbei" 
     id       = {  type = 22400 id = 34  } 
     Division = 
     {  experience = 30 
       id         = {  type = 22400 id = 35  } 
       name       = "9. Duli Lü" 
       type       = militia 
       strength   = 40 
       model      = 3
      } 
    } 
   landunit = 
   {  location = 1381 # Bose 
     name     = "9. Jun" 
     # ## leader = 50089 # Hao Menglin 
     id       = {  type = 22000 id = 20  } 
     Division = 
     {  experience = 30 
       id         = {  type = 22000 id = 21  } 
       name       = "9. Jun" 
       type       = militia 
	   strength  = 40 
       model      = 3
      } 
    } 
   landunit = 
   {  location = 1382 # Liuzhou 
     name     = "28. Jun" 
     # leader = X # ? 
     id       = {  type = 22000 id = 67  } 
     Division = 
     {  experience = 30 
       id         = {  type = 22000 id = 68  } 
       name       = "28. Jun" 
       type       = militia 
	   strength  = 40 
       model      = 3
      } 
    } 
   landunit = 
   {  location = 1380 # Guilin 
     name     = "Hunan Xi Jingbei" 
     # ## leader = # 
     id       = {  type = 22000 id = 192  } 
     Division = 
     {  experience   = 30 
       id           = {  type = 22000 id = 193  } 
       name         = "34. Xin Bubing Shi" 
       type         = militia 
       max_strength = 50 
       strength     = 50 
       model        = 3
      } 
    } 
   landunit = 
   {  location = 1383 # Wuzhou 
     name     = "Ningbo Jingbei" 
     # ## leader = # 
     id       = {  type = 22000 id = 215  } 
     Division = 
     {  id           = {  type = 22000 id = 216  } 
       name         = "37. Duli Bubing Lü" 
       type         = militia 
       max_strength = 25 
       strength     = 25 
       model        = 3
      } 
    } 
   landunit = 
   {  location = 1383 # Shaoguan 
     name     = "20. Jun" 
     # ## leader = 50162 # Guo Rudong 
     id       = {  type = 22000 id = 106  } 
     Division = 
     {  id    = {  type = 22000 id = 107  } 
       name  = "20. Jun" 
       type  = militia 
	   strength  = 40 
       model = 3
      } 
    } 
   landunit = 
   {  location = 1369 # Guangzhou 
     name     = "2. Jun" 
     # ## leader = 50050 # Jiang Dingwen 
     id       = {  type = 22000 id = 6  } 
     Division = 
     {  id    = {  type = 22000 id = 7  } 
       name  = "2. Jun" 
       type  = militia 
	   strength  = 40 
       model = 3
      } 
    } 
   landunit = 
   {  location = 1375 # Chao'an 
     name     = "16. Jun" 
     # ## leader = # Li Yunyan 
     id       = {  type = 22000 id = 36  } 
     Division = 
     {  id    = {  type = 22000 id = 37  } 
       name  = "16. Jun" 
       type  = militia 
	   strength  = 40 
       model = 3
      } 
    } 
   landunit = 
   {  location = 1375 # Shantou 
     name     = "36. Jun" 
     # ## leader = # Chou Hunyuan 
     id       = {  type = 22000 id = 87  } 
     Division = 
     {  id    = {  type = 22000 id = 88  } 
       name  = "36. Jun" 
       type  = militia 
	   strength  = 40 
       model = 3
      } 
    } 
   landunit = 
   {  location = 1381 # Bose 
     name     = "14. Lujun" 
     # ## leader = # 
     id       = {  type = 22000 id = 161  } 
     Division = 
     {  id    = {  type = 22000 id = 162  } 
       name  = "14. Lujun" 
       type  = militia 
	   strength  = 40 
       model = 3
      } 
    } 
   landunit = 
   {  location = 1382 # Liuzhou 
     name     = "18. Jun" 
     # ## leader = 50219 # Luo Zhuoying 
     id       = {  type = 22000 id = 38  } 
     Division = 
     {  id    = {  type = 22000 id = 39  } 
       name  = "18. Jun" 
       type  = militia 
	   strength  = 40 
       model = 3
      } 
    } 
   landunit = 
   {  location = 1380 # Guilin 
     name     = "26. Jun" 
     # ## leader = 50104 # Xiao Zhichu 
     id       = {  type = 22000 id = 62  } 
     Division = 
     {  id    = {  type = 22000 id = 63  } 
       name  = "26. Jun" 
       type  = militia 
	   strength  = 40 
       model = 3
      } 
    } 
   # ##### NAVY OOB ###### 
   navalunit = 
   {  location = 1369 # Guangzhou 
     name     = "Guangdong Haijun" 
     id       = {  type = 22400 id = 40  } 
     base     = 1369 
     Division = 
     {  id    = {  type = 22400 id = 43  } 
       name  = "1. Yunshuji Dadui" 
       type  = transport 
       model = 0 
      } 
    } 
   # ##### AIR FORCE OOB ###### 
   airunit = 
   {  location = 1369 # Guangzhou 
     name     = "Guangxi Kongjun" 
     base     = 1369 # Guangzhou 
     id       = {  type = 22400 id = 38  } 
     Division = 
     {  id           = {  type = 22400 id = 39  } 
       name         = "Guangxi Hang Kong Dui" 
       type         = interceptor 
       model        = 5
       max_strength = 40 
       strength     = 20 
      } 
    } 
  } 
 