 
 ############################## 
 # Country definition for FRA # 
 ############################## 
 
 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = FRA 
   capital                = 55 
   # Resource Reserves 
energy                 = 7440
metal                  = 3720
rare_materials         = 1860
   oil                    = 500 
   supplies               = 500 
   money                  = 50 
   manpower               = 528 
   transports             = 600 
   escorts                = 60 
     dissent = 1
     research_mod = 0.75

   
   diplomacy = 
   {  relation = {  tag = AST value = 150  } 
     relation = {  tag = AUS value = -10  } 
     relation = 
     {  tag        = BEL 
       value      = 120 
       guaranteed = {  day = 7 month = january year = 1935  } 
      } 
     relation = {  tag = BHU value = 150  } 
     relation = {  tag = BUL value = 20  } 
     relation = {  tag = CAN value = 150  } 
     relation = {  tag = CZE value = 150  } 
     relation = {  tag = ENG value = 150  } 
     relation = {  tag = EST value = 65  } 
     relation = {  tag = ETH value = 25  } 
     relation = {  tag = FIN value = 85  } 
     relation = {  tag = GER value = -35  } 
     relation = {  tag = GRE value = 20  } 
     relation = 
     {  tag        = HOL 
       value      = 75 
       guaranteed = {  day = 7 month = january year = 1935  } 
      } 
     relation = {  tag = HUN value = -70  } 
     relation = {  tag = IRE value = 25  } 
     relation = {  tag = IRQ value = 100  } 
     relation = {  tag = ITA value = -50  } 
     relation = {  tag = JAP value = -20  } 
     relation = {  tag = LAT value = 65  } 
     relation = {  tag = LIT value = 65  } 
     relation = 
     {  tag        = LUX 
       value      = 120 
       guaranteed = {  day = 7 month = january year = 1935  } 
      } 
     relation = {  tag = NEP value = 150  } 
     relation = 
     {  tag        = NOR 
       guaranteed = {  day = 30 month = august year = 1934  } 
      } 
     relation = {  tag = NZL value = 150  } 
     relation = {  tag = OMN value = 150  } 
     relation = 
     {  tag        = POL 
       value      = 100 
       guaranteed = {  day = 7 month = january year = 1935  } 
      } 
     relation = {  tag = ROM value = 50  } 
     relation = {  tag = SAF value = 150  } 
     relation = {  tag = SAU value = 10  } 
     relation = 
     {  tag        = SCH 
       value      = 1 
       guaranteed = {  day = 16 month = may year = 1935  } 
      } 
     relation = {  tag = SIA value = -100  } 
     relation = {  tag = SOV value = 100  } 
     relation = {  tag = SPR value = 10  } 
     relation = 
     {  tag        = TUR 
       value      = 50 
       guaranteed = {  day = 7 month = january year = 1935  } 
      } 
     relation = {  tag = U03 value = 50 access = yes  }  
     relation = {  tag = U04 value = 50 access = yes  }  
     relation = {  tag = USA value = 65  } 
     relation = {  tag = YEM value = 150  } 
     relation = 
     {  tag        = YUG 
       value      = 50 
       guaranteed = {  day = 7 month = january year = 1935  } 
      } 
    } 
   SpyInfo                = {  country = "FRA" NumberOfSpies = 9  } 
   # Togoland 
   # Metropolitan France 
claimedprovinces = {
#External claims
#Canada
	1786
	1794
	1843
	2108
	2110
	2112
	2114
	2115
	2116
	2117
	2118
	2119
	2120
	2121
	2122
	2123
	2124
	2125
	2126
	2127
	2128
	2129
	2130
	2131
	2132
	2133
	2134

#Rhineland
	126
	127
	128
	129
	130
	131

#North Germany
	141
	147
	148

#Netherlands
	125 #Rotterdam
	122 #Amsterdam
	123 #Middelburg=>Rotterdam(split)
	118 #Eindhoven
	119 #Arnheim=>Utrecht/Arnheim(merge)
	124 #Groningen=>Groningen/Leeuwarden(merge)
	120 #Nijmegen=>Eindhoven(split)
	121 #Maastricht=>Eindhoven(split)

#Belgium
	108
	109
	110
	111
	112
	113
	114
	115
	116
	117

#North Italy
	396
	398
	399
	410
	413
	414
	416
	419

#Spain
	436
	437
	439
	440

#Lousiana
	1931
	1932
	1934
	1937
	1944
	
### Karibik
   2000 #Cayenne#
   1767 #Guadeloupe#
   1768 #Martinique#
   #Maroc
   724 #Qujda#
   726 #Er Rachidia=>Bouarfa#
   725 #Ouarzazate=>Quezzane#
   721 #Fes=>Marakesh(split)#
   717 #Rabat#
   718 #Casablanca#
   722 #Marrakesh#
   723 #Khenifra=>Marakesh(split)#
   720 #Agadir#
   719 #Tiznit#
   #Algerien
   738 #Tamanrasset#
   737 #Touggourt#
   739 #Colom Bechar#
   743 #Tebessa#
   #734 #Constantine#
   #735 #Bona#
   731 #Batna#
   732 #Djelfa#
   736 #Bougie#
   733 #Geryville#
   #727 #Algiers#
   730 #Orleansville#
   #728 #Oran#
   #729 #Tlemcen#
   #Tunesien
   741 #Tataouine#
   744 #Gabes#
   740 #Kasserine#
   742 #Medenine#
   745 #Sousse#
   746 #El Kef#
   747 #Tunis#
   748 #Bizerte#
   749 #Beja#
   # Libanon/Syrien
   1019 #Beirut#
   1020 #Golan#
   1016 #Damascus#
   1018 #Trablos#
   1017 #Hims#
   1021 #Aleppo#
   1014 #Deir ez Zor#	
   1015 #El Qmisli#
   # Indochina
   1392 #Hai Phong#
   1393 #Hoa Binh#
   1395 #Hanoi#
   1404 #Muang Xay#
   1391 #Muang Xaignabouli#
   1405 #Vientiane#
   1396 #Dong Hoi#
   1394 #Pakxe#
   1397 #Da Nang#
   1399 #Saigon#
   1398 #Lumphat=>Pakse#
   1401 #Siem Reap#
   1402 #Battambang#
   1400 #Phnom Penh#
   1403 #Can Tho#
### Afrika   
   833 #Djibouti#	
   981 #Nouakchott=>Port Etienne#
   982 #Kiffa#
   943 #Zinder#
   944 #Niamey#
   942 #Say#
   984 #Gao#
   985 #Tombouctou# 
   974 #Mopti#
   978 #Dakar#
   980 #Ziguinchor#
   966 #Conakry#
   965 #Labe#
   975 #Kayes#
   971 #Nioro du Sahel#
   972 #Segou#
   973 #Sikasso#
   976 #Bamako#
   959 #Bobo-Dioulasso#
   957 #Ouagadougou#
   949 #Natitingou#
   951 #Cotonou#
   967 #Kankan#
   960 #Yamoussoukro#
   962 #Abidjan#
   910 #Bertoua#
   922 #Faya#
   920 #Fort Lamy#
   924 #Moundou#
   925 #Maroua#
   923 #Bambari#
   926 #Bangui#
   909 #Yaounde#
   928 #N'Gaoundere#
   911 #Douala#
   914 #Franceville#
   915 #Libreville#
   907 #Brazzaville#
   908 #Quesso=>Impfondo#
   #Madagaskar
   1001 #Tananarive#
   1002 #Tamatave#
   1003 #Fort Dauphin#
   # 
   996 #Saint Denis de la Reunion#
   1586 #Nouvelle-Caledonie#
   1585 #Ouvea#
   1584 #Tanna#
   1583 #Malekula#
   1582 #Espiritu Santo#
   1581 #Efate#
   #
   950 #Lome#
   948 #Kara#
   917 #Pointe-Noire#
   918 #Fort Gentil#
   919 #Bouar#
   927 #Ouadda#
   921 #Abeche#
   946 #Agadez#
   947 #Tahoua#
   945 #Tenkodogo#
   958 #Tougan#
   961 #Bouake#
   968 #Korhogo#
   970 #San Pedro#
   977 #Tambacounda#
   983 #Saint-Louis#
   986 #Atar#
   999 #Muruni
   1000 #Mamoudzou
   1740 #Rikitea
   1743 #Papeete#
   1744 #Taiohae
   1730 #Mata'utu
   1752 #St-Martin
   2135 #Saint-Pierre
   
   
   1054 #Antalya 

#Internal claims
	37
	39
	41

	105
	107

}
   
   nationalprovinces  = {
#Algeria
	727
	735
	734 #Constantine#
	728 #Oran#
	729 #Tlemcen#

#Belgium
	108
	111
	112
	113
	116
  
   #Metropole France
   49 #Calais#
   52 #Lille#
   50 #Amiens#
   103 #Hirson#=>Valenciennes
   101 #Laon#=>Valenciennes
   53 #Dieppe#
   102 #Sedan#
   56 #Chateau Thierry=>Compiegne#
   55 #Paris#
   45 #Le Havre#
   44 #Caen#
   46 #Bayeux#
   43 #Cherbourg#
   38 #Rennes#
   42 #Avranches#
   47 #Falaise=>Argentan#
   48 #Evreux=>Argentan(split)#
   99 #Reims#
   104 #Metz
   51 #Dunkirk
   100 #Verdun#
   96 #Longwy#
   106 #Nancy#
   54 #Troyes#
   60 #Chartres#
   58 #Le Mans#
   59 #Angers#
   40 #Saint Nazaire=>Nantes#
   66 #Orleans#
   95 #Chaumont#
   97 #Belfort#
   63 #Auxerre#
   65 #Bourges#
   61 #Tours#
   62 #Poitiers=>Cholet(split)#
   57 #Nantes=>Cholet(split)#
   69 #La Rochelle#
   73 #Limoges#
   72 #Chateauroux#
   74 #Vichy#
   64 #Le Creusot#
   98 #Pontarlier=>Besancon#
   88 #Bourg-en-Bresse#
   85 #Lyon#
   68 #Bordeaux#
   70 #Angouleme=>La Rochelle(split)#
   75 #Perigueux#
   76 #Tulle#
   71 #Clermont-Ferrand#
   78 #Saint Etienne#
   92 #Valence#
   91 #Chambery#
   90 #Grenoble#
   93 #Avignon#
   81 #Rodez#
   77 #Toulouse#
   84 #Agen#
   67 #Mont-de-Marsan#
   83 #Pau#
   80 #Perpignan#
   79 #Beziers#
   82 #Montpellier#
   89 #Marseille#
   86 #Toulon#
   87 #Nice#
   94 #Corsica#
   #Schweiz
   391 #Geneva
   } 
   
   ownedprovinces = {
   1054 #Antalya 
   #Metropole France
   51 #Dunkirk
   49 #Calais
   52 #Lille
   50 #Amiens
   103 #Hirson
   101 #Laon
   53 #Dieppe
   102 #Sedan
   56 #Chateau Thierry
   55 #Paris
   45 #Le Havre
   44 #Caen
   46 #Bayeux
   43 #Cherbourg
   37 #Brest
   41 #Saint Brieuc
   38 #Rennes
   42 #Avranches
   47 #Falaise
   48 #Evreux
   99 #Reims
   100 #Verdun
   96 #Longwy
   104 #Metz
   107 #Strasbourg
   105 #Colmar
   106 #Nancy
   54 #Troyes
   60 #Chartres
   58 #Le Mans
   59 #Angers
   39 #Lorient
   40 #Saint Nazaire
   66 #Orleans
   95 #Chaumont
   97 #Belfort
   63 #Auxerre
   65 #Bourges
   61 #Tours
   62 #Poitiers
   57 #Nantes
   69 #La Rochelle
   73 #Limoges
   72 #Chateauroux
   74 #Vichy
   64 #Le Creusot
   98 #Pontarlier
   88 #Bourg-en-Bresse
   85 #Lyon
   68 #Bordeaux
   70 #Angouleme
   75 #Perigueux
   76 #Tulle
   71 #Clermont-Ferrand
   78 #Saint Etienne
   92 #Valence
   91 #Chambery
   90 #Grenoble
   93 #Avignon
   81 #Rodez
   77 #Toulouse
   84 #Agen
   67 #Mont-de-Marsan
   83 #Pau
   80 #Perpignan
   79 #Beziers
   82 #Montpellier
   89 #Marseille
   86 #Toulon
   87 #Nice
   94 #Corsica
### Karibik
   2000 #Cayenne#
   1767 #Guadeloupe#
   1768 #Martinique#
   #Maroc
   724 #Qujda#
   726 #Er Rachidia=>Bouarfa#
   725 #Ouarzazate=>Quezzane#
   721 #Fes=>Marakesh(split)#
   717 #Rabat#
   718 #Casablanca#
   722 #Marrakesh#
   723 #Khenifra=>Marakesh(split)#
   720 #Agadir#
   719 #Tiznit#
   #Algerien
   738 #Tamanrasset#
   737 #Touggourt#
   739 #Colom Bechar#
   743 #Tebessa#
   734 #Constantine#
   735 #Bona#
   731 #Batna#
   732 #Djelfa#
   736 #Bougie#
   733 #Geryville#
   727 #Algiers#
   730 #Orleansville#
   728 #Oran#
   729 #Tlemcen#
   #Tunesien
   741 #Tataouine#
   744 #Gabes#
   740 #Kasserine#
   742 #Medenine#
   745 #Sousse#
   746 #El Kef#
   747 #Tunis#
   748 #Bizerte#
   749 #Beja#
   # Libanon/Syrien
   1019 #Beirut#
   1020 #Golan#
   1016 #Damascus#
   1018 #Trablos#
   1017 #Hims#
   1021 #Aleppo#
   1014 #Deir ez Zor#	
   1015 #El Qmisli#
   # Indochina
   1392 #Hai Phong#
   1393 #Hoa Binh#
   1395 #Hanoi#
   1404 #Muang Xay#
   1391 #Muang Xaignabouli#
   1405 #Vientiane#
   1396 #Dong Hoi#
   1394 #Pakxe#
   1397 #Da Nang#
   1399 #Saigon#
   1398 #Lumphat=>Pakse#
   1401 #Siem Reap#
   1402 #Battambang#
   1400 #Phnom Penh#
   1403 #Can Tho#
### Afrika   
   833 #Djibouti#	
   981 #Nouakchott=>Port Etienne#
   982 #Kiffa#
   943 #Zinder#
   944 #Niamey#
   942 #Say#
   984 #Gao#
   985 #Tombouctou# 
   974 #Mopti#
   978 #Dakar#
   980 #Ziguinchor#
   966 #Conakry#
   965 #Labe#
   975 #Kayes#
   971 #Nioro du Sahel#
   972 #Segou#
   973 #Sikasso#
   976 #Bamako#
   959 #Bobo-Dioulasso#
   957 #Ouagadougou#
   949 #Natitingou#
   951 #Cotonou#
   967 #Kankan#
   960 #Yamoussoukro#
   962 #Abidjan#
   910 #Bertoua#
   922 #Faya#
   920 #Fort Lamy#
   924 #Moundou#
   925 #Maroua#
   923 #Bambari#
   926 #Bangui#
   909 #Yaounde#
   928 #N'Gaoundere#
   911 #Douala#
   914 #Franceville#
   915 #Libreville#
   907 #Brazzaville#
   908 #Quesso=>Impfondo#
   #Madagaskar
   1001 #Tananarive#
   1002 #Tamatave#
   1003 #Fort Dauphin#
   # 
   996 #Saint Denis de la Reunion#
   1586 #Nouvelle-Caledonie#
   1585 #Ouvea#
   1584 #Tanna#
   1583 #Malekula#
   1582 #Espiritu Santo#
   1581 #Efate#
   #
   950 #Lome#
   948 #Kara#
   917 #Pointe-Noire#
   918 #Fort Gentil#
   919 #Bouar#
   927 #Ouadda#
   921 #Abeche#
   946 #Agadez#
   947 #Tahoua#
   945 #Tenkodogo#
   958 #Tougan#
   961 #Bouake#
   968 #Korhogo#
   970 #San Pedro#
   977 #Tambacounda#
   983 #Saint-Louis#
   986 #Atar#
   999 #Muruni
   1000 #Mamoudzou
   1740 #Rikitea
   1743 #Papeete#
   1744 #Taiohae
   1730 #Mata'utu
   1752 #St-Martin
   2135 #Saint-Pierre
   } 
 
   controlledprovinces  = {
   1054 #Antalya 
   #Metropole France
   51 #Dunkirk
   49 #Calais
   52 #Lille
   50 #Amiens
   103 #Hirson
   101 #Laon
   53 #Dieppe
   102 #Sedan
   56 #Chateau Thierry
   55 #Paris
   45 #Le Havre
   44 #Caen
   46 #Bayeux
   43 #Cherbourg
   37 #Brest
   41 #Saint Brieuc
   38 #Rennes
   42 #Avranches
   47 #Falaise
   48 #Evreux
   99 #Reims
   100 #Verdun
   96 #Longwy
   104 #Metz
   107 #Strasbourg
   105 #Colmar
   106 #Nancy
   54 #Troyes
   60 #Chartres
   58 #Le Mans
   59 #Angers
   39 #Lorient
   40 #Saint Nazaire
   66 #Orleans
   95 #Chaumont
   97 #Belfort
   63 #Auxerre
   65 #Bourges
   61 #Tours
   62 #Poitiers
   57 #Nantes
   69 #La Rochelle
   73 #Limoges
   72 #Chateauroux
   74 #Vichy
   64 #Le Creusot
   98 #Pontarlier
   88 #Bourg-en-Bresse
   85 #Lyon
   68 #Bordeaux
   70 #Angouleme
   75 #Perigueux
   76 #Tulle
   71 #Clermont-Ferrand
   78 #Saint Etienne
   92 #Valence
   91 #Chambery
   90 #Grenoble
   93 #Avignon
   81 #Rodez
   77 #Toulouse
   84 #Agen
   67 #Mont-de-Marsan
   83 #Pau
   80 #Perpignan
   79 #Beziers
   82 #Montpellier
   89 #Marseille
   86 #Toulon
   87 #Nice
   94 #Corsica
   #
   2000 #Cayenne
   1767 #Guadeloupe
   1768 #Martinique
   #Maroc
   724 #Qujda
   726 #Er Rachidia
   725 #Ouarzazate
   721 #Fes
   717 #Rabat
   718 #Casablanca
   722 #Marrakesh
   723 #Khenifra
   720 #Agadir
   719 #Tiznit
   #Algerien
   738 #Tamanrasset
   737 #Touggourt
   739 #Colom Bechar
   743 #Tebessa
   734 #Constantine
   735 #Bona
   731 #Batna
   732 #Djelfa
   736 #Bougie
   733 #Geryville
   727 #Algiers
   730 #Orleansville
   728 #Oran
   729 #Tlemcen
   #Tunesien
   741 #Tataouine
   744 #Gabes
   740 #Kasserine
   742 #Medenine
   745 #Sousse
   746 #El Kef
   747 #Tunis
   748 #Bizerte
   749 #Beja
   # Libanon/Syrien
   1019 #Beirut
   1020 #Golan
   1016 #Damascus
   1018 #Trablos
   1017 #Hims
   1021 #Aleppo
   1014 #Deir ez Zor	
   1015 #El Qmisli
   # Indochina
   1392 #Hai Phong
   1393 #Hoa Binh
   1395 #Hanoi
   1404 #Muang Xay
   1391 #Muang Xaignabouli
   1405 #Viang-chan
   1396 #Dong Hoi
   1394 #Pakxe
   1397 #Da Nang
   1399 #Saigon
   1398 #Lumphat
   1401 #Siem Reap
   1402 #Battambang
   1400 #Phnom Penh
   1403 #Can Tho
   #Afrika   
   833 #Djibouti	
   981 #Nawaksut
   982 #Kiffa
   943 #Zinder
   944 #Niamey
   942 #Say
   984 #Gao
   985 #Timbuktu 
   974 #Mopti
   978 #Dakar
   980 #Ziguinchor
   966 #Conakry
   965 #Labe
   975 #Kayes
   971 #Nioro du Sahel
   972 #Segou
   973 #Sikasso
   976 #Bamako
   959 #Bobo-Dioulasso
   957 #Ouagadougou
   949 #Natitingou
   951 #Cotonou
   967 #Kankan
   960 #Yamoussoukro
   962 #Abidjan
   910 #Bertoua
   922 #Faya
   920 #Fort Lamy
   924 #Moundou
   925 #Maroua
   923 #Bambari
   926 #Bangui
   909 #Yaounde
   928 #N'Gaoundere
   911 #Douala
   914 #Franceville
   915 #Libreville
   907 #Brazzaville
   908 #Quesso
   #Madagaskar
   1001 #Tananarive
   1002 #Tamatave
   1003 #Fort Dauphin
   # 
   996 #Saint Denis de la Reunion    
   1586 #Nouvelle-Caledonie
   1585 #Ouvea
   1584 #Tanna
   1583 #Malekula
   1582 #Espiritu Santo
   1581 #Efate
   #
   950 #Lome
   948 #Kara
   917 #Pointe-Noire
   918 #Fort Gentil
   919 #Bouar
   927 #Ouadda
   921 #Abech
   946 #Agadez
   947 #Tahoua
   945 #Tenkodogo
   958 #Tougan
   961 #Bouake
   968 #Korhogo
   970 #San Pedro
   977 #Tambacounda
   983 #Saint-Louis
   986 #Atar
   999 #Muruni
   1000 #Mamoudzou
   1740 #Rikitea
   1743 #Papeete
   1744 #Taiohae
   1730 #Mata'utu
   1752 #St-Martin
   2135 #Saint-Pierre
   } 
		 
   # FRA 1936 techs 
   # ###################### 
   techapps = {
		#Static Defense
		6680
 
#Basic Armoured Car  
2860 2870 2880 2020 2150
#Early Tank 
7600 7610 2620 2010 2630 2640 2646 2650 
#Great War Heavy Field Artillery 
2290 2300 2310 2900
#Early Static Anti-Air Artillery 
2800 2450 21180 21190
#Basic Anti-Air Artillery Brigade 
2810 2820 2510
#Early Anti-Tank Artillery 
##2400
#Early Infantry Division  
1010  1020 1030 1040 1050 1060 1070 1080 1090
#1930 Cavalry Division  
13060 13070 13080 1310 1320 1330 1340 1350 1360 1370
#Early Mountain Division 
1160  1170 1180 1190 1200 1210 1220 1230 1240
#Motorised Inf
1396
#Naval Infantry
1560
#Engineers
1830 1840 1850 1860
#Interbellum 1930 Supply 
1910 1920 1930 1940 1950 1960 1970 1980
#Modern Agriculture 
5700 5710 5010
#Basic Machine Tools 
5810 5820 5050 5830 5060
#Improved Construction Engineering 
5800 5080 5090 
#improved Oil Refining #5190

#Computers 
5310 54010 54020 54030
#cryptografi
5316 5326
#Faculty of Atomic Research 
5470 5480
#Medicine
5600 5610 5620 5630
#Exp. Rocket
5560

#Improved Destroyer 
3010 3020 3030 3040 3050 3060 
#Basic Light Cruiser 
3110 3120 3130 3140 3150 3160
#Improved Heavy Cruiser 
3210 3220 3230 3240 3250 3260 
#Early Battleship 
3410 3420 3430 3440 3450 3456 3460 3470
#Great War Air Carrier 
3510
#Improved Light carrier 
12100 12110 12120
#Short Range Submarine 
3610 3620 3630 3640
# Battle Cruiser
3310 3320 3330 3340
#Torpedo & ASW 18
3720 3730 3736 3740 3750 3900
#Troopships
3810 3820

#Early Fighter  
4500 4510 4520 4530 4540 4550 4010 4020
#Early Bomber 
4600 4610 4620 4630 4120 4130
#Multirole fighter
4300 4310 4320 4330
#SEAPLANES
4740 4750 4760 4770
#ww1 strategic bomber
4800 4810 4820
#ww1 navalbomber
4700 4710
#CAG 30
4900 4910
#Great War Hospital System 
14000 14010 14020

# Great War Land Doctrines (entente)
6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6540 6910
#Land Doctrines
6560 6030

#Naval Doctrines
# Theories
8010 8020 8030 8040 8050 8060 8070 8080 
# Amphibious Warfare
82300
# Naval Logistics
82500
# Naval Interdiction
8500 8510 8550 8600 
# Engagement Tactic (Fleet-in-Being)
8900 8910 8920 8930 8940
# Naval Supremacy
8100 8110 8120 8150 8160 8200 8210

#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 9040

} 
inventions = { 3000027 }
   ai_settings = { flags = {   legitIndie = 1 } }   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 9 
     political_left    = 6 
     free_market       = 7 
     freedom           = 9 
     professional_army = 5 
     defense_lobby     = 7 
     interventionism   = 5 
    } 
   headofstate            = {  type = 9 id = 5001  } 
   headofgovernment       = {  type = 9 id = 5002  } 
   foreignminister        = {  type = 9 id = 5003  } 
   armamentminister       = {  type = 9 id = 5004  } 
   ministerofsecurity     = {  type = 9 id = 5005  } 
   ministerofintelligence = {  type = 9 id = 5006  } 
   chiefofstaff           = {  type = 9 id = 5007  } 
   chiefofarmy            = {  type = 9 id = 5008  } 
   chiefofnavy            = {  type = 9 id = 5009  } 
   chiefofair             = {  type = 9 id = 5010  } 
   # #################
   # ###FRENCH OOB####
   # #################
   landunit = 
   {  id       = {  type = 13500 id = 1  } 
     name     = "Région militaire de Paris" 
     leader   = 5076 # Gamelin
     location = 55 
     Division = 
     {  id       = {  type = 13500 id = 201  } 
       name     = "Grand Quartier Général" 
       type     = hq 
       model    = 2 
       strength = 10 
      } 
     Division = 
     {  id    = {  type = 13500 id = 2  } 
       name  = "10ème Division d'Infanterie" 
       type  = infantry 
	   model = 7
      } 
     Division = 
     {  id   = {  type = 13500 id = 3  } 
       name = "3ème Division d'Infanterie Coloniale" 
       type = infantry 
	   model = 6
      } 
     Division = 
     {  id    = {  type = 13500 id = 4  } 
       name  = "2ème Division Légère Mécanisée" 
       strength = 80
       type  = light_armor 
       model = 0
       extra    = anti_air 
	   brigade_model = 2
      } 
     Division = 
     {  id       = {  type = 13500 id = 5  } 
       name     = "3ème Division de Cavalerie" 
       type     = cavalry 
       model    = 7 
       extra    = light_armor_brigade 
	   brigade_model = 1
      } 
     Division = 
     {  id    = {  type = 13500 id = 6  } 
       name  = "41ème Division d'Infanterie" 
       strength = 10
       type  = infantry 
	   model = 6
      } 
     Division = 
     {  id    = {  type = 13500 id = 7  } 
       name  = "71ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 8  } 
     name     = "Corps d'Armée Colonial" 
     location = 55 
     Division = 
     {  id    = {  type = 13500 id = 9  } 
       name  = "5ème Division d'Infanterie Coloniale" 
       strength = 10
       type  = infantry 
	   model = 5
      } 
     Division = 
     {  id    = {  type = 13500 id = 10  } 
       name  = "6ème Division d'Infanterie Coloniale"
       strength = 10 
       type  = infantry 
	   model = 5
      } 
     Division = 
     {  id    = {  type = 13500 id = 11  } 
       name  = "7ème Division d'Infanterie Coloniale" 
       strength = 10
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 12  } 
     name     = "Ier Corps d'Armée" 
     location = 52 
     Division = 
     {  id    = {  type = 13500 id = 13  } 
       name  = "1ère Division d'Infanterie Motorisée" 
       type  = infantry 
       model = 7 
       extra = armored_car 
	   brigade_model = 4
      } 
     Division = 
     {  id    = {  type = 13500 id = 14  } 
       name  = "2ème Division d'Infanterie" 
       strength = 10 
       type  = infantry 
	   model = 6
      }
     Division = 
     {  id    = {  type = 13500 id = 15  } 
       name  = "51ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    }
   landunit = 
   {  id       = {  type = 13500 id = 16  } 
     name     = "IIème Corps d'Armée" 
     location = 50 
     Division = 
     {  id   = {  type = 13500 id = 17  } 
       name = "4ème Division d'Infanterie"
       strength = 10 
       type = infantry 
	   model = 6
      }
     Division = 
     {  id       = {  type = 13500 id = 18  } 
       name     = "3ème Division d'Infanterie Motorisée" 
       strength = 70 
       type     = infantry 
       model    = 8 
       extra    = armored_car 
	   brigade_model = 3
      }
     Division = 
     {  id    = {  type = 13500 id = 19  } 
       name  = "52ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 20  } 
     name     = "IIIème Corps d'Armée" 
     location = 45 
     Division = 
     {  id   = {  type = 13500 id = 21  } 
       name = "6ème Division d'Infanterie"
       strength = 10 
       type = infantry 
	   model = 6
      }
     Division = 
     {  id       = {  type = 13500 id = 22  } 
       name     = "5ème Division d'Infanterie Motorisée" 
       strength = 70 
       type     = infantry 
       model    = 8 
       extra    = armored_car 
	   brigade_model = 3
      }
     Division = 
     {  id    = {  type = 13500 id = 23  } 
       name  = "53ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 24  } 
     name     = "IVème Corps d'Armée" 
     location = 58 
     Division = 
     {  id   = {  type = 13500 id = 25  } 
       name = "19ème Division d'Infanterie" 
       type = infantry
	   model = 7
      } 
     Division = 
     {  id   = {  type = 13500 id = 26  } 
       name = "7ème Division d'Infanterie"
       strength = 10 
       type = infantry 
	   model = 6
      }
     Division = 
     {  id   = {  type = 13500 id = 27  } 
       name = "20ème Division d'Infanterie"
       strength = 10 
       type = infantry 
	   model = 6
      }
     Division = 
     {  id    = {  type = 13500 id = 28  } 
       name  = "54ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 29  } 
     name     = "Vème Corps d'Armée" 
     location = 66 
     Division = 
     {  id       = {  type = 13500 id = 30  } 
       name     = "1ère Division de Cavalerie" 
       type     = cavalry 
       model    = 7 
      } 
     Division = 
     {  id       = {  type = 13500 id = 31  } 
       name     = "9ème Division d'Infanterie Motorisée" 
       strength = 70 
       type     = infantry 
	   model = 7
       extra    = armored_car 
	   brigade_model = 3
      } 
     Division = 
     {  id   = {  type = 13500 id = 32  } 
       name = "45ème Division d'Infanterie" 
       strength = 10
       type = infantry 
	   model = 6
      } 
     Division = 
     {  id    = {  type = 13500 id = 33  } 
       name  = "55ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 34  } 
     name     = "VIème Corps d'Armée" 
     location = 104 
     Division = 
     {  id       = {  type = 13500 id = 35  } 
       name     = "42ème Division d'Infanterie" 
       type     = infantry 
	   model = 7
       extra    = light_armor_brigade 
	   brigade_model = 1
      } 
     Division = 
     {  id       = {  type = 13500 id = 36  } 
       name     = "2ème Division d'Infanterie Nord-Africaine" 
       type     = infantry 
	   model = 6
       extra    = light_armor_brigade 
	   brigade_model = 0
      } 
     Division = 
     {  id    = {  type = 13500 id = 37  } 
       name  = "55ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 38  } 
     name     = "VIIème Corps d'Armée" 
     location = 97 
     Division = 
     {  id       = {  type = 13500 id = 39  } 
       name     = "13ème Division d'Infanterie" 
       type     = infantry 
	   model = 7
      } 
     Division = 
     {  id       = {  type = 13500 id = 40  } 
       name     = "14ème Division d'Infanterie" 
       type     = infantry 
	   model = 7
      } 
     Division = 
     {  id   = {  type = 13500 id = 41  } 
       name = "47ème Division d'Infanterie" 
       strength = 10
       type = infantry 
	   model = 6
      } 
     Division = 
     {  id    = {  type = 13500 id = 42  } 
       name  = "57ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 43  } 
     name     = "VIIIème Corps d'Armée" 
     location = 64 
     Division = 
     {  id   = {  type = 13500 id = 44  } 
       name = "16ème Division d'Infanterie"
       strength = 10 
       type = infantry 
	   model = 6
      }
     Division = 
     {  id       = {  type = 13500 id = 45  } 
       name     = "15ème Division d'Infanterie Motorisée" 
       strength = 70 
       type     = infantry 
       model    = 8 
       extra    = armored_car 
	   brigade_model = 3
      }
     Division = 
     {  id    = {  type = 13500 id = 46  } 
       name  = "58ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 47  } 
     name     = "IXème Corps d'Armée" 
     location = 61 
     Division = 
     {  id       = {  type = 13500 id = 48  } 
       name     = "23ème Division d'Infanterie" 
       type     = infantry 
	   model = 7
       extra    = light_armor_brigade 
	   brigade_model = 1
      } 
     Division = 
     {  id       = {  type = 13500 id = 49  } 
       name     = "3ème Division d'Infanterie Nord-Africaine" 
       type     = infantry 
	   model = 6
      } 
     Division = 
     {  id    = {  type = 13500 id = 50  } 
       name  = "18ème Division d'Infanterie"
       strength = 10 
       type  = infantry 
	   model = 6
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 51  } 
     name     = "Xème Corps d'Armée" 
     location = 107 
     Division = 
     {  id       = {  type = 13500 id = 52  } 
       name     = "43ème Division d'Infanterie" 
       type     = infantry 
	   model = 7
      } 
     Division = 
     {  id    = {  type = 13500 id = 53  } 
       name  = "60ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 54  } 
     name     = "XIème Corps d'Armée" 
     location = 57 
     Division = 
     {  id       = {  type = 13500 id = 55  } 
       name     = "21ème Division d'Infanterie" 
       type     = infantry 
	   model = 7
      } 
     Division = 
     {  id   = {  type = 13500 id = 56  } 
       name = "22ème Division d'Infanterie" 
       strength = 10
       type = infantry 
	   model = 6
      } 
     Division = 
     {  id    = {  type = 13500 id = 57  } 
       name  = "61ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 58  } 
     name     = "XIIème Corps d'Armée" 
     location = 99 
     Division = 
     {  id    = {  type = 13500 id = 59  } 
       name  = "1ère Division Légère Mécanisée" 
       strength = 75
       type  = light_armor 
       model = 0
      } 
     Division = 
     {  id   = {  type = 13500 id = 60  } 
       name = "24ème Division d'Infanterie"
       strength = 10 
       type = infantry 
	   model = 6
      }
     Division = 
     {  id       = {  type = 13500 id = 61  } 
       name     = "12ème Division d'Infanterie Motorisée" 
       strength = 70 
       type     = infantry 
       model    = 8 
       extra    = armored_car 
	   brigade_model = 3
      }
     Division = 
     {  id    = {  type = 13500 id = 62  } 
       name  = "62ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 63  } 
     name     = "XIIIème Corps d'Armée" 
     location = 71 
     Division = 
     {  id   = {  type = 13500 id = 64  } 
       name = "26ème Division d'Infanterie"
       strength = 10 
       type = infantry 
	   model = 6
      }
     Division = 
     {  id       = {  type = 13500 id = 65  } 
       name     = "25ème Division d'Infanterie Motorisée" 
       strength = 70 
       type     = infantry 
       model    = 8 
       extra    = armored_car 
	   brigade_model = 3
      }
     Division = 
     {  id    = {  type = 13500 id = 66  } 
       name  = "63ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 67  } 
     name     = "XIVème Corps d'Armée" 
     location = 85 
     Division = 
     {  id   = {  type = 13500 id = 68  } 
       name = "27ème Division d'Infanterie Alpine" 
       type = bergsjaeger 
	   model = 6
      } 
     Division = 
     {  id   = {  type = 13500 id = 69  } 
       name = "28ème Division d'Infanterie Alpine" 
       strength = 10
       type = bergsjaeger 
	   model = 5
      } 
     Division = 
     {  id   = {  type = 13500 id = 70  } 
       name = "64ème Division d'Infanterie Alpine" 
       strength = 5
       type = bergsjaeger 
	   model = 5
      } 
     Division = 
     {  id       = {  type = 13500 id = 71  } 
       name     = "1ère Division d'Infanterie Nord-Africaine" 
       type     = infantry 
	   model = 6
       extra    = light_armor_brigade 
	   brigade_model = 0
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 72  } 
     name     = "XVème Corps d'Armée" 
     location = 89 
     Division = 
     {  id   = {  type = 13500 id = 73  } 
       name = "29ème Division d'Infanterie Alpine" 
       type = bergsjaeger 
	   model = 6
      } 
     Division = 
     {  id   = {  type = 13500 id = 74  } 
       name = "30ème Division d'Infanterie Alpine" 
       strength = 10
       type = bergsjaeger 
	   model = 5
      } 
     Division = 
     {  id   = {  type = 13500 id = 75  } 
       name = "65ème Division d'Infanterie Alpine" 
       strength = 5
       type = bergsjaeger 
	   model = 5
      } 
     Division = 
     {  id       = {  type = 13500 id = 76  } 
       name     = "2ème Division d'Infanterie Coloniale" 
       type     = infantry 
	   model = 6
       extra    = light_armor_brigade 
	   brigade_model = 0
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 77  } 
     name     = "XVIème Corps d'Armée" 
     location = 82 
     Division = 
     {  id   = {  type = 13500 id = 78  } 
       name = "32ème Division d'Infanterie"
       strength = 10 
       type = infantry 
	   model = 6
      }
     Division = 
     {  id   = {  type = 13500 id = 79  } 
       name = "31ème Division d'Infanterie Alpine" 
       type = bergsjaeger 
	   model = 6
      } 
     Division = 
     {  id    = {  type = 13500 id = 80  } 
       name  = "66ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 81  } 
     name     = "XVIIème Corps d'Armée" 
     location = 77 
     Division = 
     {  id       = {  type = 13500 id = 82  } 
       name     = "4ème Division d'Infanterie Coloniale" 
       type     = infantry 
	   model = 6
      } 
     Division = 
     {  id    = {  type = 13500 id = 83  } 
       name  = "67ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 84  } 
     name     = "XVIIIème Corps d'Armée" 
     location = 68 
     Division = 
     {  id       = {  type = 13500 id = 85  } 
       name     = "1ère Division d'Infanterie Coloniale" 
       type     = infantry 
	   model = 6
      } 
     Division = 
     {  id   = {  type = 13500 id = 86  } 
       name = "36ème Division d'Infanterie"
       type = infantry 
	   model = 7
      }
     Division = 
     {  id   = {  type = 13500 id = 87  } 
       name = "35ème Division d'Infanterie"
       strength = 10 
       type = infantry 
	   model = 6
      }
    } 
   landunit = 
   {  id       = {  type = 13500 id = 88  } 
     name     = "XXème Corps d'Armée" 
     location = 106 
     Division = 
     {  id       = {  type = 13500 id = 89  } 
       name     = "QG Théâtre d'Opérations Nord-Est" 
       type     = hq 
       model    = 2
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 13500 id = 90  } 
       name     = "2ème Division de Cavalerie" 
       type     = cavalry 
       model    = 7 
       extra    = light_armor_brigade 
	   brigade_model = 1
      } 
     Division = 
     {  id       = {  type = 13500 id = 91  } 
       name     = "11ème Division d'Infanterie" 
       type     = infantry 
	   model = 7
       extra    = artillery 
	   brigade_model = 3
      } 
     Division = 
     {  id   = {  type = 13500 id = 92  } 
       name = "4ème Division d'Infanterie Nord-Africaine" 
       type = infantry 
	   model = 6
      } 
     Division = 
     {  id    = {  type = 13500 id = 93  } 
       name  = "70ème Division d'Infanterie"
       strength = 5 
       type  = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 94  } 
     name     = "Division d'Alger" 
     location = 727 
     Division = 
     {  id   = {  type = 13500 id = 95  } 
       name = "Division d'Alger" 
       type = infantry 
	   model = 6
       extra    = armored_car 
	   brigade_model = 2
      } 
    }
   landunit = 
   {  id       = {  type = 13500 id = 96  } 
     name     = "Division d'Oran" 
     location = 728 
     Division = 
     {  id   = {  type = 13500 id = 97  } 
       name = "Division d'Oran" 
       type = infantry 
	   model = 6
       extra    = armored_car 
	   brigade_model = 2
      }
    } 
   landunit = 
   {  id       = {  type = 13500 id = 98  } 
     name     = "Division de Constantine" 
     location = 734 
     Division = 
     {  id   = {  type = 13500 id = 99  } 
       name = "Division de Constantine" 
       type = infantry 
	   model = 6
       extra    = armored_car 
	   brigade_model = 2
      }
    } 
   landunit = 
   {  id       = {  type = 13500 id = 100  } 
     name     = "Division de Tunis" 
     location = 747 
     Division = 
     {  id   = {  type = 13500 id = 101  } 
       name = "Division de Tunis" 
       type = infantry 
	   model = 6
       extra    = armored_car 
	   brigade_model = 2
      }
    } 
   landunit = 
   {  id       = {  type = 13500 id = 102  } 
     name     = "Division de Sousse" 
     location = 745 
     Division = 
     {  id   = {  type = 13500 id = 103  } 
       name = "Division de Sousse" 
       type = garrison 
	   model = 2
      }
    } 
   landunit = 
   {  id       = {  type = 13500 id = 104  } 
     name     = "XIXème Région Militaire" 
     location = 727 
     Division = 
     {  id       = {  type = 13500 id = 105  } 
       name     = "81ème Division d'Infanterie d'Afrique" 
       strength = 5 
       type     = infantry 
	   model = 5
      } 
     Division = 
     {  id       = {  type = 13500 id = 106  } 
       name     = "82ème Division d'Infanterie d'Afrique" 
       strength = 5 
       type     = infantry 
	   model = 5
      } 
     Division = 
     {  id       = {  type = 13500 id = 107  } 
       name     = "83ème Division d'Infanterie d'Afrique" 
       strength = 5 
       type     = infantry 
	   model = 5
      } 
     Division = 
     {  id       = {  type = 13500 id = 108  } 
       name     = "84ème Division d'Infanterie d'Afrique" 
       strength = 5 
       type     = infantry 
	   model = 5
      } 
     Division = 
     {  id       = {  type = 13500 id = 109  } 
       name     = "85ème Division d'Infanterie d'Afrique" 
       strength = 5 
       type     = infantry 
	   model = 5
      } 
     Division = 
     {  id       = {  type = 13500 id = 110  } 
       name     = "86ème Division d'Infanterie d'Afrique" 
       strength = 5 
       type     = infantry 
	   model = 5
      } 
     Division = 
     {  id       = {  type = 13500 id = 111  } 
       name     = "87ème Division d'Infanterie d'Afrique" 
       strength = 5 
       type     = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 112  } 
     name     = "Commandement des troupes du Maroc" 
     location = 717 
     Division = 
     {  id       = {  type = 13500 id = 113  } 
       name     = "1ère Division Marocaine" 
       strength = 5 
       type     = infantry 
	   model = 5
      } 
     Division = 
     {  id       = {  type = 13500 id = 114  } 
       name     = "2ème Division Marocaine" 
       strength = 5 
       type     = infantry 
	   model = 5
      } 
     Division = 
     {  id       = {  type = 13500 id = 115  } 
       name     = "3ème Division Marocaine" 
       strength = 5 
       type     = infantry 
	   model = 5
      } 
    } 
   landunit = 
   {  id       = {  type = 13500 id = 116  } 
     name     = "Division de Fès" 
     location = 721 
     Division = 
     {  id   = {  type = 13500 id = 117  } 
       name = "Division de Fès" 
       type = garrison 
	   model = 2
      }
    } 
   landunit = 
   {  id       = {  type = 13500 id = 318  } 
     name     = "Division de Marrakech" 
     location = 722 
     Division = 
     {  id   = {  type = 13500 id = 319  } 
       name = "Division de Marrakech" 
       type = garrison 
	   model = 2
      }
    } 
   landunit = 
   {  id       = {  type = 13500 id = 320  } 
     name     = "Division de Meknès" 
     location = 717 
     Division = 
     {  id   = {  type = 13500 id = 321  } 
       name = "Division de Meknès" 
       type = garrison 
	   model = 2
      }
    } 
   landunit = 
   {  id       = {  type = 13500 id = 322  } 
     name     = "Subdivision de Casablanca" 
     location = 718 
     Division = 
     {  id   = {  type = 13500 id = 323  } 
       name = "Subdivision de Casablanca" 
       type = militia 
	   model = 3
      }
     Division = 
     {  id   = {  type = 13500 id = 324  } 
       name = "Goumiers" 
       type = militia 
	   model = 3
      }
    } 
   landunit = 
   {  id       = {  type = 13500 id = 325  } 
     name     = "Troupes d'Afrique occidentale" 
     location = 978 
     Division = 
     {  id   = {  type = 13500 id = 326  } 
       name = "Point d'appui de la flotte de Dakar" 
       type = garrison 
	   model = 2
       strength = 20
      }
    } 
   landunit = 
   {  id       = {  type = 13500 id = 327  } 
     name     = "1ère Brigade de Tirailleurs Sénégalais" 
     location = 983 
     Division = 
     {  id       = {  type = 13500 id = 328  } 
       name     = "1ère Brigade de Tirailleurs Sénégalais" 
       type     = militia 
       model    = 3 
      } 
    }
   landunit = 
   {  id       = {  type = 13500 id = 329  } 
     name     = "2ème Brigade de Tirailleurs Sénégalais" 
     location = 976 
     Division = 
     {  id       = {  type = 13500 id = 330  } 
       name     = "2ème Brigade de Tirailleurs Sénégalais" 
       type     = militia 
       model    = 3 
      } 
    }
   landunit = 
   {  id       = {  type = 13500 id = 331  } 
     name     = "3ème Brigade de Tirailleurs Sénégalais" 
     location = 962 
     Division = 
     {  id       = {  type = 13500 id = 332  } 
       name     = "3ème Brigade de Tirailleurs Sénégalais" 
       type     = militia 
       model    = 3 
      } 
    }
   landunit = 
   {  id       = {  type = 13500 id = 333  } 
     name     = "Troupes d'Afrique équatoriale" 
     location = 920 
     Division = 
     {  id       = {  type = 13500 id = 334  } 
       name     = "Tirailleurs du Tchad" 
       type     = militia 
       model    = 3 
      } 
    }
   landunit = 
   {  id       = {  type = 13500 id = 335  } 
     name     = "Troupes d'Afrique orientale" 
     location = 1001 
     Division = 
     {  id       = {  type = 13500 id = 336  } 
       name     = "Tirailleurs Malgaches" 
       type     = militia 
       model    = 3 
      } 
    }
	# ############
	# French Navy
	# ############
	navalunit = { 
		id = { type = 13500 id = 118 } 
		name = "1ère Flotte" 
		location = 37 
		base = 37 
		division = { 
			id = { type = 13500 id = 119 } 
			name = "Béarn" 
			type = escort_carrier 
			model = 2 
			} 
		division = { 
			id = { type = 13500 id = 120 } 
			name = "1ère Flottille de Contre-Torpilleurs" 
			type = destroyer 
			model = 5
			} 
		division = { 
			id = { type = 13500 id = 121 } 
			name = "Lorraine" 
			type = battleship 
			model = 3 
			extra1 = naval_anti_air_l
			extra2 = floatplane
			brigade_model2 = 4
			} 
		division = { 
			id = { type = 13500 id = 122 } 
			name = "Provence" 
			type = battleship 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 123 } 
			name = "Colbert" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 13500 id = 124 } 
			name = "Dupleix" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 13500 id = 125 } 
			name = "Emile Bertin" 
			type = light_cruiser 
			model = 4 
			} 
		division = { 
			id = { type = 13500 id = 128 } 
			name = "Algérie" 
			type = heavy_cruiser 
			model = 4 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 13500 id = 126 } 
			name = "Primauguet" 
			type = light_cruiser 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 127 } 
			name = "Duguay-Trouin" 
			type = light_cruiser 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 129 } 
			name = "Lamotte-Picquet" 
			type = light_cruiser 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 131 } 
			name = "La Galissonnière" 
			type = light_cruiser 
			model = 4 
			} 
		} 
	navalunit = { 
		id = { type = 13500 id = 130 } 
		name = "2ème Flotte" 
		location = 86 
		base = 86 
		division = { 
			id = { type = 13500 id = 132 } 
			name = "Courbet" 
			type = battleship 
			model = 2 
			} 
		division = { 
			id = { type = 13500 id = 133 } 
			name = "Paris" 
			type = battleship 
			model = 2 
			} 
		division = { 
			id = { type = 13500 id = 134 } 
			name = "Suffren" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 13500 id = 135 } 
			name = "Duquesne" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 13500 id = 136 } 
			name = "Pluton" 
			type = light_cruiser 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 137 } 
			name = "Jeanne d'Arc" 
			type = light_cruiser 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 139 } 
			name = "2ème Flottille de Contre-Torpilleurs" 
			type = destroyer
			model = 5
			} 
		division = { 
			id = { type = 13500 id = 138 } 
			name = "3ème Flottille de Contre-Torpilleurs" 
			type = destroyer 
			model = 4
			} 
		} 

	navalunit = { 
		id = { type = 13500 id = 140 } 
		name = "3ème Flotte" 
		location = 728 
		base = 728 

# Removing Ocean... this ship was disarmed and hulked in 1936, used as 
# a harbor training ship.
#		division = { 
#			id = { type = 13500 id = 141 } 
#			name = "Océan" 
#			type = battleship 
#			model = 2 
#			} 

		division = { 
			id = { type = 13500 id = 142 } 
			name = "Bretagne" 
			type = battleship 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 143 } 
			name = "Foch" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = {
			id = { type = 13500 id = 307 }
			name = "Commandant Teste"
			type = escort_carrier
			model = 0
			extra1 = naval_anti_air_l
			brigade_model1 = 0
			}
		division = { 
			id = { type = 13500 id = 144 } 
			name = "Tourville" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 13500 id = 145 } 
			name = "4ème Flottille de Contre-Torpilleurs" 
			type = destroyer 
			model = 4
			} 
		division = { 
			id = { type = 13500 id = 146 } 
			name = "5ème Flottille de Contre-Torpilleurs" 
			type = destroyer 
			model = 4 
			} 
		division = { 
			id = { type = 13500 id = 147 } 
			name = "6ème Flottille de Contre-Torpilleurs" 
			type = destroyer 
			model = 4 
			} 
		division = { 
			id = { type = 13500 id = 148 } 
			name = "7ème Flottille de Contre-Torpilleurs" 
			type = destroyer 
			model = 4 
			} 
		} 
	navalunit = { 
		id = { type = 13500 id = 149 } 
		name = "1ère Flotte de Sous-marins" 
		location = 86 
		base = 86 
		division = { 
			id = { type = 13500 id = 150 } 
			name = "1ère Flottille de Sous-Marins" 
			type = submarine 
			model = 3
			} 
		division = { 
			id = { type = 13500 id = 151 } 
			name = "2ème Flottille de Sous-Marins" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 152 } 
			name = "3ème Flottille de Sous-Marins" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 153 } 
			name = "4ème Flottille de Sous-Marins" 
			type = submarine 
			model = 3
			} 
		} 
	navalunit = { 
		id = { type = 13500 id = 155 } 
		name = "2ème Flotte de Sous-marins" 
		location = 86 
		base = 86 
		division = { 
			id = { type = 13500 id = 154 } 
			name = "5ème Flottille de Sous-Marins" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 156 } 
			name = "6ème Flottille de Sous-Marins" 
			type = submarine 
			model = 3
			} 
		division = { 
			id = { type = 13500 id = 157 } 
			name = "7ème Flottille de Sous-Marins" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 158 } 
			name = "8ème Flottille de Sous-Marins" 
			type = submarine 
			model = 3 
			} 
		} 
	navalunit = { 
		id = { type = 13500 id = 161 } 
		name = "3ème Flotte de Sous-marins" 
		location = 727 
		base = 727 
		division = { 
			id = { type = 13500 id = 159 } 
			name = "9ème Flottille de Sous-Marins" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 160 } 
			name = "10ème Flottille de Sous-Marins" 
			type = submarine 
			model = 2
			} 
		division = { 
			id = { type = 13500 id = 162 } 
			name = "11ème Flottille de Sous-Marins" 
			type = submarine 
			model = 2 
			} 
		} 
	navalunit = { 
		id = { type = 13500 id = 167 } 
		name = "Transport Expéditionnaire" 
		location = 86 
		base = 86 
		division = { 
			id = { type = 13500 id = 168 } 
			name = "1ère Flottille de Convoi" 
			type = transport 
			model = 1 
			} 
		division = { 
			id = { type = 13500 id = 169 } 
			name = "2ème Flottille de Convoi" 
			type = transport 
			model = 1 
			} 
		division = { 
			id = { type = 13500 id = 170 } 
			name = "3ème Flottille de Convoi" 
			type = transport 
			model = 1 
			} 
		division = { 
			id = { type = 13500 id = 171 } 
			name = "8ème Flottille de Contre-torpilleurs" 
			type = destroyer 
			model = 4
			} 
		division = { 
			id = { type = 13500 id = 172 } 
			name = "9ème Flottille de Contre-torpilleurs" 
			type = destroyer 
			model = 4
			} 
		division = { 
			id = { type = 13500 id = 173 } 
			name = "10ème Flottille de Contre-torpilleurs" 
			type = destroyer 
			model = 4
			} 
		} 
	navalunit = { 
		id = { type = 13500 id = 174 } 
		name = "Transport Général" 
		location = 86 
		base = 86 
		division = { 
			id = { type = 13500 id = 175 } 
			name = "4ème Flottille de Convoi" 
			type = transport 
			model = 1 
			} 
		division = { 
			id = { type = 13500 id = 176 } 
			name = "7ème Flottille de Convoi" 
			type = transport 
			model = 1 
			} 
		division = { 
			id = { type = 13500 id = 177 } 
			name = "11ème Flottille de Contre-Torpilleurs" 
			type = destroyer 
			model = 4
			} 
		division = { 
			id = { type = 13500 id = 178 } 
			name = "12ème Flottille de Contre-torpilleurs" 
			type = destroyer 
			model = 4
			} 
		}      
	navalunit = { 
		id = { type = 13500 id = 179 } 
		name = "1ère Flotte de la France" 
		location = 86 
		base = 86 
		division = { 
			id = { type = 13500 id = 180 } 
			name = "13ème Flottille de Contre-torpilleurs" 
			type = destroyer 
			model = 2
			} 
		division = { 
			id = { type = 13500 id = 181 } 
			name = "14ème Flottille de Contre-torpilleurs" 
			type = destroyer 
			model = 0
			} 
		division = { 
			id = { type = 13500 id = 182 } 
			name = "6ème Flottille de Convoi" 
			type = transport 
			model = 1 
			} 
		division = { 
			id = { type = 13500 id = 183 } 
			name = "5ème Flottille de Convoi" 
			type = transport 
			model = 1 
			} 
		} 
	navalunit = { 
		id = { type = 13500 id = 184 } 
		name = "2e Flotte de la France" 
		location = 37 
		base = 37 
		division = { 
			id = { type = 13500 id = 185 } 
			name = "15ème Flottille de Contre-Torpilleurs" 
			type = destroyer 
			model = 0
			} 
		division = { 
			id = { type = 13500 id = 286 } 
			name = "16ème Flottille de Contre-Torpilleurs" 
			type = destroyer 
			model = 0
			} 
		} 
	# ###############
	# French Airforce
	# ###############
   airunit = 
   {  id       = {  type = 13500 id = 188  } 
     name     = "1ère Groupe de Bombardement" 
     location = 55 
     base     = 55 
     Division = 
     {  id       = {  type = 13500 id = 189  } 
       name     = "Groupe de Bombardement Tactique 1" 
       strength = 100 
       type     = tactical_bomber 
	   model = 4
      } 
     Division = 
     {  id       = {  type = 13500 id = 190  } 
       name     = "Groupe de Bombardement Tactique 2" 
       strength = 100 
       type     = tactical_bomber 
	   model = 4
      } 
     Division = 
     {  id       = {  type = 13500 id = 191  } 
       name     = "Groupe de Bombardement Tactique 3" 
       strength = 100 
       type     = tactical_bomber 
	   model = 4
      } 
    } 
   airunit = 
   {  location = 728 
     base     = 728 
     id       = {  type = 13500 id = 192  } 
     name     = "4ème Groupe de Bombardement" 
     Division = 
     {  id       = {  type = 13500 id = 293  } 
       name     = "Groupe de Bombardement Tactique 6" 
       strength = 100 
       type     = tactical_bomber 
	   model = 4
      } 
    } 
   airunit = 
   {  location = 89 
     base     = 89 
     id       = {  type = 13500 id = 294  } 
     name     = "5ème Groupe de Bombardement" 
     Division = 
     {  id       = {  type = 13500 id = 295  } 
       name     = "Groupe de Bombardement Tactique 7" 
       strength = 100 
       type     = tactical_bomber 
	   model = 4
      } 
    } 
   airunit = 
   {  location = 55 
     base     = 55 
     id       = {  type = 13500 id = 196  } 
     name     = "1er Groupe de Chasse" 
     Division = 
     {  id       = {  type = 13500 id = 197  } 
       name     = "Groupe de Chasse 24" 
       strength = 100 
       type     = interceptor 
       model    = 7
      } 
     Division = 
     {  id       = {  type = 13500 id = 198  } 
       name     = "Groupe de Chasse 21" 
       strength = 100 
       type     = interceptor 
       model    = 6 
      } 
    } 
   airunit = 
   {  location = 89 
     base     = 89 
     id       = {  type = 13500 id = 199  } 
     name     = "3ème Groupe de Chasse" 
     Division = 
     {  id       = {  type = 13500 id = 200  } 
       name     = "Groupe de Chasse 23" 
       strength = 100 
       type     = interceptor 
	   model = 7
      } 
    } 
   # ################################# 
   # Naval units under construction 
   # ################################# 
   division_development = 
   {  name  = "Dunkerque" 
     type  = battlecruiser 
     model = 3
     new_model = no
     cost  = 0.4 
     id    = {  type = 13500 id = 300  } 
     date  = {  year = 1937 month = may day = 1  } 
    }
   division_development = 
   {  name  = "Strasbourg" 
     type  = battlecruiser 
     model = 3
     new_model = no
     cost  = 0.4 
     id    = {  type = 13500 id = 301  } 
     date  = {  year = 1939 month = april day = 6  } 
    }
   division_development = 
   {  name  = "George Leygues" 
     type  = light_cruiser 
     model = 4
     new_model = no
     cost  = 0.4 
     id    = {  type = 13500 id = 302  } 
     date  = {  year = 1937 month = november day = 15  } 
    }
   division_development = 
   {  name  = "Gloire" 
     type  = light_cruiser 
     model = 4
     new_model = no
     cost  = 0.4 
     id    = {  type = 13500 id = 303  } 
     date  = {  year = 1937 month = november day = 15  } 
    }
   division_development = 
   {  name  = "Marsellaise" 
     type  = light_cruiser 
     model = 4
     new_model = no
     cost  = 0.4 
     id    = {  type = 13500 id = 304  } 
     date  = {  year = 1937 month = october day = 10  } 
    }
   division_development = 
   {  name  = "Jean de Vienne" 
     type  = light_cruiser 
     model = 4
     new_model = no
     cost  = 0.4 
     id    = {  type = 13500 id = 305  } 
     date  = {  year = 1937 month = february day = 10  } 
    }
   division_development = 
   {  name  = "Montcalm" 
     type  = light_cruiser 
     model = 4
     new_model = no
     cost  = 0.4 
     id    = {  type = 13500 id = 306  } 
     date  = {  year = 1937 month = november day = 15  } 
    }

	division_development = {
		type = submarine
		model = 4
		cost = 0.1
		id = { type = 13500 id = 308 }
		date = { year = 1936 month = may day = 1 }
	}
	division_development = {
		type = submarine
		model = 4
		cost = 0.1
		id = { type = 13500 id = 309 }
		date = { year = 1936 month = may day = 1 }
	}
	
	division_development = {
		type = destroyer
		model = 5
		name = "17ème Flottille de Contre-Torpilleurs"
		cost = 0.2
		id = { type = 13500 id = 310 }
		date = { year = 1936 month = april day = 15 }
	}
	division_development = {
		type = destroyer
		model = 5
		name = "18ème Flottille de Contre-Torpilleurs"
		cost = 0.2
		id = { type = 13500 id = 311 }
		date = { year = 1936 month = may day = 20 }
	}
	division_development = {
		type = destroyer
		model = 5
		name = "19ème Flottille de Contre-Torpilleurs"
		cost = 0.2
		id = { type = 13500 id = 312 }
		date = { year = 1936 month = june day = 24 }
	}
	division_development = {
		type = destroyer
		model = 5
		name = "20ème Flottille de Contre-Torpilleurs"
		cost = 0.2
		id = { type = 13500 id = 313 }
		date = { year = 1936 month = july day = 10 }
	}

} 
 
