 
 ############################## 
 # Country definition for GER # 
 ############################## 

 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = GER 
    flag_ext               = _nazi
   
	capital                = 163 
	manpower               = 124.5
	transports             = 450 
	escorts                = 23 
	#ground_def_eff         = 0.82 
	# Resource Reserves 
	energy                 = 9000
	metal                  = 4500
	rare_materials         = 2250
	oil                    = 1000 
	supplies               = 500 
	money                  = 70 
	research_mod = 0.75
	peacetime_ic_mod       = 0.9
   diplomacy = 
   {  relation = {  tag = ARG value = 75  } 
     relation = {  tag = AST value = 1  } 
     relation = 
     {  tag        = AUS 
       value      = 100 
       #guaranteed = {  day = 30 month = december year = 1932  } 
      } 
     relation = {  tag = BEL value = 20  } 
     relation = {  tag = BHU value = 1  } 
     relation = {  tag = BOL value = 15  } 
     relation = {  tag = BRA value = 50  } 
     relation = 
     {  tag        = BUL 
       value      = 25 
       guaranteed = {  day = 30 month = december year = 1935  } 
      } 
     relation = {  tag = CAN value = 1  } 
     relation = {  tag = CHL value = 50  } 
     relation = {  tag = COL value = -20  } 
     relation = 
     {  tag        = CZE 
       value      = -25 
       guaranteed = {  day = 30 month = december year = 1932  } 
      } 
     relation = {  tag = ENG value = 150  } 
     relation = 
     {  tag        = DEN 
       value      = 25 
       guaranteed = {  day = 30 month = december year = 1932  } 
      } 
     relation = {  tag = EST value = 10  } 
     relation = 
     {  tag        = FIN 
       value      = 25 
       guaranteed = {  day = 22 month = august year = 1934  } 
      } 
     relation = {  tag = FRA value = -35  } 
     relation = {  tag = GRE value = 15  } 
     relation = {  tag = HOL value = 100  } 
     relation = {  tag = HUN value = 100  } 
     relation = {  tag = IRE value = 15  } 
     relation = {  tag = IRQ value = 25  } 
     relation = 
     {  tag        = ITA 
       value      = -50#50 
       guaranteed = {  day = 30 month = december year = 1935  } 
      } 
     relation = {  tag = JAP value = 20  } 
     relation = {  tag = LAT value = 10  } 
     relation = {  tag = LIT value = -50  } 
     relation = {  tag = LUX value = -50  } 
     relation = {  tag = MAN value = 20  } 
     relation = {  tag = NEP value = 1  } 
     relation = {  tag = NZL value = 1  } 
     relation = {  tag = OMN value = 1  } 
     relation = 
     {  tag        = POL 
       value      = -10 
       guaranteed = {  day = 30 month = december year = 1932  } 
      } 
     relation = {  tag = POR value = 75  } 
     relation = 
     {  tag        = ROM 
       value      = 50 
       guaranteed = {  day = 30 month = december year = 1935  } 
      } 
     relation = {  tag = SAF value = 1  } 
     relation = 
     {  tag        = SCH 
       value      = 50 
       guaranteed = {  day = 16 month = may year = 1935  } 
      } 
     relation = {  tag = SOV value = 1  } 
     relation = {  tag = SPR value = -50  } 
     relation = 
     {  tag        = SWE 
       value      = 50 
       guaranteed = {  day = 30 month = december year = 1935  } 
      } 
     relation = 
     {  tag        = TUR 
       value      = 100 
       guaranteed = {  day = 30 month = december year = 1935  } 
      } 
     relation = {  tag = USA value = -10  } 
     relation = {  tag = YEM value = 1  } 
     relation = 
     {  tag        = YUG 
       value      = 50 
       guaranteed = {  day = 30 month = december year = 1932  } 
      } 
    } 
   SpyInfo                = {  country = "GER" NumberOfSpies = 7  } 
   
claimedprovinces = {
#Czech
	203
	201
	196
	198
	202
	207
	199

#Slovenia
	346
	349

#North Italy
	393
	394
	395
	400
	404
	405
	407
	
	403
	401

#Netherlands
	125 #Rotterdam
	122 #Amsterdam
	123 #Middelburg=>Rotterdam(split)
	118 #Eindhoven
	119 #Arnheim=>Utrecht/Arnheim(merge)
	124 #Groningen=>Groningen/Leeuwarden(merge)
	120 #Nijmegen=>Eindhoven(split)
	121 #Maastricht=>Eindhoven(split)

#Belgium
	108
	111
	112
	113
	114
	115
	116
	117

#France
	#51
	52
	96
	106
	97
	98
	88

#Swiss
	391
	390

#US
	1791
	1792
	1800
	1801
	1804
	1803
	1802
	1806
	1808
	1798
	1824
	1825
	1821
	1822
	1845
	1844
	1842
	1826
	1832
	1837
	1847
	1854
	1831
	1830
	1829
	1839
	1841
	1843
	1840
	1848
	1850
	1849
	1835
	1834
	1838
	1846
	1857
	1855
	1852
	1853
	1859
	1908
	1914
	1860
	1858
	1856
	1851
	1867
	1864
	1861
	1862
	1863
	1865
	1866
	1868
	1872
	1873
	1874
	1875
	1877

#Canada
	2106
	2101
	2104
	2100
}
   
   nationalprovinces = {  
#Ostpreußen
   182 #Tilsit#
   183 #Elbing#
   184 #Königsberg#
   185 #Allenstein#
#Reich   
   126 #Aachen#
   129 #Koblenz#
   131 #Köln#
   128 #Trier#
   127 #Saarbrücken#
   130 #Mainz#
   143 #Neuwied#
   142 #Duesseldorf#
   145 #Essen#
   141 #Muenster#
   147 #Wilhelmshaven#
   144 #Bielefeld#
   137 #Kassel#
   138 #Frankfurt/Main#
   139 #Darmstadt#
   136 #Karlsruhe#
   132 #Freiburg#
   133 #Konstanz#
   135 #Tubingen#
   134 #Stuttgart#
   180 #Würzburg#
   140 #Fulda#
   148 #Bremen#
   150 #Flensburg#
   151 #Lübeck#
   152 #Kiel#
   154 #Hamburg#
   149 #Lüneburg#
   146 #Hannover#
   171 #Erfurt#
   177 #Nürnberg#
   178 #Augsburg#
   176 #Landshut#
   179 #München#
   175 #Regensburg#
   174 #Bayreuth#
   169 #Magdeburg#
   153 #Rostock#
   156 #Neuruppin#
   157 #Potsdam#
   163 #Berlin#
   170 #Leipzig#
   173 #Dresden#
   172 #Cottbus#
   160 #Frankfurt/Oder#
   162 #Stralsund#
   #Posen,Schlesien,Westpreußen
   158 #Stettin#
   159 #Meseritz#
   165 #Liegnitz#
   166 #Waldenburg#
   167 #Breslau#
   168 #Gleiwitz#
   164 #Oppeln#
   155 #Stolpe#
   161 #Deutsch-Krone#
   #Elsaß-Lothringen  
   104 #Metz
   107 #Strasbourg
   105 #Colmar
   #Luxembourg
   109 #Luxembourg#
   #Schleswig 
   216 #Abenra
   #Danzig
   181 #Danzig
   #Memel
   261 #Klaipeda
   #Westpreußen
   225 #Bydgoszcz
   224 #Poznan
   #Schweiz
   392 #Bern
   389 #Zürich
   #Polen/Schlesien
   221 #Katowice
   #Eupen-Malmedy
   110 #Eupen
   #Austria 
   189 #Innsbruck
   191 #Klagenfurt
   192 #Salzburg
   190 #Graz
   195 #Wien
   194 #Hollabrun
   186 #Freistadt
   187 #Linz
   193 #Sankt Poelten
   188 #Eisenstadt

   #Poland 
   226 #Gdynia
#   230 #Plock
   222 #Torun

#Sudetenland
	206
	200
	205
	204
	197

#Italy
	402

#Austria-Hungary
	277
	336
	291
	285

#Russia
	666

#Baltic
	268
	269
   } 
   ownedprovinces = { 
   #Ostpreußen
   182 #Tilsit
   183 #Elbing
   184 #Königsberg
   185 #Allenstein
   #Reich   
   126 #Aachen
   129 #Koblenz
   131 #Köln
   128 #Trier
   127 #Saarbrücken
   130 #Mainz
   143 #Neuwied
   142 #Düsseldorf
   145 #Essen
   141 #Münster
   147 #Wilhelmshaven
   144 #Bielefeld
   137 #Kassel
   138 #Frankfurt/Main
   139 #Darmstadt
   136 #Karlsruhe
   132 #Freiburg
   133 #Konstanz
   135 #Tübingen
   134 #Stuttgart
   180 #Würzburg
   140 #Fulda
   148 #Bremen
   150 #Flensburg
   151 #Lübeck
   152 #Kiel
   154 #Hamburg
   149 #Lüneburg
   146 #Hannover
   171 #Erfurt
   177 #Nürnberg
   178 #Augsburg
   176 #Landshut
   179 #München
   175 #Regensburg
   174 #Bayreuth
   169 #Magdeburg
   153 #Rostock
   156 #Neuruppin
   157 #Potsdam
   163 #Berlin
   170 #Leipzig
   173 #Dresden
   172 #Cottbus
   160 #Frankfurt/Oder
   162 #Stralsund
   #Posen,Schlesien,Westpreußen
   158 #Stettin
   159 #Meseritz
   165 #Liegnitz
   166 #Waldenburg
   167 #Breslau
   168 #Gleiwitz
   164 #Oppeln
   155 #Stolpe
   161 #Deutsch-Krone
   } 
   controlledprovinces = {
   #Ostpreußen
   182 #Tilsit
   183 #Elbing
   184 #Königsberg
   185 #Allenstein
   #Reich   
   126 #Aachen
   129 #Koblenz
   131 #Köln
   128 #Trier
   127 #Saarbrücken
   130 #Mainz
   143 #Neuwied
   142 #Düsseldorf
   145 #Essen
   141 #Münster
   147 #Wilhelmshaven
   144 #Bielefeld
   137 #Kassel
   138 #Frankfurt/Main
   139 #Darmstadt
   136 #Karlsruhe
   132 #Freiburg
   133 #Konstanz
   135 #Tübingen
   134 #Stuttgart
   180 #Würzburg
   140 #Fulda
   148 #Bremen
   150 #Flensburg
   151 #Lübeck
   152 #Kiel
   154 #Hamburg
   149 #Lüneburg
   146 #Hannover
   171 #Erfurt
   177 #Nürnberg
   178 #Augsburg
   176 #Landshut
   179 #München
   175 #Regensburg
   174 #Bayreuth
   169 #Magdeburg
   153 #Rostock
   156 #Neuruppin
   157 #Potsdam
   163 #Berlin
   170 #Leipzig
   173 #Dresden
   172 #Cottbus
   160 #Frankfurt/Oder
   162 #Stralsund
   #Posen,Schlesien,Westpreußen
   158 #Stettin
   159 #Meseritz
   165 #Liegnitz
   166 #Waldenburg
   167 #Breslau
   168 #Gleiwitz
   164 #Oppeln
   155 #Stolpe
   161 #Deutsch-Krone
   } 

   # Germany 1936 techs 
   # ###################### 
   techapps = {
 
#Early Infantry Division  
1010 1020 1030 1040 1050 1060 1070 1080 1090
#SEMI-MOTORIZED CAVALRY 
13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 1380 
# Motorized Infantry
1396
#Early Mountain Division 
1160  1170 1180 1190 1200 1210 1220 1230 1240
#Engineers
1830 1840 1850 1860
#Interbellum 1930 Supply
1910 1920 1930 1940 1950 1960 1970 1980

#Basic Armoured Car  
2860 2870 2880 2020 2150
#Early Tank 
7600 7610 2620 2010 2630 2640 2646 2650 2030
#Early Field Artillery 
2290 2300 2310 2900 2910 2920 2930
#Early Static Anti-Air Artillery 
2800 2450 21180 21190 21200
#Basic Anti-Air Artillery Brigade 
2810 2820 2510

#Improved Destroyer 
3010 3020 3030 3040 3050 3060
#Basic Light Cruiser 
3110 3120 3130 3140 3150 3160
#Improved Heavy Cruiser 
3210 3220 3230 3240 3250 3260  
#Early Battlecruiser
3310 3320 3330 3340
#Early Battleship 
3410 3420 3430 3440 3450 3456 3460 3470
#Improved Submarine 
3610 3620 3630 3640 3650
#Great War Air Carrier 
3510
#CAG
4900
#Improved Light carrier 
12100 12110
#Torpedo & ASW 18
3720 3730 3736 3740 3750 3900
#Troopships
3810 3820

#Basic Air Transport 
4290 4250
#Multirole fighter
4300 4310 4320 4330 4340
#CAS
4400
#ww1 strategic bomber
4800 4810 4820
#ww1 navalbomber
4700 4710
#Early Fighter  
4500 4510 4520 4530 4540 4550 4010 4020
#Early Bomber
4600 4610 4620 4630 4120 4130
#SEAPLANES
4740 4750 4760

#Manufacturing
5810 5820 5050 5830 5060
#Improved Construction Engineering 
5800 5080 5090
#Basic Oil Refining
5190 5200
#Computers & cryptografi
5310 54010 54020 54030 5316 5326
#Faculty of Atomic Research
5470 5480 
#Exp. Rocket
5560
#Mechanized Agriculture 
5700 5710 5010 5020
#Medicine
5600 5610 5620 5630

# Great War Land Doctrines (central powers)
6500 6510 6530 6550 6590 6600 6610 6620 6650 6670 6680 6690 6700 6710 6910
# WW2 Land Doctrines
6210 6220 6230 6250 6900
#Great War Hospital System 
14000 14010 14020

#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 9040 9050 9090

#Naval Doctrines
8010 8020 8030 8040 8050 8060 8070 8080
# Amphib
82300
# Naval Logistics
82500
# Naval Interdiction
8500 8510 8520 8550 8560 8570
# Trade Interdiction Submarine
8600 8610
# Indirect Approach
81300 81310 81320 81330 81340 81350
# Naval Supremacy
8100 8110 8120 8150 8160 8170 8200 8210
} 
inventions = { 3000027 3000028 }
blueprints = { 6240 6260 6270 } # Elastic Defense, Combined Arms Off. and Kampfgruppe doctrines
   ai_settings = { flags = {   legitIndie = 1 } }   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 1 
     political_left    = 1 
     free_market       = 5 
     freedom           = 2 
     professional_army = 4 
     defense_lobby     = 6 
     interventionism   = 6
    } 
   headofstate            = {  type = 9 id = 1  } 
   headofgovernment       = {  type = 9 id = 2  } 
   foreignminister        = {  type = 9 id = 3  } 
   armamentminister       = {  type = 9 id = 4  } 
   ministerofsecurity     = {  type = 9 id = 5  } 
   ministerofintelligence = {  type = 9 id = 6  } 
   chiefofstaff           = {  type = 9 id = 7  } 
   chiefofarmy            = {  type = 9 id = 8  } 
   chiefofnavy            = {  type = 9 id = 9  } 
   chiefofair             = {  type = 9 id = 10  } 
   dormant_leaders        = {  36 44 54 66 67 223 226 292 352 473 479 526
							   542 543 544 546 547 549 550 551 553 558 559 560 561 562 563 
							   567 571 572 573 578 595 686 712 746 749 816 821 909 983 992
							}
							
   landunit = 
   {  location = 184 
     name     = "I. Armeekorps" 
     id       = {  type = 14500 id = 34  } 
     Division = 
     {  id       = {  type = 14500 id = 35  } 
       name     = "1. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id            = {  type = 14500 id = 36  } 
       name          = "11. Infanterie-Division" 
       type          = infantry 
       model         = 8
       extra         = artillery 
       brigade_model = 6
       strength      = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 37  } 
       name     = "21. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1001  } 
       name     = "61. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1002  } 
       name     = "206. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1003  } 
       name     = "217. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1004  } 
       name     = "228. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   landunit = 
   {  location = 158 
     name     = "II. Armeekorps" 
     id       = {  type = 14500 id = 38  } 
     Division = 
     {  id       = {  type = 14500 id = 39  } 
       name     = "75. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 40  } 
       name     = "207. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 41  } 
       name     = "12. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
       extra    = artillery 
	   brigade_model = 6
      } 
     Division = 
     {  id       = {  type = 14500 id = 1005  } 
       name     = "258. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   landunit = 
   {  location = 163 
     name     = "III. Armeekorps" 
     id       = {  type = 14500 id = 42  } 
     Division = 
     {  id       = {  type = 14500 id = 1706  } 
       name     = "Oberkommando des Heeres" 
       type     = hq 
       model    = 2 
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 14500 id = 43  } 
       name     = "3. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 44  } 
       name     = "23. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
       extra    = engineer
	   brigade_model = 3	
      } 
     Division = 
     {  id       = {  type = 14500 id = 1006  } 
       name     = "50. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1007  } 
       name     = "68. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1008  } 
       name     = "76. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1009  } 
       name     = "208. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1010  } 
       name     = "218. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1011  } 
       name     = "257. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1012  } 
       name     = "93. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   landunit = 
   {  location = 167 
     name     = "VIII. Armeekorps" 
     id       = {  type = 14500 id = 45  } 
     Division = 
     {  id       = {  type = 14500 id = 46  } 
       name     = "8. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 47  } 
       name     = "62. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 48  } 
       name     = "18. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
       extra    = engineer
	   brigade_model = 3	   
      } 
     Division = 
     {  id       = {  type = 14500 id = 1013  } 
       name     = "213. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1014  } 
       name     = "221. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1015  } 
       name     = "252. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   landunit = 
   {  location = 134 
     name     = "V. Armeekorps" 
     id       = {  type = 14500 id = 49  } 
     Division = 
     {  id       = {  type = 14500 id = 50  } 
       name     = "78. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id            = {  type = 14500 id = 51  } 
       name          = "5. Infanterie-Division" 
       type          = infantry 
       model         = 8
       strength      = 90 
       extra         = artillery 
       brigade_model = 7
      } 
     Division = 
     {  id       = {  type = 14500 id = 52  } 
       name     = "260. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   landunit = 
   {  location = 141 
     name     = "VI. Armeekorps" 
     id       = {  type = 14500 id = 53  } 
     Division = 
     {  id       = {  type = 14500 id = 54  } 
       name     = "6. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 55  } 
       name     = "16. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
       extra    = artillery 
	   brigade_model = 5
      } 
     Division = 
     {  id       = {  type = 14500 id = 56  } 
       name     = "69. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1016  } 
       name     = "86. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1017  } 
       name     = "211. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1018  } 
       name     = "227. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1019  } 
       name     = "253. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1020  } 
       name     = "254. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   landunit = 
   {  location = 137 
     name     = "IX. Armeekorps" 
     id       = {  type = 14500 id = 57  } 
     Division = 
     {  id       = {  type = 14500 id = 58  } 
       name     = "9. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 59  } 
       name     = "15. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
       extra    = anti_air 
	   brigade_model = 2
      } 
     Division = 
     {  id       = {  type = 14500 id = 60  } 
       name     = "52. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1021  } 
       name     = "214. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1022  } 
       name     = "239. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1023  } 
       name     = "251. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1024  } 
       name     = "95. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   landunit = 
   {  location = 140 
     name     = "XII. Armeekorps" 
     id       = {  type = 14500 id = 61  } 
     Division = 
     {  id       = {  type = 14500 id = 62  } 
       name     = "79. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 63  } 
       name     = "246. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 64  } 
       name     = "262. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1025  } 
       name     = "263. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   landunit = 
   {  location = 173 
     name     = "IV. Armeekorps" 
     id       = {  type = 14500 id = 65  } 
     Division = 
     {  id       = {  type = 14500 id = 66  } 
       name     = "4. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
     Division = 
     {  id            = {  type = 14500 id = 67  } 
       name          = "14. Infanterie-Division" 
       type          = infantry 
       model         = 8 
       strength      = 90 
       extra         = artillery 
       brigade_model = 6
      } 
     Division = 
     {  id       = {  type = 14500 id = 68  } 
       name     = "24. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1026  } 
       name     = "56. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1027  } 
       name     = "87. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1028  } 
       name     = "209. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1029  } 
       name     = "223. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1030  } 
       name     = "255. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1031  } 
       name     = "256. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1032  } 
       name     = "94. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   landunit = 
   {  location = 179 
     name     = "VII. Armeekorps" 
     id       = {  type = 14500 id = 69  } 
     Division = 
     {  id       = {  type = 14500 id = 70  } 
       name     = "57. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 71  } 
       name     = "7. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
       extra    = artillery 
	   brigade_model = 6
      } 
     Division = 
     {  id       = {  type = 14500 id = 72  } 
       name     = "212. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 73  } 
       name     = "168. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   landunit = 
   {  location = 154 
     name     = "X. Armeekorps" 
     id       = {  type = 14500 id = 74  } 
     Division = 
     {  id       = {  type = 14500 id = 75  } 
       name     = "58. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id            = {  type = 14500 id = 76  } 
       name          = "22. Infanterie-Division" 
       type          = infantry 
       model         = 8 
       strength      = 90 
       extra         = artillery 
       brigade_model = 6
      } 
     Division = 
     {  id       = {  type = 14500 id = 77  } 
       name     = "70. Infanterie-Division" 
       type     = infantry 
       model    = 6 
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1033  } 
       name     = "215. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1034  } 
       name     = "225. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1035  } 
       name     = "269. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   landunit = 
   {  location = 146 
     name     = "XI. Armeekorps" 
     id       = {  type = 14500 id = 78  } 
     Division = 
     {  id       = {  type = 14500 id = 79  } 
       name     = "71. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 80  } 
       name     = "19. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
       extra    = anti_air 
	   brigade_model = 2
      } 
     Division = 
     {  id       = {  type = 14500 id = 81  } 
       name     = "216. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1036  } 
       name     = "267. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1037  } 
       name     = "96. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   landunit = 
   {  location = 163 
     name     = "XVI. Armeekorps" 
     id       = {  type = 14500 id = 82  } 
     Division = 
     {  id       = {  type = 14500 id = 83  } 
       name     = "1. Panzer-Division" 
       type     = light_armor 
       model    = 0
       strength = 100 
      } 
     Division = 
     {  id       = {  type = 14500 id = 84  } 
       name     = "2. Panzer-Division" 
       type     = light_armor 
       model    = 0
       strength = 100 
      } 
     Division = 
     {  id           = {  type = 14500 id = 85  } 
       name         = "3. Panzer-Division" 
       type         = light_armor 
       model        = 0
       strength     = 65 
       organisation = 30
      } 
    } 
   landunit = 
   {  location = 177 
     name     = "XIII. Armeekorps" 
     id       = {  type = 14500 id = 1038  } 
     Division = 
     {  id       = {  type = 14500 id = 1039  } 
       name     = "17. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id            = {  type = 14500 id = 1040  } 
       name          = "10. Infanterie-Division" 
       type          = infantry 
       model         = 8 
       strength      = 90 
       extra         = artillery 
       brigade_model = 6
      } 
     Division = 
     {  id       = {  type = 14500 id = 1041  } 
       name     = "73. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1042  } 
       name     = "231. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1043  } 
       name     = "98. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   navalunit = 
   {  name     = "Kriegsmarine" 
     id       = {  type = 14500 id = 1  } 
     location = 147 
     base     = 147 
     Division = 
     {  id    = {  type = 14500 id = 2  } 
       name  = "Deutschland" 
       type  = heavy_cruiser 
       model = 4
      } 
     Division = 
     {  id    = {  type = 14500 id = 3  } 
       name  = "Admiral Scheer" 
       type  = heavy_cruiser 
       model = 4
      } 
     Division = 
     {  id    = {  type = 14500 id = 4  } 
       name  = "Nürnberg" 
       type  = light_cruiser 
       model = 4 
      } 
     Division = 
     {  id    = {  type = 14500 id = 5  } 
       name  = "Leipzig" 
       type  = light_cruiser 
       model = 3 
      } 
     Division = 
     {  id    = {  type = 14500 id = 6  } 
       name  = "Königsberg" 
       type  = light_cruiser 
       model = 3 
      } 
     Division = 
     {  id    = {  type = 14500 id = 7  } 
       name  = "Karlsruhe" 
       type  = light_cruiser 
       model = 3 
      } 
     Division = 
     {  id    = {  type = 14500 id = 8  } 
       name  = "Köln" 
       type  = light_cruiser 
       model = 3 
      } 
     Division = 
     {  id    = {  type = 14500 id = 9  } 
       name  = "Emden" 
       type  = light_cruiser 
       model = 3 
      } 
     Division = 
     {  id    = {  type = 14500 id = 10  } 
       name  = "4. Zerstörergeschwader" 
       type  = destroyer 
       model = 3 
      } 
    } 
 navalunit = 
   {  name     = "I. Truppentransporter Flotte" 
     id       = {  type = 14500 id = 104  } 
     location = 147 
     base     = 147 
     Division = 
     {  id    = {  type = 14500 id = 105  } 
       name  = "1. Truppentransporterflottille" 
       type = transport
	model = 1 
      } 
     Division = 
     {  id    = {  type = 14500 id = 106  } 
       name  = "2. Truppentransporterflottille" 
       type = transport 
	model = 1 
      } 
     Division = 
     {  id    = {  type = 14500 id = 107  } 
       name  = "3. Truppentransporterflottille" 
       type = transport 
	model = 1 
      } 
    } 
   navalunit = 
   {  name     = "II. Unterseebootsflotte" 
     id       = {  type = 14500 id = 20  } 
     location = 152 
     base     = 152 
     Division = 
     {  id    = {  type = 14500 id = 21  } 
       name  = "2. Unterseebootsflottille" 
       type  = submarine 
       model = 3 
      } 
     Division = 
     {  id    = {  type = 14500 id = 25  } 
       name  = "3. Unterseebootsflottille" 
       type  = submarine 
       model = 3 
      } 
    } 
   navalunit = 
   {  name     = "I. Unterseebootsflotte" 
     id       = {  type = 14500 id = 26  } 
     location = 147 
     base     = 147 
     Division = 
     {  id    = {  type = 14500 id = 27  } 
       name  = "1. Unterseebootsflottille" 
       type  = submarine 
       model = 2 
      } 
    } 
   navalunit = 
   {  name     = "Baltische Flotte" 
     id       = {  type = 14500 id = 28  } 
     location = 184 
     base     = 184 
     Division = 
     {  id    = {  type = 14500 id = 29  } 
       name  = "Schleswig-Holstein" 
       type  = battleship 
       model = 1
      } 
     Division = 
     {  id    = {  type = 14500 id = 30  } 
       name  = "Schlesien" 
       type  = battleship 
       model = 1
      } 
     Division = 
     {  id    = {  type = 14500 id = 31  } 
       name  = "1. Zerstörergeschwader" 
       type  = destroyer 
       model = 4 
      } 
     Division = 
     {  id    = {  type = 14500 id = 32  } 
       name  = "2. Zerstörergeschwader" 
       type  = destroyer 
       model = 4 
      } 
     Division = 
     {  id    = {  type = 14500 id = 33  } 
       name  = "3. Zerstörergeschwader" 
       type  = destroyer 
       model = 4 
      } 
    } 
   # ######### Luftwaffe ############## 
   airunit = 
   {  location = 163 
     id       = {  type = 14500 id = 86  } 
     name     = "Luftflotte II" 
     base     = 163 
     Division = 
     {  id       = {  type = 14500 id = 87  } 
       name     = "KG 2 'Holzhammer'" 
       strength = 100 
       type     = tactical_bomber 
       model    = 4
      } 
     Division = 
     {  id       = {  type = 14500 id = 88  } 
       name     = "KG 3 'Blitz'" 
       strength = 100 
       type     = tactical_bomber 
       model    = 4
      } 
     Division = 
     {  id       = {  type = 14500 id = 89  } 
       name     = "Sturzkampfgeschwader 51" 
       strength = 100 
       type     = CAS 
       model    = 0
      } 
     Division = 
     {  id            = {  type = 14500 id = 90  } 
       name          = "JG 2 'Richthofen'" 
       strength      = 100 
       type          = interceptor 
       model         = 7
      } 
     Division = 
     {  id            = {  type = 14500 id = 91  } 
       name          = "JG 26 'Schlageter'" 
       strength      = 100 
       type          = interceptor 
       model         = 7
      } 
    } 
   airunit = 
   {  location = 167 
     id       = {  type = 14500 id = 95  } 
     name     = "Luftflotte III" 
     base     = 167 
     Division = 
     {  id       = {  type = 14500 id = 96  } 
       name     = "KG 53 'Legion Condor'" 
       strength = 100 
       type     = tactical_bomber 
       model    = 4
      } 
     Division = 
     {  id       = {  type = 14500 id = 97  } 
       name     = "Kampfgeschwader 25" 
       strength = 100 
       type     = tactical_bomber 
       model    = 4
      } 
     Division = 
     {  id       = {  type = 14500 id = 98  } 
       name     = "KG 30 'Adler'" 
       strength = 100 
       type     = tactical_bomber 
       model    = 4
      } 
    } 
   airunit = 
   {  location = 137 
     id       = {  type = 14500 id = 99  } 
     name     = "Luftflotte IV" 
     base     = 137 
     Division = 
     {  id       = {  type = 14500 id = 100  } 
       name     = "KG 1 'Hindenburg'" 
       strength = 100 
       type     = tactical_bomber 
       model    = 4
      } 
     Division = 
     {  id       = {  type = 14500 id = 101  } 
       name     = "JG 3 'Udet'" 
       strength = 100 
       type     = interceptor 
       model    = 7
      } 
    } 
   airunit = 
   {  location = 179 
     id       = {  type = 14500 id = 102  } 
     name     = "Luftflotte V" 
     base     = 179 
     Division = 
     {  id       = {  type = 14500 id = 103  } 
       name     = "KG 4 'General Wever'" 
       strength = 100 
       type     = tactical_bomber 
       model    = 4
      } 
    } 

	# ####under developement##### 
	division_development = {
		name  = "Admiral Graf Spee" 
		type  = heavy_cruiser
		model = 4
		cost  = 0.2 
		id    = {  type = 14500 id = 500  } 
		date  = {  year = 1936 month = january day = 6  } 
		new_model = no
	} 
	division_development = {
		name  = "Admiral Hipper" 
		type  = heavy_cruiser
		model = 5
		cost  = 0.2 
		size  = 2
		id    = {  type = 14500 id = 501  } 
		date  = {  year = 1939 month = april day = 25  } 
	} 
	division_development = {
		name  = "Blücher" 
		type  = heavy_cruiser
		model = 5
		cost  = 0.2 
		size  = 2		
		id    = {  type = 14500 id = 502  } 
		date  = {  year = 1939 month = september day = 20  } 
	} 
	division_development = {
		name  = "Gneisenau" 
		type  = battlecruiser
		model = 3
		cost  = 0.3 
		id    = {  type = 14500 id = 503  } 
		date  = {  year = 1938 month = may day = 21  } 
	} 
	division_development = {
		name  = "Scharnhorst" 
		type  = battlecruiser
		model = 3
		cost  = 0.3 
		id    = {  type = 14500 id = 504  } 
		date  = {  year = 1939 month = january day = 7  } 
	} 
	division_development = {
		name  = "8. Zerstörergeschwader" 
		type  = destroyer 
		model = 5 
		cost  = 0.1
		size  = 6
		id    = {  type = 14500 id = 505  } 
		date  = {  year = 1936 month = march day = 1  } 
	}

division_development = {
		name  = "32. Infanterie-Division" 
		type  = infantry
		model = 8
		cost  = 0.1 
		id    = {  type = 14500 id = 507  } 
		date  = {  year = 1936 month = october day = 1  } 
	} 
division_development = {
		name  = "26. Infanterie-Division" 
		type  = infantry
		model = 8
		cost  = 0.1 
		id    = {  type = 14500 id = 508  } 
		date  = {  year = 1936 month = october day = 1  } 
	} 
division_development = {
		name  = "36. Infanterie-Division" 
		type  = infantry
		model = 8
		cost  = 0.1 
		id    = {  type = 14500 id = 509  } 
		date  = {  year = 1936 month = october day = 1  } 
	} 
division_development = {
		name  = "25. Infanterie-Division" 
		type  = infantry
		model = 8
		cost  = 0.1 
		id    = {  type = 14500 id = 510  } 
		date  = {  year = 1936 month = april day = 1  } 
	} 
division_development = {
		name  = "35. Infanterie-Division" 
		type  = infantry
		model = 8
		cost  = 0.1 
		id    = {  type = 14500 id = 511  } 
		date  = {  year = 1936 month = october day = 1  } 
	} 
division_development = {
		name  = "27. Infanterie-Division" 
		type  = infantry
		model = 8
		cost  = 0.1 
		id    = {  type = 14500 id = 512  } 
		date  = {  year = 1936 month = october day = 1  } 
	} 
division_development = {
		name  = "28. Infanterie-Division" 
		type  = infantry
		model = 8
		cost  = 0.1 
		id    = {  type = 14500 id = 513  } 
		date  = {  year = 1936 month = october day = 1  } 
	} 
division_development = {
		name  = "30. Infanterie-Division" 
		type  = infantry
		model = 8
		cost  = 0.1 
		id    = {  type = 14500 id = 514  } 
		date  = {  year = 1936 month = october day = 1  } 
	} 
division_development = {
		name  = "31. Infanterie-Division" 
		type  = infantry
		model = 8
		cost  = 0.1 
		id    = {  type = 14500 id = 515  } 
		date  = {  year = 1936 month = october day = 1  } 
	} 
division_development = {
		name  = "33. Infanterie-Division" 
		type  = infantry
		model = 8
		cost  = 0.1 
		id    = {  type = 14500 id = 516  } 
		date  = {  year = 1936 month = april day = 1  } 
	} 
division_development = {
		name  = "34. Infanterie-Division" 
		type  = infantry
		model = 8
		cost  = 0.1 
		id    = {  type = 14500 id = 517  } 
		date  = {  year = 1936 month = april day = 1  } 
	} 
division_development = {
		name  = "2. Infanterie-Division (mot.)" 
		type  = motorized
		model = 0
		cost  = 0.1 
		id    = {  type = 14500 id = 518  } 
		date  = {  year = 1937 month = october day = 1  } 
	} 
division_development = {
		name  = "13. Infanterie-Division (mot.)" 
		type  = motorized
		model = 0
		cost  = 0.1 
		id    = {  type = 14500 id = 519  } 
		date  = {  year = 1937 month = october day = 1  } 
	} 
division_development = {
		name  = "20. Infanterie-Division (mot.)" 
		type  = motorized
		model = 0
		cost  = 4.5 
		id    = {  type = 14500 id = 520  } 
		date  = {  year = 1937 month = october day = 1  } 
	} 
division_development = {
		name  = "29. Infanterie-Division (mot.)" 
		type  = motorized
		model = 0
		cost  = 0.1 
		id    = {  type = 14500 id = 521  } 
		date  = {  year = 1937 month = october day = 1  } 
	} 
	province_development = { 
		id = { type = 14500 id = 540 } 
		location = 132 
		cost = 0.1 
		size = 4 
		type = land_fort 
		date  = {  year = 1964 } 
		} 
	province_development = { 
		id = { type = 14500 id = 541 } 
		location = 127 
		cost = 0.1 
		size = 4 
		type = land_fort 
		date  = {  year = 1964 } 
		} 		
	province_development = { 
		id = { type = 14500 id = 542 } 
		location = 130 
		cost = 0.1 
		size = 4 
		type = land_fort 
		date  = {  year = 1964 } 
		} 	
	province_development = { 
		id = { type = 14500 id = 546 } 
		location = 152 
		cost = 0.1 
		size = 3 
		type = coastal_fort 
		date  = {  year = 1964 } 
		} 	
} 
