 
############################## 
# Country definition for JAP # 
############################## 
  
##################### 
# Country main data # 
##################### 
  
country = {
	tag                    = JAP 
	belligerence           = 4
	capital                = 1552 
	manpower               = 686
	# Resource Reserves 
	energy                 = 1000 
	metal                  = 1000 
	rare_materials         = 500 
	oil                    = 500 
	supplies               = 500 
	money                  = 100 
	transports             = 1200 
	escorts                = 100 
	research_mod = 0.75
    
	ai_settings = { flags = {   legitIndie = 1 } }
   	diplomacy = {
		relation = {  tag = BEL value = -25  } 
		relation = {  tag = CGX value = -75  } 
		relation = {  tag = CHC value = -200  } 
		relation = {  tag = CHI value = -100  } 
		relation = {  tag = CHL value = 20  } 
		relation = {  tag = CSX value = -100  } 
		relation = {  tag = CXB value = -75  } 
		relation = {  tag = CYN value = -75  } 
		relation = {  tag = U67 value = -200 } 
		relation = {  tag = ENG value = -25  } 
		relation = {  tag = ETH value = 35  } 
		relation = {  tag = FIN value = 20  } 
		relation = {  tag = FRA value = -20  } 
		relation = {  tag = GER value = 20  } 
		relation = {  tag = HOL value = -50  } 
		relation = {  tag = MAN value = 200 access = yes  } 
		relation = {  tag = PHI value = 1  } 
		relation = {  tag = SIA value = 75  } 
		relation = {  tag = SOV value = -10  } 
		relation = {  tag = USA value = 15  } 
	} 
	SpyInfo                = {  country = "JAP" NumberOfSpies = 9  } 
    
claimedprovinces = {
#Philippines
	1567 #Baguio=>Lingay Gulf
	1570 #Tuguegarao=>Apari
	1569 #Olongapo=>Bataan
	1566 #Cabanatuan=>ClarkField
	1565 #Manila/Lamon Bay
	1568 #Legazpi=>Legaspi
	1571 #Mindoro
	1576 #Panay
	1575 #Samar
	1573 #Leyte
	1574 #Bacolod=>Negros
	1580 #Zamboanga
	1578 #Cagayan de Oro=>Cagayan
	1579 #Dabaw=>Davao
	1572 #Palawan
	1577 #Jolo


#Carolines
	1670 #Peleliu
	1671 #Kloulklubek
	1665 #Ponape
	1669 #Yap
	1668 #Woleai
	1667 #Truk
	1666 #Kusaie
	1674 #Bikini
	1675 #Eniwetok
	1676 #Kwajalein
	1677 #Majuro
	1681 #Wotje
	1542 1555 1547 1548 1546 

#Taiwan     
	1361 #Gaoxiong
	1362 #Taipei
	1363 #Taizhong
	1364 #Hualian

#Manchuria
	1211 #Hunjiang->Adong/Liaoyuan
 	1212 #Yanji->Jilin/Liaoyuan
	1214 #Shenyang->Mukden
	1215 #Fushun->Adong
	1216 #Jinzhou->Jinxi
	1217 #Anshan->Dalian
	1218 #Panjin->Jinxi
	1219 #Port Arthur
	1220 #Dandong->Dalian
	1235 #Fuxin->Changde
	1202 #Jiamusi->Jixi/Jiamusi
	1204 #Jixi
	1205 #Mudanjiang->Jilin/Mudanjiang
	1199 #Harbin
	1203 #Qiqihaer
	1200 #Human->Mohe
	1206 #Haila'er
	1213 #Baicheng->Ulan Hot
	1237 #Ulayanqada->Xililnhot/Erenhot
	1201 #Heihe
	1208 #Changchun->Mukden
	1209 #Wulanhaote->Ulan Hot/Xilinhot
	1210 #Tongliyao Hot->Chifeng
	1197 #Hegang->Heihe
	1198 #Butehaqi->Qiqihar
	1245 #Tangshan
	1240 #Sili-yin Qota->Xilinhot/Erenhot
	1236 #Chengde->Changde
	1207 #Jilin->Xinjing

# South Korea
	1228 #Seoul
	1229 #Daeejon
	1233 #Chuncheon
	1232 #Busan
	1231 #Daegu
	1230  #Gwangju
# North Korea
	1223 #Wonsan
	1221 #Pyongyang
	1222 #Sariwon
	1226 #Ganggye
	1227 #Hamheyung
	1224 #Sinuiju
	1225 #Cheongijn
#Guam
	1683 #Guam

# Shandong
	1331
	1328

#Manchuria
 		1202 #Jiamusi->Jixi/Jiamusi
 		1204 #Jixi
 		1205 #Mudanjiang->Jilin/Mudanjiang
 		1199 #Harbin
 		1203 #Qiqihaer
 		1200 #Human->Mohe
 		1206 #Haila'er
 		1213 #Baicheng->Ulan Hot
 		1237 #Ulayanqada->Xililnhot/Erenhot
 		1201 #Heihe
 		1208 #Changchun->Mukden
 		1209 #Wulanhaote->Ulan Hot/Xilinhot
 		1210 #Tongliyao Hot->Chifeng
 		1197 #Hegang->Heihe
 		1198 #Butehaqi->Qiqihar
 		1245 #Tangshan
 		1240 #Sili-yin Qota->Xilinhot/Erenhot
 		1236 #Chengde->Changde
		1207 #Jilin->Xinjing
}

   nationalprovinces      = 
{  
	1543 #Shana
	1544 #Kushiro=>Asahikawa
	1545 #Sapporo
	1549 #Sendai
	1551 #Niigata
	1550 #Yokohama
	1556 #Kanazawa
	1552 #Tokyo
	1557 #Nagoya
	1558 #Kyoto
	1553 #Osaka
	1554 #Hiroshima
	1559 #Matsuyama=>Shikoku
	1560 #Nagasaki=>Fukuoka
	1561 #Kagoshima
	1662 #Chichi Jima=>Bonin Island
	1661 #Iwo Jima
	1663 #Motoyama
	1664 #Mount Suribashi
	1562 #Amami
	1563 #Okinawa South
	1564 #Okinawa North
	1672 #Minami Torichima
	1555 #Kobe
	1542 #Toyohara
        1541 #Okha
        1547 #Akita
	1548 #Nagano
	1546 #Shizuoka
} 
   ownedprovinces         = {  
1543 1544 1545 1549 1551 1550 1556 1552 1557 1558 1553 1554 1559 1560 1561 1662 1661 1663 1664 1562 1563 1564 1672 1686 1685 1684  

#Carolines
	1670 #Peleliu
	1671 #Kloulklubek
	1665 #Ponape
	1669 #Yap
	1668 #Woleai
	1667 #Truk
	1666 #Kusaie
	1674 #Bikini
	1675 #Eniwetok
	1676 #Kwajalein
	1677 #Majuro
	1681 #Wotje
	1542 1555 1547 1548 1546 
# Taiwan		 
	1361 #Gaoxiong#
	1362 #Taipei
	1363 #Tauizhong
	1364  #Hualian

# Port Arthur
	1219

 		1211 #Hunjiang->Adong/Liaoyuan
 		1212 #Yanji->Jilin/Liaoyuan
		1214 #Shenyang->Mukden
 		1215 #Fushun->Adong
 		1216 #Jinzhou->Jinxi
 		1217 #Anshan->Dalian
 		1218 #Panjin->Jinxi
 		1220 #Dandong->Dalian
 		1235 #Fuxin->Changde
		1245 #Tangshan

		#Korea
 		1225 #Cheongjin->Chongyin
 		1226 #Ganggye->Heysan
 		1227 #Hamheung->Hamhung/Heysan
 		1224 #Sinuiju->Sinuiju/Ganggye
 		1223 #Wonsan
 		1221 #Pyongyang
 		1228 #Seoul
 		1233 #Chuncheon->Chunchon
 		1231 #Daegu
 		1232 #Busab->Busan
 		1230 #Gwangju
 		1222 #Sariwon->Seoul
 		1229 #Daejeon-Seoul 

 1328 1331
} 
  
   controlledprovinces    = {  
1543 1544 1545 1549 1551 1550 1556 1552 1557 1558 1553 1554 1559 1560 1561 1662 1661 1663 1664 1562 1563 1564 1672 1686 1685 1684 1668 1670 1671 1665 1669 1667 1666 1674 1675 1676 1677 1681 1364 
1542 1555 1361  
1547 1548 1546 1362 
# Sakhalin 
 1363
# Port Arthur
 1219

 		1211 #Hunjiang->Adong/Liaoyuan
 		1212 #Yanji->Jilin/Liaoyuan
		1214 #Shenyang->Mukden
 		1215 #Fushun->Adong
 		1216 #Jinzhou->Jinxi
 		1217 #Anshan->Dalian
 		1218 #Panjin->Jinxi
 		1220 #Dandong->Dalian
 		1235 #Fuxin->Changde
 		1245 #Tangshan

		#Korea
 		1225 #Cheongjin->Chongyin
 		1226 #Ganggye->Heysan
 		1227 #Hamheung->Hamhung/Heysan
 		1224 #Sinuiju->Sinuiju/Ganggye
 		1223 #Wonsan
 		1221 #Pyongyang
 		1228 #Seoul
 		1233 #Chuncheon->Chunchon
 		1231 #Daegu
 		1232 #Busab->Busan
 		1230 #Gwangju
 		1222 #Sariwon->Seoul
 		1229 #Daejeon-Seoul 

 1328 1331
}
	# JAP 1936 techs 
	# ###################### 
	techapps = {
		#Static Defense
		6680
 
		# Infantry Division  
		1010 1020 1030 1040 1050 1060 1070 1080 1090
		# Mountain
		1160 1170 1180 1190 1200 1210 1220 1230 1240
		# Cavalry Division  
		13060 13070 13080 1310 1320 1330 1340 1350 1360 1370
		# Marines
		1560 1570 1580 1590
		# Engineers
		1830 1840 1850 1860
		# Interbellum 1930 Supply 
		1910 1920 1930 1940 1950 1960 1970 1980
		# Tanks 
		7600 7610 2620 2010 2630 2640 2646 2650 
		# Armored Car  
		2860 2870 2880 2020
		# Field Artillery 
		2290 2300 2310 2900 2910 2920
		# Early Anti-Tank Artillery 
		#2400
		# Static Anti-Air Artillery 
		2800 2450 21180 21190
		# Anti-Air Artillery Brigade 
		2810 2820 2510
		# Improved Destroyer 
		3010 3020 3030 3040 3050 3060 
		# Basic Light Cruiser 
		3110 3120 3130 3140 3150 3160
		# Improved Heavy Cruiser 
		3210 3220 3230 3240 3250 3260
		# Battlecruiser
		3310 3320 3330 3340
		# Battleship 
		3410 3420 3430 3440 3450 3456 3460 3470
		# Aircraft Carrier
		3510 3520 3530
		# Improved Light carrier 
		12100 12110 12120 12130
		# Submarine
		3610 3620 3630 3640 3650
		# Torpedos & ASW
		3720 3730 3736 3740 3750 3760 3900
		# Troopships
		3810 3820
		# Close Air support
		4400
		# Early Fighter  
		4500 4510 4520 4530 4540 4550 4010 4020
		# Early Bomber 
		4600 4610 4620 4630 4120 4130
		# Basic Naval Bomber 
		4700 4710 4190
		# Transports
		4290
		# Multirole fighter
		4300 4310 4320 4330 4340
		# Seaplanes
		4740 4750 4760 4770 4780
		# Strategic Bomber
		4800 4810 4820
		# CAG 34
		4900 4910 4920
		# Modern Agriculture
		5700 5710 5010
		# Manufacturing
		5810 5820 5050 5830
		# Construction Engineering 
		5800 5080 5090 
		# Basic Oil Refining 
		#5190 
		# Computers & Cryptography
		5310 54010 54020 54030 
		5316 5326 5327
		# Medicine
		5600 5610 5620
		# Exp. Rocket
		5560
		# Great War Land Doctrines (entente)
		6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6540 6910
		# Land Doctrines (Light Infantry line)
		6390 6400 6420
		# Hospital System 
		14000 14010
		# Naval Doctrines
		# Engagement Theories
		8010 8020 8030 8040 8050 8060 8070 8080
		# Naval Supremacy
		8100 8110 8120 8150
		# Naval Interdiction
		8500 8510 8520 8550 8560 8600 8610
		# Engagement Tactics - Fleet-in-Being column
		8900 8910 8920 8930 8940 8950
		# Subsidiary Carrier Role
		81650
		# Aerial Supremacy column
		81700 81710
		# Scouting Focus column
		81850 81860
		# Amphibious Warfare
		82300 82310
		# Logistic Support
		82500
		# Air Doctrines - ww2 techs
		27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 9040      
	} 
	blueprints = { 81730 81740 } 
	inventions = { 3000027 }

	policy = {
		date              = {  year = 0 month = january day = 0  } 
		democratic        = 7 
		political_left    = 2 
		freedom           = 3 
		free_market       = 3 
		professional_army = 6 
		defense_lobby     = 8 
		interventionism   = 8 
	} 
	headofstate            = {  type = 9 id = 50001  } 
	headofgovernment       = {  type = 9 id = 50002  } 
	foreignminister        = {  type = 9 id = 50003  } 
	armamentminister       = {  type = 9 id = 50004  } 
	ministerofsecurity     = {  type = 9 id = 50005  } 
	ministerofintelligence = {  type = 9 id = 50006  } 
	chiefofstaff           = {  type = 9 id = 50007  } 
	chiefofarmy            = {  type = 9 id = 50008  } 
	chiefofnavy            = {  type = 9 id = 50009  } 
	chiefofair             = {  type = 9 id = 50010  } 
	
	
	### Japan Land OOB ### 
	
	landunit = {
		id       = {  type = 13016 id = 1  } 
		name     = "Kantôgun" 
		location = 1214 
		division = {
			id       = {  type = 13016 id = 2  } 
			name     = "Kantôgun saikô shireibu" 
			strength = 40 
			type     = hq 
			model    = 2 
		} 
		division = {
			id       = {  type = 13016 id = 3  } 
			name     = "Dai 2 Hoheishidan" 
			strength = 65 
			type     = infantry 
			model    = 7
 			extra    = artillery 
			brigade_model = 6
		} 
		division = {
			id       = {  type = 13016 id = 4  } 
			name     = "Dai 6 Hoheishidan" 
			strength = 65 
			type     = infantry 
			model    = 7 
			extra    = artillery 
			brigade_model = 6
		} 
		division = {
			id       = {  type = 13016 id = 6  } 
			name     = "Dai 7 Hoheishidan" 
			strength = 65 
			type     = infantry 
			model    = 7 
			extra    = engineer 
			brigade_model = 3
		} 
		division = {
			id       = {  type = 13016 id = 7  } 
			name     = "Dai 8 Hoheishidan" 
			strength = 65
			type     = infantry 
			model    = 7 
			extra    = engineer 
			brigade_model = 3
		} 
		division = {
			id       = {  type = 13016 id = 9  } 
			name     = "Dai 9 Hoheishidan" 
			strength = 65
			type     = infantry 
			model    = 7 
			extra    = engineer 
			brigade_model = 3
		} 
		division = {
			id       = {  type = 13016 id = 10  } 
			name     = "Dai 10 Hoheishidan" 
			strength = 65
			type     = infantry 
			model    = 7 
			extra    = engineer 
			brigade_model = 3
		} 
		division = {
			id       = {  type = 13016 id = 18  } 
			name     = "Dai 14 Hoheishidan" 
			strength = 65
			type     = infantry 
			model    = 7 
			extra    = engineer 
			brigade_model = 3
		} 
		division = {
			id       = {  type = 13016 id = 19  } 
			name     = "Dai 16 Hoheishidan" 
			strength = 65
			type     = infantry 
			model    = 7 
			extra    = engineer 
			brigade_model = 3
		} 
		division = {
			id       = {  type = 13016 id = 22  } 
			name     = "Dai 19 Hoheishidan" 
			strength = 65
			type     = infantry 
			model    = 7 
			extra    = engineer
			brigade_model = 3
		} 
	} 
	landunit = {
		id       = {  type = 13016 id = 5  } 
		name     = "Kihei gurupu" 
		location = 1226
		division = {
			id       = {  type = 13016 id = 11  } 
			name     = "Dai 1 Kihei ryodan" 
			strength = 30
			type     = cavalry 
			model    = 9 
		} 
		division = {
			id       = {  type = 13016 id = 12  } 
			name     = "Dai 3 Kihei ryodan" 
			strength = 30
			type     = cavalry 
			model    = 9 
		} 
		division = {
			id       = {  type = 13016 id = 13  } 
			name     = "Dai 4 Kihei ryodan" 
			strength = 30
			type     = cavalry 
			model    = 9 
		} 
	} 

	landunit = {
		id       = {  type = 13016 id = 8  } 
		name     = "Seibu Gun" 
		location = 1560
		division = {
			id       = {  type = 13016 id = 23  } 
			name     = "Dai 11 Hoheishidan" 
			strength = 65
			type     = infantry 
			model    = 7 
			extra    = engineer
			brigade_model = 3
		} 
		division = {
			id       = {  type = 13016 id = 25  } 
			name     = "Dai 12 Hoheishidan" 
			strength = 65
			type     = infantry 
			model    = 7 
			extra    = engineer
			brigade_model = 3
		} 
		division = {
			id       = {  type = 13016 id = 33  } 
			name     = "Dai 18 Hoheishidan" 
			strength = 5
			type     = infantry 
			model    = 6 
		} 
		division = {
			id       = {  type = 13016 id = 34  } 
			name     = "Dai 21 Hoheishidan" 
			strength = 5
			type     = infantry 
			model    = 6 
		} 
		division = {
			id       = {  type = 13016 id = 36  } 
			name     = "Dai 23 Hoheishidan" 
			strength = 5
			type     = infantry 
			model    = 6
		} 
	}
	landunit = {
		id       = {  type = 13016 id = 16  } 
		name     = "Shina chutongun" 
		location = 1245
		division = {
			id       = {  type = 13016 id = 37  } 
			name     = "Dai 5 Hoheishidan" 
			strength = 65
			type     = infantry 
			model    = 7 
			extra    = engineer
			brigade_model = 3
		} 
		division = {
			id       = {  type = 13016 id = 40  } 
			name     = "Dai 20 Hoheishidan" 
			strength = 65
			type     = infantry 
			model    = 7 
			extra    = engineer 
			brigade_model = 3
		} 
		division = {
			id       = {  type = 13016 id = 41  } 
			name     = "Chukogu hohei ryodan" 
			strength = 30
			type     = infantry 
			model    = 7 
			extra    = light_armor_brigade
			brigade_model = 2
		} 
		division = {
			id       = {  type = 13016 id = 43  } 
			name     = "Dai 1 Dokuritsu konsei ryodan" 
			strength = 20
			type     = infantry 
			model    = 7 
			extra    = light_armor_brigade
			brigade_model = 2
		} 
		division = {
			id       = {  type = 13016 id = 44  } 
			name     = "Dai 11 Dokuritsu konsei ryodan" 
			strength = 45 
			type     = infantry 
			model    = 7 
			extra    = artillery 
			brigade_model = 6
		} 
	} 
	landunit = {
		id       = {  type = 13016 id = 21  } 
		name     = "Tobu gun" 
		location = 1557
		division = {
			id       = {  type = 13016 id = 45  } 
			name     = "Dai 3 Hoheishidan"  
			strength = 65 
			type     = infantry 
			model    = 7 
			extra    = engineer 
			brigade_model = 3
		} 
		division = {
			id       = {  type = 13016 id = 48  } 
			name     = "Dai 4 Hoheishidan" 
			strength = 65
			type     = infantry 
			model    = 7 
			extra    = engineer 
			brigade_model = 3
		} 
		division = {
			id       = {  type = 13016 id = 53  } 
			name     = "Dai 13 Hoheishidan" 
			strength = 5
			type     = infantry 
			model    = 6 
		} 
		division = {
			id       = {  type = 13016 id = 58  } 
			name     = "Dai 15 Hoheishidan" 
			strength = 5
			type     = infantry 
			model    = 6 
		} 
		division = {
			id       = {  type = 13016 id = 60  } 
			name     = "Dai 17 'Ranan' Hoheishidan" 
			strength = 5
			type     = infantry 
			model    = 6 
		} 
	} 
	landunit = {
		id       = {  type = 13016 id = 24  } 
		name     = "Tokyo keibi shireibu"  
		location = 1552
		division = {
			id       = {  type = 13016 id = 17  } 
			name     = "Daihon'ei" 
			strength  = 40 
			type     = hq 
			model    = 2 
			extra    = anti_air
			brigade_model = 1
		} 
		division = {
			id       = {  type = 13016 id = 70  } 
			name     = "Dai 1 Hoheishidan" 
			strength = 65
			type     = infantry 
			model    = 7 
			extra    = artillery 
			brigade_model = 6
		} 
		division = {
			id       = {  type = 13016 id = 29  } 
			name     = "Dai 22 Hoheishidan" 
			strength = 5
			type     = infantry
			model    = 6
		} 
		division = {
			id       = {  type = 13016 id = 30  } 
			name     = "Konoe Shidan" 
			strength = 65
			type     = infantry
			model    = 8
			extra    = anti_air 
			brigade_model = 1
		} 
		division = {
			id       = {  type = 13016 id = 31  } 
			name     = "Dai 2 Kihei ryodan" 
			strength = 30
			type     = cavalry 
			model    = 9 
		} 
	} 
	landunit = {
		id       = {  type = 13016 id = 28  } 
		name     = "Kure Kaigunku"  
		location = 1554
		division = {
			id       = {  type = 13016 id = 26  } 
			name     = "Kure Kaigun tokubetsu rikusentai"
			strength = 15
			type     = marine
			model    = 2
		} 
	} 
	landunit = {
		id       = {  type = 13016 id = 32  } 
		name     = "Maizuru Kaigunku" 
		location = 1558
		division = {
			id       = {  type = 13016 id = 20  } 
			name     = "Maizuru Kaigun tokubetsu rikusentai" 
			strength = 15
			type     = marine
			model    = 2
		} 
	} 
	landunit = {
		id       = {  type = 13016 id = 35  } 
		name     = "Sasebo Kaigunku" 
		location = 1560 
		division = {
			id       = {  type = 13016 id = 38  } 
			name     = "Sasebo Kaigun tokubetsu rikusentai" 
			strength = 15 
			type     = marine
			model    = 2 
		} 
	} 
	landunit = {
		id       = {  type = 13016 id = 39  } 
		name     = "Yokosuka Kaigunku" 
		location = 1552
		division = {
			id       = {  type = 13016 id = 27  } 
			name     = "Yokosuka Kaigun tokubetsu rikusentai" 
			strength = 15 
			type     = marine
			model    = 2
		} 
	}
	landunit = {
		id       = {  type = 13016 id = 42  } 
		name     = "Uchi komu ko gun" # Inner Mongolian army
		location = 1240
		division = {
			id       = {  type = 13016 id = 14  } 
			name     = "Uchi komu ko gun" 
			strength = 100 
			type     = cavalry 
			model    = 7 
		} 
	} 
	landunit = {
		id       = {  type = 13016 id = 46  } 
		name     = "Higashi no Kawakita gun" # Chinese collaborationists 
		location = 1245
		division = {
			id       = {  type = 13016 id = 50  } 
			name     = "Dai 1 Tai" 
			strength = 80
			type     = militia
			model    = 4
		} 
		division = {
			id       = {  type = 13016 id = 51  } 
			name     = "Dai 2 Tai" 
			strength = 80
			type     = militia
			model    = 4
		} 
		division = {
			id       = {  type = 13016 id = 55  } 
			name     = "Dai 3 Tai" 
			strength = 80
			type     = militia
			model    = 4
		} 
		division = {
			id       = {  type = 13016 id = 56  } 
			name     = "Dai 4 Tai" 
			strength = 80
			type     = militia
			model    = 4
		} 
		division = {
			id       = {  type = 13016 id = 72  } 
			name     = "Kunren tai" 
			strength = 40
			type     = militia
			model    = 3
		} 
	} 


	### Japan Navy OOB ### 
  
	# CarDiv 1
	navalunit = { 
		id = { type = 13016 id = 112 } 
		name = "Dai 1 Koku Sentai" 
		location = 1552 
		base = 1552 
		division = { 
			id = { type = 13016 id = 175 } 
			name = "Akagi" 
			type = carrier 
			model = 0 
			extra1 = cag 
			brigade_model1 = 2 
		} 
		division = { 
			id = { type = 13016 id = 177 } 
			name = "Kaga" 
			type = carrier 
			model = 0 
			extra1 = cag 
			brigade_model1 = 2 
		} 
		division = { 
			id = { type = 13016 id = 163 } 
			name = "Myoko" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 164 } 
			name = "Ashigara" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 131 } 
			name = "Tama" 
			type = light_cruiser 
			model = 2 
		} 
		division = { 
			id = { type = 13016 id = 132 } 
			name = "Kitakami" 
			type = light_cruiser 
			model = 2 
		}  
		division = { 
			id = { type = 13016 id = 127 } 
			name = "Tatsuta" 
			type = light_cruiser 
			model = 2 
		} 
		division = { 
			id = { type = 13016 id = 182 } 
			name = "Dai 1 Kuchikusentai" 
			type = destroyer 
			model = 3 
		} 
	}

	# CarDiv 2 (put Soryu and Hiryu in here)
	navalunit = { 
		id = { type = 13016 id = 116 } 
		name = "Dai 2 Koku Sentai" 
		location = 1552 
		base = 1552 
		division = { 
			id = { type = 13016 id = 179 } 
			name = "Ryujo" 
			type  = light_carrier 
			model = 0 
			extra1 = light_cag
			brigade_model1 = 2
		} 
		division = { 
			id = { type = 13016 id = 170 } 
			name = "Mikuma" 
			type = heavy_cruiser 
			model = 4 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 171 } 
			name = "Mogami" 
			type = heavy_cruiser 
			model = 4 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 150 } 
			name = "Yubari" 
			type = light_cruiser 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 151 } 
			name = "Isuzu" 
			type = light_cruiser 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 197 } 
			name = "Dai 2 Kuchikusentai" 
			type = destroyer 
			model = 5 
		} 
		division = { 
			id = { type = 13016 id = 198 } 
			name = "Dai 3 Kuchikusentai" 
			type = destroyer 
			model = 5 
		} 
		division = { 
			id = { type = 13016 id = 201 } 
			name = "Dai 4 Kuchikusentai" 
			type = destroyer 
			model = 5 
		} 
	} 
	
	# BatDiv 1
	navalunit = { 
		id = { type = 13016 id = 120 } 
		name = "Dai 1 Senkan Sentai" 
		location = 1554 
		base = 1554 
		division = { 
			id = { type = 13016 id = 123 } 
			name = "Nagato" 
			type = battleship 
			model = 5 
			extra1 = naval_anti_air_l
			extra2 = naval_fire_controll_l
			extra3 = floatplane
			brigade_model3 = 4
		} 
		division = { 
			id = { type = 13016 id = 173 } 
			name = "Hosho" 
			type = escort_carrier 
			model = 2 
		} 
		division = { 
			id = { type = 13016 id = 166 } 
			name = "Takao" 
			type = heavy_cruiser 
			model = 4 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 167 } 
			name = "Chokai" 
			type = heavy_cruiser 
			model = 4 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 145 } 
			name = "Natori" 
			type = light_cruiser 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 146 } 
			name = "Kinu" 
			type = light_cruiser 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 207 } 
			name = "Dai 5 Kuchikusentai" 
			type = destroyer 
			model = 5
		} 
		division = { 
			id = { type = 13016 id = 215 } 
			name = "Dai 6 Kuchikusentai" 
			type = destroyer 
			model = 5
		} 
		division = { 
			id = { type = 13016 id = 205 } 
			name = "Dai 7 Kuchikusentai" 
			type = destroyer 
			model = 5 
		} 
	} 
	
	# BatDiv 2
	navalunit = { 
		id = { type = 13016 id = 124 } 
		name = "Dai 2 Senkan Sentai" 
		location = 1559 
		base = 1559 
		division = { 
			id = { type = 13016 id = 121 } 
			name = "Ise" 
			type = battleship 
			model = 4 
			extra1 = naval_improved_hull_l
			extra2 = naval_anti_air_l
			extra3 = floatplane
			brigade_model3 = 4
		} 
		division = { 
			id = { type = 13016 id = 122 } 
			name = "Hyuga" 
			type = battleship 
			model = 4 
			extra1 = naval_improved_hull_l
			extra2 = naval_anti_air_l
			extra3 = floatplane
			brigade_model3 = 4
		} 
		division = {
			id = { type = 13016 id = 260 }
			name = "Kamoi"
			type = escort_carrier
			model = 0
		}
		division = { 
			id = { type = 13016 id = 156 } 
			name = "Kako" 
			type = heavy_cruiser 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 133 } 
			name = "Furutaka" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 130 } 
			name = "Kuma" 
			type = light_cruiser 
			model = 2 
		} 
		division = { 
			id = { type = 13016 id = 161 } 
			name = "Naka" 
			type = light_cruiser 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 214 } 
			name = "Dai 8 Kuchikusentai" 
			type = destroyer 
			model = 4 
		} 
		division = { 
			id = { type = 13016 id = 206 } 
			name = "Dai 9 Kuchikusentai" 
			type = destroyer 
			model = 4 
		} 
		division = { 
			id = { type = 13016 id = 196 } 
			name = "Dai 10 Kuchikusentai" 
			type = destroyer 
			model = 4 
		} 
	} 
	
	# BatDiv 3 (add the other Kongos here)
	navalunit = { 
		id = { type = 13016 id = 126 } 
		name = "Dai 3 Senkan Sentai" 
		location = 1552 
		base = 1552 
		division = { 
			id = { type = 13016 id = 115 } 
			name = "Haruna" 
			type = battlecruiser 
			model = 3 
			extra1 = naval_improved_hull_l
			extra2 = floatplane
			brigade_model2 = 4
		} 
		division = { 
			id = { type = 13016 id = 165 } 
			name = "Atago" 
			type = heavy_cruiser 
			model = 4 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 169 } 
			name = "Maya" 
			type = heavy_cruiser 
			model = 4 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 134 } 
			name = "Kitikama" 
			type = light_cruiser 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 147 } 
			name = "Yuru" 
			type = light_cruiser 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 213 } 
			name = "Dai 11 Kuchikusentai" 
			type = destroyer 
			model = 4 
		} 
		division = { 
			id = { type = 13016 id = 186 } 
			name = "Dai 12 Kuchikusentai" 
			type = destroyer 
			model = 4 
		} 
		division = { 
			id = { type = 13016 id = 200 } 
			name = "Dai 13 Kuchikusentai" 
			type = destroyer 
			model = 4 
		} 
		division = { 
			id = { type = 13016 id = 199 } 
			name = "Dai 14 Kuchikusentai" 
			type = destroyer 
			model = 4 
		} 
	}
		
	# BatDiv 4 (not sure it really existed, but whatever)
	navalunit = { 
		id = { type = 13016 id = 172 } 
		name = "Dai 4 Senkan Sentai" 
		location = 1552 
		base = 1552 
		division = { 
			id = { type = 13016 id = 118 } 
			name = "Fuso" 
			type = battleship 
			model = 3 
			extra1 = naval_improved_hull_l
			extra2 = floatplane
			brigade_model2 = 4
		} 
		division = { 
			id = { type = 13016 id = 119 } 
			name = "Yamashiro" 
			type = battleship 
			model = 3 
			extra1 = naval_improved_hull_l
			extra2 = floatplane
			brigade_model2 = 4
		} 
		division = {
			id = { type = 13016 id = 261 }
			name = "Notoro"
			type = escort_carrier
			model = 0
		}
		division = { 
			id = { type = 13016 id = 157 } 
			name = "Aoba" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 158 } 
			name = "Kinugasa" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 137 } 
			name = "Nagara" 
			type = light_cruiser 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 140 } 
			name = "Yura" 
			type = light_cruiser 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 194 } 
			name = "Dai 15 Kuchikusentai" 
			type = destroyer 
			model = 1
		} 
		division = { 
			id = { type = 13016 id = 181 } 
			name = "Dai 16 Kuchikusentai" 
			type = destroyer 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 183 } 
			name = "Dai 17 Kuchikusentai" 
			type = destroyer 
			model = 1 
		} 
	} 
			
	navalunit = { 
		id = { type = 13016 id = 193 } 
		name = "Dai 5 Sentai" 
		location = 1553 
		base = 1553 
		division = { 
			id = { type = 13016 id = 159 } 
			name = "Nachi" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 160 } 
			name = "Haguro" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 135 } 
			name = "Kiso" 
			type = light_cruiser 
			model = 2 
		} 
		division = { 
			id = { type = 13016 id = 136 } 
			name = "Oi" 
			type = light_cruiser 
			model = 2 
		} 
		division = { 
			id = { type = 13016 id = 139 } 
			name = "Tenryu" 
			type = light_cruiser 
			model = 2
		} 
		division = { 
			id = { type = 13016 id = 152 } 
			name = "Sendai" 
			type = light_cruiser 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 153 } 
			name = "Abukuma" 
			type = light_cruiser 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 154 } 
			name = "Jintsu" 
			type = light_cruiser 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 184 } 
			name = "Dai 18 Kuchikusentai" 
			type = destroyer 
			model = 4 
			} 
		division = { 
			id = { type = 13016 id = 185 } 
			name = "Dai 19 Kuchikusentai" 
			type = destroyer 
			model = 4 
		} 
	} 
	
	# Crappy Reserve Fleet 1
	navalunit = { 
		id = { type = 13016 id = 231 } 
		name = "Dai 7 sentai" 
		location = 1560 
		base = 1560 
		division = { 
			id = { type = 13016 id = 148 } 
			name = "Asama" 
			type = heavy_cruiser 
			model = 1 
		} 
		division = {
			id = { type = 13016 id = 258 }
			name = "Iwate"
			type = heavy_cruiser
			model = 1
		}
		division = { 
			id = { type = 13016 id = 138 } 
			name = "Izumo" 
			type = heavy_cruiser 
			model = 1
		} 
		division = { 
			id = { type = 13016 id = 2249 } 
			name = "Dai 20 Kuchikusentai" 
			type = destroyer 
			model = 3
		} 
		division = { 
			id = { type = 13016 id = 2250 } 
			name = "Dai 21 Kuchikusentai" 
			type = destroyer 
			model = 3
		} 
	}

	# Crappy Reserve Fleet 2
	navalunit = { 
		id = { type = 13016 id = 212 } 
		name = "Dai 9 Sentai" 
		location = 1552 
		base = 1552 
		division = {
			id = { type = 13016 id = 259 }
			name = "Isuzu"
			type = heavy_cruiser
			model = 1
		}
		division = {
			id = { type = 13016 id = 262 }
			name = "Yakumo"
			type = heavy_cruiser
			model = 1
		}
		division = { 
			id = { type = 13016 id = 129 } 
			name = "Yahagi" 
			type = light_cruiser 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 128 } 
			name = "Hirado" 
			type = light_cruiser 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 2253 } 
			name = "Dai 22 Kuchikusentai" 
			type = destroyer 
			model = 0
		} 
		division = { 
			id = { type = 13016 id = 2246 } 
			name = "Dai 23 Kuchikusentai" 
			type = destroyer
			model = 0
		} 
		division = { 
			id = { type = 13016 id = 2247 } 
			name = "Dai 24 Kuchikusentai" 
			type = destroyer 
			model = 0
		} 
	} 
	
	# Submarine Fleet 1
	navalunit = { 
		id = { type = 13016 id = 280 } 
		name = "Dai 1 Sensui Kantai" 
		location = 1554 
		base = 1554 
		division = { 
			id = { type = 13016 id = 281 } 
			name = "Dai 1 Sensuisentai" 
			type = submarine 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 282 } 
			name = "Dai 2 Sensuisentai" 
			type = submarine 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 283 } 
			name = "Dai 3 Sensuisentai" 
			type = submarine 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 284 } 
			name = "Dai 4 Sensuisentai" 
			type = submarine 
			model = 3 
		} 
	} 

	# Submarine Fleet 2
	navalunit = { 
		id = { type = 13016 id = 285 } 
		name = "Dai 2 Sensui Kantai" 
		location = 1552 
		base = 1552 
		division = { 
			id = { type = 13016 id = 286 } 
			name = "Dai 5 Sensuisentai" 
			type = submarine 
			model = 2
		} 
		division = { 
			id = { type = 13016 id = 287 } 
			name = "Dai 6 Sensuisentai" 
			type = submarine 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 288 } 
			name = "Dai 7 Sensuisentai" 
			type = submarine 
			model = 1
		} 
	}
	
	# Submarine Fleet 3
	navalunit = {
		id = { type = 13016 id = 300 }
		name = "Dai 3 Sensui Kantai"
		location = 1552
		base = 1552
		division = { 
			id = { type = 13016 id = 289 } 
			name = "Dai 8 Sensuisentai" 
			type = submarine 
			model = 1
		} 
		division = { 
			id = { type = 13016 id = 290 } 
			name = "Dai 9 Sensuisentai" 
			type = submarine 
			model = 1
		} 
		division = { 
			id = { type = 13016 id = 291 } 
			name = "Dai 10 Sensuisentai"
			type = submarine 
			model = 1
		} 
		division = { 
			id = { type = 13016 id = 292 } 
			name = "Dai 11 Sensuisentai"
			type = submarine 
			model = 1
		} 
	} 
	
	# Submarine Fleet 4
	navalunit = { 
		id = { type = 13016 id = 293 } 
		name = "Dai 4 Sensui Kantai" 
		location = 1554 
		base = 1554 
		division = { 
			id = { type = 13016 id = 294 } 
			name = "Dai 12 Sensuisentai" 
			type = nuclear_submarine
			model = 0
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 295 } 
			name = "Dai 13 Sensuisentai" 
			type = submarine 
			model = 4
		} 
	} 

	# Transport Fleet 1
	navalunit = { 
		id = { type = 13016 id = 1508 } 
		name = "Dai 1 Yuso Kantai" 
		location = 1553 
		base = 1553 
		division = { 
			id = { type = 13016 id = 2254 } 
			name = "Dai 25 Kuchikusentai" 
			type = destroyer 
			model = 4
		} 
		division = { 
			id = { type = 13016 id = 187 } 
			name = "Dai 1 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 188 } 
			name = "Dai 2 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 189 } 
			name = "Dai 3 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 221 } 
			name = "Dai 16 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
	} 
	
	# Transport Fleet 2
	navalunit = { 
		id = { type = 13016 id = 1510 } 
		name = "Dai 2 Yuso Kantai" 
		location = 1553 
		base = 1553 
		division = { 
			id = { type = 13016 id = 2255 } 
			name = "Dai 26 Kuchikusentai" 
			type = destroyer 
			model = 1
		} 
		division = { 
			id = { type = 13016 id = 192 } 
			name = "Dai 6 Yuso Sentai" 
			type = transport 
			model = 1 
			} 
		division = { 
			id = { type = 13016 id = 191 } 
			name = "Dai 5 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 190 } 
			name = "Dai 4 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 224 } 
			name = "Dai 19 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
	} 
	
	# Transport Fleet 3
	navalunit = { 
		id = { type = 13016 id = 2244 } 
		name = "Dai 3 Yuso Kantai" 
		location = 1552 
		base = 1552 
		division = { 
			id = { type = 13016 id = 2256 } 
			name = "Dai 27 Kuchikusentai" 
			type = destroyer 
			model = 1
		} 
		division = { 
			id = { type = 13016 id = 218 } 
			name = "Dai 14 Yuso Sentai" 
			type = transport 
			model = 1 
			} 
		division = { 
			id = { type = 13016 id = 219 } 
			name = "Dai 15 Yuso Sentai" 
			type = transport 
			model = 1 
			} 
		division = { 
			id = { type = 13016 id = 222 } 
			name = "Dai 17 Yuso Sentai" 
			type = transport 
			model = 1 
			} 
		division = { 
			id = { type = 13016 id = 223 } 
			name = "Dai 18 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
	} 
		
	# Transport Fleet 4
	navalunit = { 
		id = { type = 13016 id = 2259 } 
		name = "Dai 4 Yuso Kantai" 
		location = 1554 
		base = 1554 
		division = { 
			id = { type = 13016 id = 2257 } 
			name = "Dai 28 Kuchikusentai" 
			type = destroyer 
			model = 1
		} 
		division = { 
			id = { type = 13016 id = 202 } 
			name = "Dai 7 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 203 } 
			name = "Dai 8 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 216 } 
			name = "Dai 20 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 217 } 
			name = "Dai 13 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
	} 
	
	# Transport Fleet 5
	navalunit = { 
		id = { type = 13016 id = 204 } 
		name = "Dai 5 Yuso Kantai" 
		location = 1552 
		base = 1552 
		division = { 
			id = { type = 13016 id = 2258 } 
			name = "Dai 29 Kuchikusentai" 
			type = destroyer 
			model = 1
		} 
		division = { 
			id = { type = 13016 id = 211 } 
			name = "Dai 12 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 208 } 
			name = "Dai 9 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 209 } 
			name = "Dai 10 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 210 } 
			name = "Dai 11 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
	} 
	
#	navalunit = { 
#		id = { type = 13016 id = 180 } 
#		name = "Dai 5 Sentai" 
#		location = 1553 
#		base = 1553 
#	} 

	
	### Japan Air OOB ### 
	
	airunit = {
		location = 1552 
		base     = 1552 
		id       = {  type = 13016 id = 236  } 
		name     = "Dai 1 Nihon Kokutai" 
		division = {
			id    = {  type = 13016 id = 237  } 
			name  = "Dai 1 Keibakugeki Hikodan" 
			type  = tactical_bomber 
			model = 4
		} 
	} 
	airunit = {
		location = 1552 
		base     = 1552 
		id       = {  type = 13016 id = 238  } 
		name     = "Dai 2 Nihon Kokutai" 
		division = {
			id    = {  type = 13016 id = 239  } 
			name  = "Dai 2 Keibakugeki Hikodan" 
			type  = tactical_bomber 
			model = 4
		} 
	} 
	airunit = {
		location = 1219 
		base     = 1219 
		id       = {  type = 13016 id = 240  } 
		name     = "Dai 1 Kokutai" 
		division = {
			id    = {  type = 13016 id = 241  } 
			name  = "Dai 3 Keibakugeki Hikodan" 
			type  = tactical_bomber 
			model = 4
		} 
	} 
	airunit = {
		location = 1219 
		base     = 1219 
		id       = {  type = 13016 id = 242  } 
		name     = "Dai 3 Nihon Kokutai" 
		division = {
			id    = {  type = 13016 id = 243  } 
			name  = "Dai 4 Keibakugeki Hikodan" 
			type  = tactical_bomber 
			model = 4
		} 
	} 
	airunit = {
		location = 1219 
		base     = 1219 
		id       = {  type = 13016 id = 244  } 
		name     = "Dai 2 Kokutai" 
		division = {
			id    = {  type = 13016 id = 245  } 
			name  = "Dai 5 Keibakugeki Hikodan" 
			type  = tactical_bomber 
			model = 4 
		} 
	} 
	airunit = {
		location = 1552 
		base     = 1552 
		id       = {  type = 13016 id = 246  } 
		name     = "Dai 4 Nihon Kokutai" 
		division = {
			id    = {  type = 13016 id = 247  } 
			name  = "Dai 13 Kaigunkogeki Hikodan" 
			type  = naval_bomber 
			model = 1
		} 
	} 
	airunit = {
		location = 1219 
		base     = 1219 
		id       = {  type = 13016 id = 248  } 
		name     = "Dai 5 Nihon Kokutai" 
		division = {
			id    = {  type = 13016 id = 249  } 
			name  = "Dai 33 Goraikogeki Hikodan" 
			type  = naval_bomber 
			model = 2
		} 
	} 
	airunit = {
		id       = {  type = 13016 id = 250  } 
		name     = "Dai 1 Kyokutsi Hikodan" 
		location = 1226 
		base     = 1226 
		division = {
			id       = {  type = 13016 id = 251  } 
			name     = "Dai 1 Kyokutsi Hikodan" 
			strength = 85 
			type     = interceptor 
			model    = 7
		} 
	} 
	airunit = {
		id       = {  type = 13016 id = 252  } 
		name     = "Dai 2 Kyokutsi Hikodan" 
		location = 1226 
		base     = 1226 
		division = {
			id       = {  type = 13016 id = 253  } 
			name     = "Dai 2 Kyokutsi Hikodan" 
			strength = 85 
			type     = interceptor 
			model    = 7
		} 
	} 
	airunit = {
		id       = {  type = 13016 id = 254  } 
		name     = "Dai 3 Kyokutsi Hikodan" 
		location = 1219 
		base     = 1219 
		division = {
			id       = {  type = 13016 id = 255  } 
			name     = "Dai 3 Kyokutsi Hikodan" 
			strength = 85 
			type     = interceptor 
			model    = 7
		} 
	} 
	airunit = {
		id       = {  type = 13016 id = 256  } 
		name     = "Dai 4 Kyokutsi Hikodan" 
		location = 1552 
		base     = 1552 
		division = {
			id       = {  type = 13016 id = 257  } 
			name     = "Dai 4 Kyokutsi Hikodan" 
			strength = 85 
			type     = interceptor 
			model    = 6
		} 
	}
	
	
	# ### Under division_development ### 
	
	division_development = {  
		name  = "Soryu" 
		type  = carrier 
		model = 2 
		cost  = 0.1
		id    = {  type = 13016 id = 263  } 
		date  = {  year = 1936 month = december day = 20  } 
		extra = cag 
		brigade_model = 2 
		new_model = no
	} 
	division_development = {  
		name  = "Kumano"
		type  = heavy_cruiser
		model = 4
		cost  = 0.1
		id    = { type = 13016 id = 264 }
		date  = { year = 1937 month = october day = 1 }
		extra1 = floatplane
		brigade_model1 = 4
		new_model = no
	}
	division_development = {  
		name  = "Suzuya"
		type  = heavy_cruiser
		model = 4
		cost  = 0.1
		id    = { type = 13016 id = 265 }
		date  = { year = 1937 month = october day = 31 }
		extra1 = floatplane
		brigade_model1 = 4
		new_model = no
	}
	division_development = {  
		name  = "Tone"
		type  = heavy_cruiser
		model = 5
		cost  = 0.1
		id    = { type = 13016 id = 266 }
		date  = { year = 1938 month = november day = 20 }
		extra1 = floatplane
		brigade_model1 = 4
		new_model = no
	}
	division_development = {  
		name  = "Chikuma"
		type  = heavy_cruiser
		model = 5
		cost  = 0.1
		id    = { type = 13016 id = 267 }
		date  = { year = 1939 month = may day = 20 }
		extra1 = floatplane
		brigade_model1 = 4
		new_model = no
	}
	division_development = {
		name  = "Dai 30 Kuchikusentai" 
		type  = destroyer 
		model = 5 
		cost  = 0.1
		id    = {  type = 13016 id = 268  } 
		date  = {  year = 1936 month = march day = 1  } 
		new_model = no
	} 
	division_development = {
		name  = "Dai 31 Kuchikusentai" 
		type  = destroyer 
		model = 5 
		cost  = 0.1
		id    = {  type = 13016 id = 368  } 
		date  = {  year = 1936 month = june day = 1  } 
		new_model = no
	} 
	division_development = {
		name  = "Dai 32 Kuchikusentai" 
		type  = destroyer 
		model = 5 
		cost  = 0.1
		id    = {  type = 13016 id = 468  } 
		date  = {  year = 1936 month = september day = 1  } 
		new_model = no
	} 
	division_development = { 
		id = { type = 13016 id = 113 } 
		name = "Kongo" 
		type = battlecruiser 
		model = 3 
		cost = 1.1
		unitcost = no
		date = { year = 1937 month = january day = 8 }
		extra1 = naval_improved_hull_l
		extra2 = floatplane
		brigade_model2 = 4
		new_model = no
	} 
	division_development = { 
		id = { type = 13016 id = 117 } 
		name = "Kirishima" 
		type = battlecruiser 
		model = 3 
		cost = 1.1
		unitcost = no
		date = { year = 1936 month = june day = 8 }
		extra1 = naval_improved_hull_l
		extra2 = floatplane
		brigade_model2 = 4
		new_model = no
	} 
	division_development = { 
		id = { type = 13016 id = 114 } 
		name = "Hiei" 
		type = battlecruiser 
		model = 3 
		cost = 1.1
		unitcost = no
		# Date is bogus, Hiei didn't begin rebuild until Apr '37 (finished Jan '40).
		# Starting rebuild in Jan '36 as we have no easy way to model this otherwise.
		# Giving ship an earlier completion date since it has an earlier start date.
		date = { year = 1938 month = may day = 1 } 
		extra1 = naval_improved_hull_l
		extra2 = floatplane
		brigade_model2 = 4
		new_model = no
	} 
	division_development = { 
		id = { type = 13016 id = 125 } 
		name = "Mutsu" 
		type = battleship 
		model = 5 
		cost = 0.5
		unitcost = no
		date = { year = 1936 month = september day = 30 }
		extra1 = naval_anti_air_l
		extra2 = naval_fire_controll_l
		extra3 = naval_improved_hull_l
		extra4 = floatplane
		brigade_model4 = 4
		new_model = no
	} 
	division_development = {
		id = { type = 13016 id = 269 }
		name = "Chitose"
		type = escort_carrier
		cost = 0.1
		date = { year = 1938 month = july day = 25 }
		new_model = no
	}
	division_development = {
		id = { type = 13016 id = 270 }
		name = "Chiyoda"
		type = escort_carrier
		cost = 0.1
		date = { year = 1938 month = july day = 25 }
		new_model = no
	}
	division_development = {
		id = { type = 13016 id = 271 }
		name = "Dai 13 Sensuisentai"
		type = submarine
		model = 4
		date = { year = 1936 month = may day = 1 }
		cost = 0.1
	}

	landdivision = { dormant = yes id = { type = 13016 id = 2000 } name = "1 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2001 } name = "22 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2002 } name = "2 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2003 } name = "3 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2004 } name = "4 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2005 } name = "5 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2006 } name = "6 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2007 } name = "7 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2008 } name = "8 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2009 } name = "9 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2010 } name = "10 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2011 } name = "11 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2012 } name = "12 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2013 } name = "13 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2014 } name = "14 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2015 } name = "15 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2016 } name = "16 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2017 } name = "17 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2018 } name = "18 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2019 } name = "19 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2020 } name = "20 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2021 } name = "21 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }

} 
 
