
 ############################## 
 # Country definition for SIA # 
 ############################## 
  
 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = SIA 
	name = SIA36
   # Resource Reserves 
energy                 = 540
metal                  = 270
rare_materials         = 135
   transports = 100
   oil                    = 500 
   supplies               = 500 
   money                  = 10 
   capital                = 1423 
   manpower               = 4 
      
   ai_settings = { flags = {   legitIndie = 1 } }   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 4 
     political_left    = 3 
     freedom           = 3 
     free_market       = 3 
     professional_army = 5 
     defense_lobby     = 5 
     interventionism   = 5 
    } 
    ownedprovinces =      {
 	1431 #Songhla=>Singora
 	1430 #Nakhon Sri Thammarat=>Kra
 	1429 #Prachuap Khiri Khau=>Kra
	 1424 #Nakhon Sawan=>Thon Buri
 	1425 #Chiang Mai=>Chian Rai
 	1426 #Phitsanulok
 	1428 #Phetchabun=>Phitsanulok
 	1427 #Khon Kaen
 	1422 #Chon Buri=>Nakhon Ratchthani
 	1423 #Bangkok
	 }
    controlledprovinces = {
	1431 #Songhla=>Kra
 	1430 #Nakhon Sri Thammarat
 	1429 #Prachuap Khiri Khau
 	1424 #Nakhon Sawan=>Thon Buri
 	1425 #Chiang Mai=>Chian Rai
 	1426 #Phitsanulok
 	1428 #Phetchabun=>Phitsanulok
 	1427 #Khon Kaen
 	1422 #Chon Buri=>Nakhon Ratchthani
 	1423 #Bangkok
	  }
    nationalprovinces =   {
 	1430 #Nakhon Sri Thammarat
 	1429 #Prachuap Khiri Khau
 	1424 #Nakhon Sawan=>Thon Buri
 	1425 #Chiang Mai=>Chian Rai
 	1426 #Phitsanulok
 	1428 #Phetchabun=>Phitsanulok
 	1427 #Khon Kaen
 	1422 #Chon Buri=>Nakhon Ratchthani
 	1423 #Bangkok

1433
1434
1413
1412
1409
1391
	}

claimedprovinces = {

#Claims French Indochine
1402 #Battambang
1401 #Seam Reap
1400 #Phnom Penh
1398
1394
1405
1404

1431

}
   # ROTW Minor Tech '36 
   # Group D 1936 techs 
   # ###################### 
   # GW fighter 
   techapps = {
		#Static Defense
		6680
  
#Interwar Fighter  
4500 4510 4520 4530 4540 4550 4010   
#Interwar Bomber 
4600 4610 4620 4630 4120   
#Basic Armoured Car  
2860 2870 2880 2020   
#Great War Heavy Field Artillery 
2290 2300 2310  
#SW Tank 
7600 7610 
#Great War Infantry Division  
1010  1020 1030 1040 1050 1060 
#Great War Cavalry Division  
13060 13070 13080 1310 1320 1330 1340 
#Early Mountain Division 
1160  1170 1180 1190 1200 1210 1220 1230 1240
#Interbellum Supply 
1910 1920 1930 1940 1950 1960
#Early Static Anti-Air Artillery 
2800 2450 21180 21190
#Basic Anti-Air Artillery Brigade 
2810 2820 2510  
#Manufactoring
5810 5820 
#Improved Construction Engineering 
5800 5080 

#Great War Destroyer 
3010 3020 3030 3040 
#Early Light Cruiser 
3110 3120 3130
#Short Range Submarine 
3610 3620 
#Naval Doctrines
8010 8050  
#Naval Infantry
#1560 
#Engineers
1830 1840 
#Torpedo & ASW 18
3720 3730 3736 3740 3750 3900
#Troopships
3810
#Medicine
5600 5610
#Land Doctrines WWI - Entente line
6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6540 6910
#Landdoctrine ww2 - none

#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010

} 
inventions = { 3000027 }
   diplomacy = 
   {  relation = {  tag = ENG value = 70  } 
     relation = {  tag = FRA value = -100  } 
     relation = {  tag = JAP value = 75  } 
     relation = {  tag = MAN value = 75  } 
    } 
   SpyInfo                = {  country = "SIA" NumberOfSpies = 5  } 
   headofstate            = {  type = 9 id = 290001  } 
   headofgovernment       = {  type = 9 id = 290002  } 
   foreignminister        = {  type = 9 id = 290003  } 
   armamentminister       = {  type = 9 id = 290004  } 
   ministerofsecurity     = {  type = 9 id = 290005  } 
   ministerofintelligence = {  type = 9 id = 290006  } 
   chiefofstaff           = {  type = 9 id = 290007  } 
   chiefofarmy            = {  type = 9 id = 290008  } 
   chiefofnavy            = {  type = 9 id = 290009  } 
   chiefofair             = {  type = 9 id = 290010  } 
   landunit = 
   {  location = 1424 
     name     = "Royal Thai Army" 
     id       = {  type = 23600 id = 1  } 
     Division = 
     {  id       = {  type = 23600 id = 2  } 
       name     = "1. Thai Infantry Div." 
       type     = infantry 
	   model = 7
       strength = 90 
      } 
     Division = 
     {  id       = {  type = 23600 id = 3  } 
       name     = "2. Thai Infantry Div." 
       type     = infantry 
	   model = 6
       strength = 70 
      } 
    } 
   landunit = 
   {  location = 1423 
     name     = "Royal Thai Police Force" 
     id       = {  type = 23600 id = 4  } 
     Division = 
     {  id       = {  type = 23600 id = 5  } 
       name     = "1. Royal Thai Police Div." 
       type     = garrison
		model = 3 
       strength = 30 
       extra    = police 
	   brigade_model = 1
      } 
    } 
   navalunit = 
   {  location = 1424 
     base     = 1424 
     name     = "Royal Thai Navy" 
     id       = {  type = 23600 id = 6  } 
     Division = 
     {  id    = {  type = 23600 id = 7  } 
       name  = "RTNS Sri Ayuthia" 
       type  = light_cruiser 
       model = 2 
      } 
     Division = 
     {  id    = {  type = 23600 id = 8  } 
       name  = "RTNS Dhonburi" 
       type  = light_cruiser 
       model = 2 
      } 
     Division = 
     {  id    = {  type = 23600 id = 10  } 
       name  = "Phra Ruang Flotille" 
       type  = destroyer 
       model = 2
      } 
    } 
   airunit = 
   {  location = 1424 
     base     = 1424 
     name     = "Royal Thai Airforce" 
     id       = {  type = 23600 id = 12  } 
     Division = 
     {  id       = {  type = 23600 id = 13  } 
       name     = "1. RTAF Fighter Group" 
       type     = interceptor 
       model    = 4 
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 23600 id = 14  } 
       name     = "1. RTAF Tactic Bomb Group" 
       type     = tactical_bomber 
       model    = 3
       strength = 44 
      } 
    } 
  } 
 
