 
 ############################## 
 # Country definition for TUR # 
 ############################## 
  
 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = TUR 
   # Resource Reserves 
energy                 = 1320
metal                  = 660
rare_materials         = 330
   oil                    = 500 
   supplies               = 500 
   money                  = 20 
   capital                = 1075 
   manpower               = 38 
      
   transports             = 135 
   escorts                = 10 
   ai_settings = { flags = {   legitIndie = 1 } }   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 6 
     political_left    = 5
     freedom           = 4 
     free_market       = 6 
     professional_army = 5 
     defense_lobby     = 6 
     interventionism   = 3 
    } 
    ownedprovinces =      {
	385 #Edirne=>Istanbul
 	384 #Gelibolu=>Istanbul
 	409 #Istanbul
 	1076 #Izmit
 	1078 #Bursa
 	1077 #Izmir
 	1079 #Denizli=>Antalya
	1071 #Eskisehir=>Afyonkarahisar
 	1068 #Zuguldak=>Karabük
 	1065 #Karabuk
 	1075 #Ankara
 	1074 #Konya
 	1057 #Antalya
 	1058 #Tarsus=>Antalya
 	1055 #Adana=>Mersin
 	1073 #Kayseri
 	1072 #Kirikkale=>Sivas
 	1066 #Samsun
 	1059 #Sivas
 	1061 #Maltya=>Elazig
 	1056 #Gaziantep
  	1060 #Diyarbakir=>Batman
 	1064 #Elazig=>Erzurum
 	1067 #Trebizond=>Trabzon
 	386 #Kars
 	1063 #Erzurum=>Van
 	1062 #Hakkari=>Van
	 }
    controlledprovinces = {
	385 #Edirne=>Istanbul
 	384 #Gelibolu=>Istanbul
 	409 #Istanbul
 	1076 #Izmit
 	1078 #Bursa
 	1077 #Izmir
 	1079 #Denizli=>Antalya
	1071 #Eskisehir=>Afyonkarahisar
 	1068 #Zuguldak=>Karabük
 	1065 #Karabuk
 	1075 #Ankara
 	1074 #Konya
 	1057 #Antalya
 	1058 #Tarsus=>Antalya
 	1055 #Adana=>Gaziantep/Kayseri
 	1073 #Kayseri
 	1072 #Kirikkale=>Sivas
 	1066 #Samsun
 	1059 #Sivas
 	1061 #Maltya=>Elazig
 	1056 #Gaziantep
  	1060 #Diyarbakir=>Batman
 	1064 #Elazig=>Erzurum
 	1067 #Trebizond=>Trabzon
 	386 #Kars
 	1063 #Erzurum=>Van
 	1062 #Hakkari=>Van 
	  }
claimedprovinces = {
#External claims

#Iraq
	1033 #El Hillah
	1034 #Baghdad
	1035 #Kut
	1030 #Karbala
	1037 #An Nasiriyyah
	1028 #Al Amarah
	1032 #Basrah
	1031 #An Najaf
	1041

#Syria
	1014
	1015
	1016
	1017
	1018
	1019
	1020

#Transjordan
	1022
	1023
	1024
	1025
	1026
	1172
	1008
	1009
	1010
	1011
	1013

#KSA
	1048
	1049
	1050

#Egypt
	900
  	795 #Aswan#
	794 #Asyut#
	793 #Minian#
 	798 #El Kharga#
 	802 #El Qasr#
	801 #El Farafra#
	792 #El Faiyum#
	788 #Hakim#
	787 #Kairo#   
	800 #Bir Nahid#
	799 #Moghara#
	779 #Siwah#
	789 #Alexandria
	783 #El Alamein
	784 #Fuqa
	785 #Matruh
	780 #Sidi Barrani
	781 #As Sollum
	778 #Bir Fuda
	782 #Bir Baylih
	791 #Pur Said
	786 #Dimyat
	796 #El Ghardaqah
	797 #El Uqsur 
	790 #Tanta
	1004
	1005
	1006
	1007

	#North Sudan
	804
	803
	813
	814
	805
	811
	810
	812
	806

	#Libya
	762
	759
	750
	751
	752
	753
	754
	755
	756
	757
	758
	776

	761 #Benghazi
	768 #Darnah
	760 #Masus
	766 #El Mukhayla
	765 #Tobruk
	771 #Al Bardia
	769 #Bir Hakeim
	770 #El Jaghbub
	773 #Jalu
	774 #Al Jawf
	777 #Ayn Ath Thalab
	763 #Qaminis
	775 #Wadi al Hamim
	764 #Al Bayda
	767 #Gazala
	772 #Bir al Ghabi

#Albania
	359
	360
	361
	362	

#Bulgaria
	370
	325

	324
	320

#Greece
#	363
	364
	365
	366
	367
	369

	380
	382
	383

#Yugoslavia
	328
	329
	333
	334
	335

	353
	354
	355
	356
	357
	358

#Mosul
	1015
	1027
	1029
	1036

#Cyprus
	388

#Rhodos
	379
	378

#Armenia
	711

#North Azerbaijan
	712
	713
	714	

#South Azerbaijan
	1081
	1083

#South Azerbaijan
	1082

#Moldova
	306

#Crimean Tartars
	638
	641

	637
	639
	640

#Internal claims

#East Turkey
	1060
	1062
	1063
	1064
	386

}

    nationalprovinces =   {
#Mosul
	1029
	1036

#Syria
	1054
	1021

#Bulgaria
	307
	317
	326
	319
	
#Greece
	363
	
#Istanbul area
	384
	385

 	409 #Istanbul
 	1076 #Izmit
 	1078 #Bursa
 	1077 #Izmir
 	1079 #Denizli=>Antalya
	1071 #Eskisehir=>Afyonkarahisar
 	1068 #Zuguldak=>Karabük
 	1065 #Karabuk
 	1075 #Ankara
 	1074 #Konya
 	1057 #Antalya
 	1058 #Tarsus=>Antalya
 	1055 #Adana=>Gaziantep/Kayseri
 	1073 #Kayseri
 	1072 #Kirikkale=>Sivas
 	1066 #Samsun
 	1059 #Sivas
 	1061 #Maltya=>Elazig
 	1056 #Gaziantep
 	1067 #Trebizond=>Trabzon

	#Zypern
	387 #Gazimagusa

	}
 
   # Semi-Major Tech '36 
   # Group C 1936 techs 
   # ###################### 
   techapps = {
#Early Fighter  
4500 4510 4520 4530 4540 4550 4010 4020
#Interwar Bomber 
4600 4610 4620 4630 4120
#Multirole fighter
4300 4310 4320 4330
#ww1 strategic bomber
4800 4810 4820
#ww1 navalbomber
4700 4710
#Engineers
1830 1840  
#Basic Armoured Car 
2860 2870 2880 2020
#Tankette
7600 7610 2620 2010 2630 2640
#Great War Heavy Field Artillery 
2290 2300 2310 
#Early Static Anti-Air Artillery 
2800 2450 21180 21190
#Basic Anti-Air Artillery Brigade 
2810 2820 2510
#Great War Infantry Division  
1010  1020 1030 1040 1050 1060 1070
#Great War Cavalry Division  
13060 13070 13080 1310 1320 1330 1340 
#Early Mountain Division 
1160  1170 1180 1190 1200 1210 1220 1230 1240
#Interbellum Supply 
1910 1920 1930 1940 1950 1960
#Great War Hospital System
 14000 14010 14020
#Modern Agriculture  
5700 5710 5010
#Manufactoring
5810 5820 5050 5830
#Improved Construction Engineering
5800 5080 5090 
#Great War Battlecruiser  
3310 3320 3330
#Improved Destroyer 
3010 3020 3030 3040 3050 3060
#Early Light Cruiser 
3110 3120 3130
#Early Heavy Cruiser
 3210 3220 3230
#Short Range Submarine
 3610 3620
 #Torpedo & ASW 18
3720 3730 3736 3740 3750 3900
#Troopships
3810
#Medicine
5600 5610 5620
#Improved Great War Hospital System
14000 14010
 
 
 
# Land doctrines WWI - Central Powers line: germany, turkey, austr, hun, bul, russia
6500 6510 6530 6590 6600 6610 6680 6620 6690 6700 6650 6710 6670 6550 6910
# Land Doctrines WWII - Manpower Focus
6570 6300
#Naval Doctrines
 8010  8020  8040  8050 

 #Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010
 
 
} 
inventions = { 3000027 }
   diplomacy = 
   {  relation = {  tag = AFG value = 50  } 
     relation = {  tag = BUL value = 75  } 
     relation = {  tag = ENG value = 75  } 
     relation = {  tag = FRA value = 50  } 
     relation = {  tag = GER value = 10  } 
     relation = 
     {  tag        = GRE 
       value      = 100 
       guaranteed = {  day = 30 month = december year = 1934  } 
      } 
     relation = {  tag = ITA value = 1  } 
     relation = {  tag = OMN value = 35  } 
     relation = {  tag = PER value = -50  } 
     relation = 
     {  tag        = ROM 
       value      = 100 
       guaranteed = {  day = 30 month = december year = 1934  } 
      } 
     relation = {  tag = SAU value = 50  } 
     relation = {  tag = SOV value = 100  } 
     relation = {  tag = YEM value = 35  } 
     relation = 
     {  tag        = YUG 
       value      = 100 
       guaranteed = {  day = 30 month = december year = 1934  } 
      } 
    } 
   SpyInfo                = {  country = "TUR" NumberOfSpies = 7  } 
   headofstate            = {  type = 9 id = 45001  } 
   headofgovernment       = {  type = 9 id = 45002  } 
   foreignminister        = {  type = 9 id = 45003  } 
   armamentminister       = {  type = 9 id = 45004  } 
   ministerofsecurity     = {  type = 9 id = 45005  } 
   ministerofintelligence = {  type = 9 id = 45006  } 
   chiefofstaff           = {  type = 9 id = 45007  } 
   chiefofarmy            = {  type = 9 id = 45008  } 
   chiefofnavy            = {  type = 9 id = 45009  } 
   chiefofair             = {  type = 9 id = 45010  } 
   landunit = 
   {  location = 1075 
     name     = "I. Topluluk" 
     id       = {  type = 11700 id = 8  } 
     Division = 
     {  id           = {  type = 11700 id = 9  } 
       type         = infantry 
	   model = 6
       strength     = 100 
       organisation = 30 
       name         = "1. Piyade Dagitim" 
      } 
     Division = 
     {  id           = {  type = 11700 id = 100  } 
       type         = infantry 
	   model = 6
       strength     = 50 
       organisation = 30 
       name         = "2. Piyade Dagitim" 
      } 
     Division = 
     {  id           = {  type = 11700 id = 10  } 
       type         = infantry 
	   model = 7
       extra        = artillery 
	   brigade_model = 6
       strength     = 100 
       organisation = 30 
       name         = "3. Piyade Dagitim" 
      } 
     Division = 
     {  id           = {  type = 11700 id = 101  } 
       type         = infantry 
	   model = 6
       strength     = 50 
       organisation = 30 
       name         = "4. Piyade Dagitim" 
      } 
    } 
   landunit = 
   {  location = 409 
     name     = "II. Topluluk" 
     id       = {  type = 11700 id = 11  } 
     Division = 
     {  id           = {  type = 11700 id = 12  } 
       type         = infantry 
	   model = 7
       extra        = anti_air 
	   brigade_model = 1
       strength     = 50 
       organisation = 30 
       name         = "5. Piyade Dagitim" 
      } 
     Division = 
     {  id           = {  type = 11700 id = 102  } 
       type         = infantry 
	   model = 6
       strength     = 50 
       organisation = 30 
       name         = "6. Piyade Dagitim" 
      } 
    } 
   landunit = 
   {  location = 1078 
     name     = "III. Topluluk" 
     id       = {  type = 11700 id = 13  } 
     Division = 
     {  id           = {  type = 11700 id = 14  } 
       type         = infantry 
	   model = 7
       strength     = 100 
       organisation = 30 
       name         = "7. Piyade Dagitim" 
      } 
     Division = 
     {  id           = {  type = 11700 id = 103  } 
       type         = infantry 
	   model = 6
       strength     = 50 
       organisation = 30 
       name         = "8. Piyade Dagitim" 
      } 
    } 
   landunit = 
   {  location = 1059 
     name     = "IV. Topluluk" 
     id       = {  type = 11700 id = 15  } 
     Division = 
     {  id           = {  type = 11700 id = 16  } 
       type         = infantry 
	   model = 7
       strength     = 100 
       organisation = 30 
       name         = "9. Piyade Dagitim" 
      } 
     Division = 
     {  id           = {  type = 11700 id = 104  } 
       type         = infantry 
	   model = 6
       strength     = 50 
       organisation = 30 
       name         = "10. Piyade Dagitim" 
      } 
    } 
   landunit = 
   {  location = 1067 
     name     = "V. Topluluk" 
     id       = {  type = 11700 id = 17  } 
     Division = 
     {  id           = {  type = 11700 id = 18  } 
       type         = infantry 
	   model = 6
       strength     = 100 
       organisation = 30 
       name         = "11. Piyade Dagitim" 
      }
     Division = 
     {  id           = {  type = 11700 id = 105  } 
       type         = infantry 
	   model = 6
       strength     = 50 
       organisation = 30 
       name         = "12. Piyade Dagitim" 
      } 
    } 
   landunit = 
   {  location = 1062 
     name     = "VI. Topluluk" 
     id       = {  type = 11700 id = 19  } 
     Division = 
     {  id           = {  type = 11700 id = 20  } 
       type         = infantry 
	   model = 7
       extra        = anti_air 
	   brigade_model = 1
       strength     = 100 
       organisation = 30 
       name         = "13. Piyade Dagitim" 
      } 
     Division = 
     {  id           = {  type = 11700 id = 106  } 
       type         = infantry 
	   model = 6
       strength     = 50 
       organisation = 30 
       name         = "14. Piyade Dagitim" 
      } 
    } 
   landunit = 
   {  location = 1061 
     name     = "VII. Topluluk" 
     id       = {  type = 11700 id = 21  } 
     Division = 
     {  id           = {  type = 11700 id = 22  } 
       type         = infantry 
	   model = 6
       strength     = 100 
       organisation = 30 
       name         = "15. Piyade Dagitim" 
      } 
     Division = 
     {  id           = {  type = 11700 id = 107  } 
       type         = infantry 
	   model = 6
       strength     = 50 
       organisation = 30 
       name         = "16. Piyade Dagitim" 
      } 
    } 
   landunit = 
   {  location = 1060 
     name     = "VIII. Topluluk" 
     id       = {  type = 11700 id = 23  } 
     Division = 
     {  id           = {  type = 11700 id = 24  } 
       type         = infantry 
	   model = 6
       strength     = 100 
       organisation = 30 
       name         = "17. Piyade Dagitim" 
      } 
     Division = 
     {  id           = {  type = 11700 id = 108  } 
       type         = infantry 
	   model = 6
       strength     = 50 
       organisation = 30 
       name         = "18. Piyade Dagitim" 
      } 
    } 
   landunit = 
   {  location = 1063 
     name     = "IX. Topluluk" 
     id       = {  type = 11700 id = 25  } 
     Division = 
     {  id           = {  type = 11700 id = 26  } 
       type         = infantry 
	   model = 7
       strength     = 100 
       organisation = 30 
       name         = "19. Piyade Dagitim" 
      } 
     Division = 
     {  id           = {  type = 11700 id = 109  } 
       type         = infantry 
	   model = 6
       strength     = 50 
       organisation = 30 
       name         = "20. Piyade Dagitim" 
      } 
    } 
   landunit = 
   {  location = 1064 
     name     = "X. Topluluk" 
     id       = {  type = 11700 id = 27  } 
     Division = 
     {  id           = {  type = 11700 id = 28  } 
       type         = bergsjaeger 
	   model = 6
       extra        = artillery 
	   brigade_model = 5
       strength     = 80 
       organisation = 30 
       name         = "1. Dagci Tugay" 
      } 
    } 
   landunit = 
   {  location = 1074 
     name     = "Türkce Süvari Topluluk" 
     id       = {  type = 11700 id = 29  } 
     Division = 
     {  id           = {  type = 11700 id = 30  } 
       type         = cavalry 
	   model = 7
       extra        = artillery 
	   brigade_model = 6
       strength     = 100 
       organisation = 30 
       name         = "1. Süvari Dagitim" 
      } 
     Division = 
     {  id           = {  type = 11700 id = 31  } 
       type         = cavalry
		model = 7	   
       strength     = 100 
       organisation = 30 
       name         = "3. Süvari Dagitim" 
      } 
     Division = 
     {  id           = {  type = 11700 id = 32  } 
       type         = cavalry
		model = 7
       strength     = 50 
       organisation = 30 
       name         = "5. Yedek Süvari Dagitim" 
      } 
    } 
   # #####Turkey `36 ###### 
	navalunit = { 
		id = { type = 11700 id = 1 } 
		name = "Türkce Deniz Filosu" 
		location = 1076 
		base = 1076 
		division = { 
			id = { type = 11700 id = 99 } 
			name = "Reschid Pasha Kücük Filotilla" 
			type = transport 
			} 
		division = { 
			id = { type = 11700 id = 7 } 
			name = "1. Filotilla Torpido Ve Denizalti" 
			type = destroyer 
			model = 3 
			} 
		}  
	navalunit = { 
		id = { type = 11700 id = 2205 } 
		name = "1. Türk Dz. Kuvvetleri Filosu" 
		location = 1076 
		base = 1076 
		division = { 
			id = { type = 11700 id = 3 } 
			name = "TDT Yavuz" 
			type = battlecruiser 
			model = 1 
			} 
		division = { 
			id = { type = 11700 id = 5 } 
			name = "TDT Medjidieh" 
			type = light_cruiser 
			model = 3 
			} 
		division = { 
			id = { type = 11700 id = 4 } 
			name = "TDT Hamidieh" 
			type = light_cruiser 
			model = 3 
			} 
		} 
	navalunit = { 
		id = { type = 11700 id = 2434 } 
		name = "2. Türk Dz. Kuvvetleri Filosu" 
		location = 1076 
		base = 1076 
		division = { 
			id = { type = 11700 id = 6 } 
			name = "1. Filotilla Denizalti Kücük" 
			type = submarine 
			model = 2 
			} 
		} 
   airunit = 
   {  location = 1075 
     base     = 1075 
     name     = "I. Türkce Hava Topluluk" 
     id       = {  type = 11700 id = 33  } 
     Division = 
     {  id           = {  type = 25635 id = 34  } 
       type         = interceptor 
       model        = 5
       strength     = 48 
       organisation = 30 
       name         = "1. Avci Ucagi Grup" 
      } 
     Division = 
     {  id           = {  type = 25635 id = 35  } 
       type         = tactical_bomber 
       model        = 4 
       strength     = 52 
       organisation = 30 
       name         = "1. Taktik Bombardiman Ucagi Grup" 
      } 
    } 
  } 
 
