 
 ############################## 
 # Country definition for ENG # 
 ############################## 
 
 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = ENG 
   capital                = 29 
   flag_ext 			= _nazi
    
   
   manpower               = 520 
     dissent = 1
energy                 = 8040
metal                  = 4020
rare_materials         = 2010
   oil                    = 500 
   supplies               = 500 
   money                  = 70 
   transports             = 1600 
   escorts                = 150 
     research_mod = 0.75
   diplomacy = 
   {  relation = 
     {  tag        = AFG 
       value      = -75 
       guaranteed = {  day = 11 month = february year = 1934  } 
      } 
     relation = {  tag = ARG value = 75  } 
     relation = {  tag = AST value = 200  } # was access = yes  
     relation = 
     {  tag        = AUS 
       value      = 75 
       guaranteed = {  day = 27 month = september year = 1934  } 
      } 
     relation = {  tag = BEL value = 150  } 
     relation = {  tag = BHU value = 200 access = yes  } 
     relation = {  tag = BUL value = 20  } 
     relation = {  tag = CAN value = 200  } # was access = yes 
     relation = {  tag = CUB value = 30  } 
     relation = {  tag = CZE value = 125  } 
     relation = 
     {  tag        = DEN 
       value      = 100 
       guaranteed = {  day = 30 month = august year = 1934  } 
      } 
     relation = {  tag = EGY value = 200  } 
     relation = {  tag = EST value = 65  } 
     relation = {  tag = ETH value = 50  } 
     relation = {  tag = FIN value = 85  } 
     relation = {  tag = FRA value = 150  } 
     relation = {  tag = GER value = 150  } 
     relation = 
     {  tag        = GRE 
       value      = 50 
       guaranteed = {  day = 11 month = february year = 1934  } 
      } 
     relation = {  tag = GUA value = 50  } 
     relation = {  tag = HOL value = 150  } 
     relation = {  tag = HON value = 50  } 
     relation = {  tag = HUN value = -50  } 
     relation = 
     {  tag        = IRE 
       value      = 25 
       guaranteed = {  day = 11 month = february year = 1934  } 
      } 
     relation = 
     {  tag        = IRQ 
       value      = 100 
       access     = yes 
       guaranteed = {  day = 11 month = february year = 1934  } 
      } 
     relation = {  tag = ITA value = -50  } 
     relation = {  tag = JAP value = -25  } 
     relation = {  tag = LAT value = 65  } 
     relation = {  tag = LIT value = 65  } 
     relation = {  tag = MEX value = 50  } 
     relation = {  tag = NEP value = 200 access = yes  } 
     relation = 
     {  tag        = NOR 
       value      = 90 
       guaranteed = {  day = 30 month = august year = 1934  } 
      } 
     relation = {  tag = NZL value = 200  } # was access = yes 
     relation = 
     {  tag        = OMN 
       value      = 150 
       access     = yes 
       guaranteed = {  day = 11 month = february year = 1934  } 
      } 
     relation = 
     {  tag        = PER 
       value      = 25 
       guaranteed = {  day = 11 month = february year = 1934  } 
      } 
     relation = {  tag = POL value = 50  } 
     relation = 
     {  tag        = POR 
       value      = 100 
       guaranteed = {  day = 30 month = december year = 1935  } 
      } 
     relation = {  tag = ROM value = 50  } 
     relation = {  tag = SAF value = 200  } # was access = yes 
     relation = 
     {  tag        = SAU 
       value      = 100 
       guaranteed = {  day = 11 month = february year = 1934  } 
      } 
     relation = 
     {  tag        = SCH 
       value      = 50 
       guaranteed = {  day = 16 month = may year = 1935  } 
      } 
     relation = {  tag = SIA value = 70  } 
     relation = {  tag = SPR value = -10  } 
     relation = {  tag = SOV value = -25  } 
     relation = 
     {  tag        = SWE 
       value      = 80 
       guaranteed = {  day = 30 month = august year = 1934  } 
      } 
     relation = 
     {  tag        = TUR 
       value      = 75 
       guaranteed = {  day = 11 month = february year = 1934  } 
      } 
     relation = {  tag = USA value = 150  } 
     relation = {  tag = VEN value = -10  } 
     relation = 
     {  tag        = YEM 
       value      = 150 
       access     = yes 
       guaranteed = {  day = 11 month = february year = 1934  } 
      } 
    } 
   SpyInfo                = {  country = "ENG" NumberOfSpies = 12  } 
    
claimedprovinces = {
#External claims

#Burma
 1406 # Haka
 1407 # Indaw
 1408 # Myitkyina
 1409 # Lashio
 1410 # Mandalay
 1411 # Pakokdu
 1412 # Taunggyi
 1413 # Kengtung
 1414 # Putao
 1415 # Rangoon
 1416 # Moulmein
 1417 # Pegu
 1418 # Tavoy
 1419 # Bassein
 1420 # Akyab
 1421 # Port Blair Islands/To UK!
 1439 # Gauhati
 1440 # Aijal
 1441 # Dibrugarh
 1442 # Imphal
 1443 # Dhubri
 1445 # Dhaka
 1450 # Cattagram
 1455 # Itanagar
 1458 # Mipi

#India  
 1444 # Khulna
 1446 # Siliguri
 1447 # Calcutta
 1448 # Kharagpur
 1449 # Rajshahi
 1451 # Dehradun
 1452 # Gangtok
 1453 # Dharmasala
 1454 # Simla
 1459 # Dehl
 1460 # Merath
 1461 # Lucknow
 1462 # Muzaffarpur
 1463 # Chandigarh
 1464 # Bareli
 1465 # Patna
 1466 # Arrah
 1467 # Gorakhpur
 1468 # Cawnpore
 1469 # Raigarh
 1470 # Balangir
 1471 # Bhubanesbar
 1472 # Jamshedpur
 1473 # Kataka
 1474 # Jeypore
 1475 # Bastar
 1476 # Ranchi
 1477 # Raipur
 1478 # Burhanpur
 1479 # Jubbulpore
 1480 # Bhopal
 1481 # Indhur
 1482 # Amaravati
 1483 # Rewa
 1484 # Chhindwara
 1485 # Nagpur
 1486 # Aurangabad
 1487 # Hyderabad 
 1488 # Warangal
 1489 # 1489
 1490 # Raichur
 1491 # Nalgonda
 1492 # Adilabad
 1493 # Vizagapatam
 1494 # Nellore
 1495 # Trivandrum
 1496 # Gunturu
 1497 # Cochin
 1498 # Bezawada
 1499 # Trichinopoly
 1500 # Madras
 1501 # Anantapur
 1502 # Bangalore
 1503 # Mangalore
 1504 # Madurai
 1505 # Coimbatore
 1506 # Salem
 1507 # Mysore
 1508 # Solapur
 1512 # Kolhapur
 1513 # Panjim #### Portuguese Colony
 1514 # Nasik
 1515 # Hubli
 1516 # Poona
 1517 # Bombay  #### British Harbour/To UK!
 1518 # Ahmedabad
 1519 # Mandvi
 1520 # Surat
 1521 # Baroda
 1522 # Rajkot
 1523 # Gwalior
 1524 # Jaypur
 1525 # Jodhpur
 1526 # Udaypur
 1527 # Bikaner
 1528 # Kotah
 1530 # Lahore
 1531 # Ludhiana
 1532 # Nawabshah
 1535 # Amritsar
 1536 # Bahawalnagar



#Ceylon
  1510 #Kandy
  1511 #Colombo
  1509 #Mahawilachchiya


#Pakistan 
 1278 # Sumdo
 1529 # Quetta
 1533 # Karachi
 1534 # Rawalpindi
 1537 # Peshawar
 1538 # Gwadar
 1539 # Muzaffarabad
 1540 # Srinagar


#New Zealand
	1720
	1718
	1719
	1721
	1722
	1723

#USAF
	872
	873
	874
	875
	876
	877
	878
	879
	880
	881
	882
	883
	884
	886

#Australia
	1697	
	1716	
	1698	
	1695	
	1688	
	1692	
	1689	
	1690	
	1694	
	1691	
	1703	
	1693	
	1711	
   	1712	
	1715	
	1704	
	1705	
	1706	
	1717	
	1707	
	1710	
	1708	
	1709	
	1713	
	1701	
	1699	
	1714	
   	1700	
	1702	
	1696	

#Canada
	2089
	2092
	2090
	2093
	2095
	2103
	2104
	2105
	2102
	2099
	2091
	2096
	2097
	2098
	2094
	2100
	2101
	2106
	2107
	2115
	2108
	2109
	2110
	2129
	2113
	2114
	2148
	2149
	2112
	2127
	2130
	2111
	2116
	2123
	2122
	2121
	2120
	2125
	2124
	2117
	2118
	2119
	2128
	2135
	2136
	2138
	2137
	2132
	2131
	2134
	2126
	2133

#New England
	1784
	1785
	1786
	1787
	1788
	1789
	1790
	1791
	1792
	1796
	1800

#US East Coast
	1794
	1793
	1799
	1795
	1797
	1798
	1801
	1802
	1803
	1804
	1805
	1806
	1807
	1808

#CSA
	1809
	1810
	1811
	1814
	1816
	1817
	1818
	1819
	1820
	1827
	1828
	1823
	1831
	1833
	1836
	1909
	1910
	1912
	1917
	1918
	1919
	1920
	1921
	1924
	1925
	1928
	1941
	1942
	1943
	1945
	1948
	1949
	1950
	1951
	1952
	1955
	1953
	1956
	1959
	1962
	1964
	1812
	1813
	1815
	1957
	1961
	1963
	1958
	1960
	1954
	1947
	1946
	1936
	1935
	1939
	1940
	1915
	1933
	1938
	1930
	1933
	1929
	1911
	1913
	1916
	1944

#Mormonland
	1869
	1870
	1894
	1895
	1896
	1897
	1898
	1899

#West coast
	1861
	1863
	1865
	1871
	1872
	1873
	1874
	1875
	1876
	1877
	1878
	1879
	1880
	1881
	1882
	1884
	1885
	1889
	1890

	1893
	1894
	1895

#Germany - Hannover
	146
	147
	148
	149

#Netherlands
#	125 #Rotterdam
#	122 #Amsterdam
#	123 #Middelburg=>Rotterdam(split)
#	118 #Eindhoven
#	119 #Arnheim=>Utrecht/Arnheim(merge)
#	124 #Groningen=>Groningen/Leeuwarden(merge)
#	120 #Nijmegen=>Eindhoven(split)
#	121 #Maastricht=>Eindhoven(split)

#Belgium
#	108
#	109
#	110
#	111
#	112
#	113
#	114
#	115
#	116
#	117

#Internal claims

#Scotland
	4
	5
	6
	7
	8
	9
	10
	11
	12

#Ireland
	30
	31
	32
	33
	34
	35
	36

#Wales
	21
	22

#India
   1517 #Bombay ### As Harbour for RN in India
	
   900 #Suez#

   429 #Malta#
   348 #Gibraltar#

### Middle East
   1013 #Akko#
   1022 #Amman#
   1172 #Jerusalem#
   1011 #Haifa#
   1009 #Gaza#
   1010 #Eilat#
   1024 #Az Zarqa#
   1025 #Ma'an#
   1026 #Al Kerak#
   1023 #Irbid#
   1008 #Tel Aviv#

### Cyprus
   387 #Gazimagusa#
   388 #Lefkosia#

### Aden, Arabia
   1053 #Aden#
   1051 #El Mukalla#
   1041 #Kuwait#
   1038 #Doha#
   1039 #Abu Dhabi#
   
### Caribean Sea
   1773 #The Bermudas#
   1760 #Saint Kitts#
   1772 #Turks and Caicos#
   1771 #The Bahamas#
   1782 #Jamaica#
   1774 #Cayman Islands#
   1766 #British Virgin Island#
   1759 #Atigua & Barbuda#
   1757 #Anguilla#
   1754 #Montserrat#
   1753 #Dominica#
   1770 #St Lucia#
   1755 #St Vincent#
   1763 #Saint George's#
   1764 #Barbados#
   1769 #Tobago#
   1758 #Trinidad#
   1998 #Bartica#
   1997 #Georgetown#
   2086 #Belize City#

### Canada
   993 #Ascension Island#
   896 #Saint Helena#

### Indik
   998 #Port Victoria#
   1611 #Male#
   1612 #Kavaratti#
   997 #Port Louis#
   840 #Suqutra#
   1421 #Port Bleyar=>Andaman Islands/Nicobar Islands#

### Africa
   832 #Hargeysa#
   804 #Dunqula#
   803 #Wadi Halfa#
   813 #Bur Sudan#
   814 #Kassala#
   811 #El Qadarif#
   810 #Khartoum#
   812 #Malakal#
   806 #El Ubayyid#
   808 #Nayala#
   809 #Waw#
   805 #Umm Durman#
   807 #Juba#
   845 #Gulu#
   844 #Kampala#
   843 #Nakuru#
   839 #Garissa#
   842 #Mombasa#
   841 #Nairobi#
   848 #Mwanza#
   851 #Tabora#
   849 #Mbeya#
   850 #Dar es Salaam#
   852 #Zanzibar
   864 #Blantyre#
   865 #Chipata#
   861 #Kasama#
   863 #Lusaka#
   862 #Chingola#
   860 #Kalabo#
   859 #Livingstone#
   867 #Salisbury#
   866 #Bulawayo#
   868 #Hwange#
   869 #Francistown#
   871 #Maun#
   870 #Gaberones#
   956 #Accra#
   954 #Kumasi#
   952 #Tamale#
   955 #Ho#
   953 #Wa#
   938 #Maiduguri#
   940 #Kano#
   937 #Sokoto#
   939 #Kaduna#
   941 #Abuja#
   936 #Yola#
   931 #Katsina-Ala#
   930 #Port Harcourt#
   933 #Buea#
   932 #Ibadan#
   934 #Oshogbo#
   929 #Lagos#
   935 #Benin City#
   964 #Freetown#
   979 #Banjul#

### Ceylon
   1510 #Kandy#
   1511 #Colombo#
   1509 #Mahawilachchiya#

### Malaysia
   1433 #Kota Bahru#
   1434 #Alor Setar#
   1435 #Ipoh=>Alor Star#
   1436 #Kuantan#
   1437 #Jojor Bahru#
   1438 #Kuala Lumpur#
   1432 #Singapore#

   1371 #Hong Kong#

### Sarawak
   1624 #Kuching#
   1625 #Bandar Seri Begawan#
   1626 #Jesselton

### Salomonen
   1588 #Saint Isabel#
   1591 #Malaita#
   1589 #New Georgia#
   1592 #Nendo#
   1590 #Guadal Landingzone#
   1593 #Guadalcanal#

### Pazifik
   1682 #Nauru#
   1678 #Makin#
   1680 #Tarawa#
   1679 #Abemama#
   1728 #Suva#
   1687 #Funafuti#
   1749 #Nuku'alofa#
   1729 #Labasa#
   1746 #Christmas Island#
   1750 #Kanton#

### Südafrika
   874 #Maseru
   877 #Mbabane


   1613 #West Island
   1614 #Christmas

}

   # GREAT BRITAIN 
   nationalprovinces = {  
   29 #London#
   13 #Sunderland#
   14 #Carlisle#
   15 #Hull#
   18 #Sheffield#
   17 #Manchester#
   16 #Lincoln#
   24 #Birmingham#
   25 #Norwich#
   28 #Oxford#
   19 #Bristol#
   26 #Dover#
   27 #Portsmouth#
   20 #Exeter#
	#Cornwall
	23 #Plymouth#
   }
     
   ownedprovinces = { 
   4 #Stornoway
   5 #Scapa Flow
   6 #Inverness
   7 #Aberdeen
   8 #Fort William
   9 #Lerwick
   11 #Glasgow
   12 #Edinburgh
   10 #Dumfries
   13 #Sunderland
   14 #Carisle
   15 #Hull
   16 #Lincoln
   17 #Manchaster
   18 #Sheffield
   19 #Bristol
   20 #Exeter
   21 #Caernarfon
   22 #Cardiff
   24 #Birmingham
   28 #Oxford
   25 #Norwich
   29 #London
   26 #Dover
   27 #Portsmouth
   23 #Plymouth
   #Irland
   36 #Belfast
   35 #Londonderry

   1517 #Bombay ### As Harbour for RN in India

   900 #Suez#

   429 #Malta#
   348 #Gibraltar#

### Middle East
   1013 #Akko#
   1022 #Amman#
   1172 #Jerusalem#
   1011 #Haifa#
   1009 #Gaza#
   1010 #Eilat#
   1024 #Az Zarqa#
   1025 #Ma'an#
   1026 #Al Kerak#
   1023 #Irbid#
   1008 #Tel Aviv#

### Cyprus
   387 #Gazimagusa#
   388 #Lefkosia#

### Aden, Arabia
   1053 #Aden#
   1051 #El Mukalla#
   1041 #Kuwait#
   1038 #Doha#
   1039 #Abu Dhabi#
   
### Caribean Sea
   1773 #The Bermudas#
   1760 #Saint Kitts#
   1772 #Turks and Caicos#
   1771 #The Bahamas#
   1782 #Jamaica#
   1774 #Cayman Islands#
   1766 #British Virgin Island#
   1759 #Atigua & Barbuda#
   1757 #Anguilla#
   1754 #Montserrat#
   1753 #Dominica#
   1770 #St Lucia#
   1755 #St Vincent#
   1763 #Saint George's#
   1764 #Barbados#
   1769 #Tobago#
   1758 #Trinidad#
   1998 #Bartica#
   1997 #Georgetown#
   2086 #Belize City#

   2045 #Falkland Islands#

### Canada
   2136 #Goose Bay#
   2138 #Nain#
   2137 #St John's#

   993 #Ascension Island#
   896 #Saint Helena#

### Indik
   998 #Port Victoria#
   1611 #Male#
   1612 #Kavaratti#
   997 #Port Louis#
   840 #Suqutra#
   1421 #Port Bleyar=>Andaman Islands/Nicobar Islands#

### Africa
   832 #Hargeysa#
   804 #Dunqula#
   803 #Wadi Halfa#
   813 #Bur Sudan#
   814 #Kassala#
   811 #El Qadarif#
   810 #Khartoum#
   812 #Malakal#
   806 #El Ubayyid#
   808 #Nayala#
   809 #Waw#
   805 #Umm Durman#
   807 #Juba#
   845 #Gulu#
   844 #Kampala#
   843 #Nakuru#
   839 #Garissa#
   842 #Mombasa#
   841 #Nairobi#
   848 #Mwanza#
   851 #Tabora#
   849 #Mbeya#
   850 #Dar es Salaam#
   852 #Zanzibar
   864 #Blantyre#
   865 #Chipata#
   861 #Kasama#
   863 #Lusaka#
   862 #Chingola#
   860 #Kalabo#
   859 #Livingstone#
   867 #Salisbury#
   866 #Bulawayo#
   868 #Hwange#
   869 #Francistown#
   871 #Maun#
   870 #Gaberones#
   956 #Accra#
   954 #Kumasi#
   952 #Tamale#
   955 #Ho#
   953 #Wa#
   938 #Maiduguri#
   940 #Kano#
   937 #Sokoto#
   939 #Kaduna#
   941 #Abuja#
   936 #Yola#
   931 #Katsina-Ala#
   930 #Port Harcourt#
   933 #Buea#
   932 #Ibadan#
   934 #Oshogbo#
   929 #Lagos#
   935 #Benin City#
   964 #Freetown#
   979 #Banjul#

### Ceylon
   1510 #Kandy#
   1511 #Colombo#
   1509 #Mahawilachchiya#

### Malaysia
   1433 #Kota Bahru#
   1434 #Alor Setar#
   1435 #Ipoh=>Alor Star#
   1436 #Kuantan#
   1437 #Jojor Bahru#
   1438 #Kuala Lumpur#
   1432 #Singapore#

   1371 #Hong Kong#

### Sarawak
   1624 #Kuching#
   1625 #Bandar Seri Begawan#
   1626 #Jesselton

### Salomonen
   1588 #Saint Isabel#
   1591 #Malaita#
   1589 #New Georgia#
   1592 #Nendo#
   1590 #Guadal Landingzone#
   1593 #Guadalcanal#

### Pazifik
   1682 #Nauru#
   1678 #Makin#
   1680 #Tarawa#
   1679 #Abemama#
   1728 #Suva#
   1687 #Funafuti#
   1749 #Nuku'alofa#
   1729 #Labasa#
   1746 #Christmas Island#
   1750 #Kanton#

### Südafrika
   874 #Maseru
   877 #Mbabane


   1613 #West Island
   1614 #Christmas

   } 
  
   controlledprovinces = { 
   4 #Stornoway
   5 #Scapa Flow
   6 #Inverness
   7 #Aberdeen
   8 #Fort William
   9 #Lerwick
   11 #Glasgow
   12 #Edinburgh
   10 #Dumfries
   13 #Sunderland
   14 #Carisle
   15 #Hull
   16 #Lincoln
   17 #Manchaster
   18 #Sheffield
   19 #Bristol
   20 #Exeter
   21 #Caernarfon
   22 #Cardiff
   24 #Birmingham
   28 #Oxford
   25 #Norwich
   29 #London
   26 #Dover
   27 #Portsmouth
   23 #Plymouth
   #Irland
   36 #Belfast
   35 #Londonderry
   1517 #Bombay ### As Harbour for RN in India
   #Ägypten
   900 #Suez#
   #
   429 #Malta
   348 #Gibraltar
   1011 #Haifa
   1010 #Eilat
   1024 #Az Zarqa
   #Cyprus
   387 #Gazimagusa
   388 #Lefkosia
   #
   1773 #The Bermudas
   1760 #Saint Kitts
   1772 #Turks and Caicos
   #Canada
   2136 #Goose Bay
   2138 #Nain
   2137 #St John's
   #
   1774 #Caynab Islands
   1753 #Dominica
   1754 #Montserrat
   1755 #St Vincent
   1771 #The Bahamas
   1038 #Doha
   2086 #Belize City
   1757 #Anguilla
   1770 #St Lucia
   1763 #Saint George's
   1764 #Barbados
   1769 #Tobago
   1758 #Trinidad
   2045 #Falkland Islands
   1998 #Bartica
   1997 #Georgetown
   1782 #Jamaica
   1766 #British Virgin Island
   1759 #Atigua & Barbuda
   874 #Maseru
   979 #Banjul
   964 #Freetown
   937 #Sokoto
   952 #Tamale
   955 #Ho
   956 #Accra
   939 #Kaduna
   929 #Lagos
   940 #Kano
   941 #Abuja
   930 #Port Harcourt
   931 #Katsina-Ala
   803 #Wadi Halfa
   804 #Dunqula
   813 #Bur Sudan
   814 #Kassala
   805 #Umm Durman
   832 #Hargeysa
   811 #El Qadarif
   812 #Malakal
   843 #Nakuru
   841 #Nairobi
   842 #Mombasa
   848 #Mwanza
   844 #Kampala
   807 #Juba
   810 #Khartoum
   806 #El Ubayyid
   808 #Nayala
   809 #Waw
   932 #Ibadan
   859 #Livingstone
   860 #Kalabo
   871 #Maun
   869 #Francistown
   870 #Gaberones
   866 #Bulawayo
   867 #Salisbury
   933 #Buea
   861 #Kasama
   863 #Lusaka
   864 #Blantyre
   997 #Port Louis
   849 #Mbeya
   850 #Dar es Salaam
   851 #Tabora
   938 #Maiduguri
   993 #Ascension Island
   896 #Saint Helena
   1371 #Hong Kong
   #Malaysia
   1433 #Kota Bahru
   1434 #Alor Setar
   1435 #Ipoh
   1436 #Kuantan
   1437 #Jojor Bahru
   1438 #Kuala Lumpur
   1432 #Singapore
   1421 #Port Bleyar=>Andaman Islands/Nicobar Islands
   #
   1039 #Abu Dhabi
   #Ceylon
   1510 #Kandy
   1511 #Colombo
   1509 #Mahawilachchiya
   #
   1678 #Makin
   1679 #Abemama
   1680 #Tarawa
   1728 #Suva
   1687 #Funafuti
   1729 #Labasa
   1588 #Saint Isabel
   1590 #Guadal Landingzone
   1593 #Guadalcanal
   1624 #Kuching
   1625 #Bandar Seri Begawan
   1626 #Jesselton
   1589 #New Georgia
   1591 #Malaita
   1592 #Nendo
   1682 #Nauru
   1749 #Nuku'alofa
   1750 #Kanton
   1746 #Christmas Island
   1022 #Amman
   1172 #Jerusalem
   1008 #Tel Aviv
   1009 #Gaza
   1025 #Ma'an
   1026 #Al Kerak
   1053 #Aden
   1051 #El Mukalla
   840 #Suqutra
   998 #Port Victoria
   1611 #Male
   877 #Mbabane
   1041 #Kuwait
   1013 #Akko
   1023 #Irbid
   1612 #Kavaratti
   1613 #West Island
   1614 #Christmas
   845 #Gulu
   852 #Zanzibar
   839 #Garissa
   865 #Chipata
   862 #Chingola
   936 #Yola
   934 #Oshogbo
   935 #Benin City
   954 #Kumasi
   953 #Wa
   868 #Hwange 
   } 

						
# Commonwealth Tech '36 
# UK 1936 techs 
# ###################### 
techapps = {
		#Static Defense
		6680
 
#Early Infantry Division  
1010 1020 1030 1040 1050 1060 1070 1080 1090
#SEMI-MOTORIZED CAVALRY 
13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 1380
#Early Mountain Division 
1160  1170 1180 1190 1200 1210 1220 1230 1240
#1922 NAVAL INFANTRY
1560
#Motorised Inf
1396
#Engineers
1830 1840 1850 1860
#Interbellum 1930 Supply 
1910 1920 1930 1940 1950 1960 1970 1980

#Interwar Armoured Car 
2860 2870 2880 2020
#Armor 
7600 7610 2620 2010 2630 2640 2646 2650
#Great War Heavy Field Artillery 
2290 2300 2310 2900 2910 2920
#Early Static Anti-Air Artillery 
2800 2450 21180 21190
#Basic Anti-Air Artillery Brigade 
2810 2820 2510

#Short Range Submarine 
3610 3620 3630 3640 3650
#Improved Destroyer 
3010 3020 3030 3040 3050 3060
#Basic Light Cruiser 
3110 3120 3130 3140 3150 3160
#Improved Heavy Cruiser 
3210 3220 3230 3240 3250 3260
#Interwar Battlecruiser
3310 3320 3330 3340
#Early Battleship 
3410 3420 3430 3440 3450 3456 3460 3470
#Improved Light carrier 
12100 12110 12120 12130
#Fleet Carrier 
3510 3520 3530
#Torpedo & ASW 18
3720 3730 3736 3740 3750 3900
#Troopships
3810 3820

#Early Fighter  
4500 4510 4520 4530 4540 4550 4010 4020
#Early Bomber 
4600 4610 4620 4630 4120 4130
#Multirole fighter
4300 4310 4320 4330 4340
# Transports
4290
#ww1 navalbomber
4700 4710
#CAG 34
4900 4910 4920
#Basic Strategic Bomber 
4800 4810 4820 4220
#SEAPLANES
4740 4750 4760

#Agriculture
5700 5710 5010 5020
#Manufacturing
5810 5820 5050 5830 5060 5070
#Improved Construction Engineering 
5800 5080 5090
#Basic Oil Refining
5190
#Computers
5310 54010 54020 54030 
#Cryptography
5316 5326 5327
#Basic Decimetric Radar Warning Sites 
5410 5416 
#Faculty of Atomic Research 
5470
#Exp. Rocket
5560
#Medicine
5600 5610 5620 5630

#Great War Hospital System 
14000 14010 14020

# WWI Land Doctrines - Entente line: eng fra ita usa bel hol jap 
6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6540 6910
# WWII Land Doctrines
6560 6030 

# Naval Doctrines
# 
# Theories
8010 8020 8030 8040 8050 8060 8070 8080
# Amphib
82300
# Logistic Support
82500
# Naval Interdiction
8500 8510 8520 8550 8560 8600 8610
# Engagement Tactics
8900 8910 8920 8930 8940 8950
# Naval Supremacy
8100 8110 8120 8150 8160 8200 8210
# Carrier Doctrine
81650
# Carrier - Scouting Focus Line
81850
# Carrier - Strike Line
81700

#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 9140

} 
inventions = { 3000027 }
   ai_settings = { flags = {   legitIndie = 1 } }   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 4
     political_left    = 1 
     freedom           = 6 
     free_market       = 8 
     professional_army = 3 
     defense_lobby     = 5 
     interventionism   = 7 
    } 
#   headofstate            = {  type = 9 id = 10001  } 
#   headofgovernment       = {  type = 9 id = 10002  } 
#   foreignminister        = {  type = 9 id = 10003  } 
#   armamentminister       = {  type = 9 id = 10004  } 
#   ministerofsecurity     = {  type = 9 id = 10005  } 
#   ministerofintelligence = {  type = 9 id = 10006  } 
#   chiefofstaff           = {  type = 9 id = 10007  } 
#   chiefofarmy            = {  type = 9 id = 10008  } 
#   chiefofnavy            = {  type = 9 id = 10009  } 
#   chiefofair             = {  type = 9 id = 10010  } 
   # ## United Kingdom Land OOB ### 
   landunit = 
   {  name     = "Aldershot Command" 
     location = 27 
     id       = {  type = 12700 id = 1  } 
     Division = 
     {  id       = {  type = 12700 id = 63  } 
       name     = "British Army HQ" 
       type     = hq 
       model    = 2 
       strength = 100
      } 
     Division = 
     {  id            = {  type = 12700 id = 2  } 
       name 	= "1st Infantry Division" 
       type 	= infantry
	   model 	= 8
       strength = 100
	   extra 	= light_armor_brigade
	   brigade_model = 3
      } 
     Division = 
     {  id       = {  type = 12700 id = 3  } 
       name     = "2nd Infantry Division" 
       type     = infantry
		model   = 7	   
       strength = 100
	   extra    = light_armor_brigade
	   brigade_model = 2
      } 
    } 
   landunit = 
   {  name     = "Northern Command" 
     location = 18 
     id       = {  type = 12700 id = 4  } 
     Division = 
     {  id       = {  type = 12700 id = 5  } 
       name     = "5th Infantry Division" 
       type     = infantry 
	   model    = 7
       strength = 100
      }
     Division = 
     {  id       = {  type = 12700 id = 1501  } 
       name     = "49th (West Riding) Division" 
       type     = infantry 
	   model    = 5
       strength = 10
      } 
     Division = 
     {  id       = {  type = 12700 id = 1502  } 
       name     = "50th (Northumbrian) Division" 
       type     = infantry 
	   model    = 5
       strength = 10
      }  
     Division = 
     {  id       = {  type = 12700 id = 1503  } 
       name     = "23rd (Northumbrian) Division" 
       type     = infantry 
	   model    = 5
       strength = 5
      }  
     Division = 
     {  id       = {  type = 12700 id = 1504  } 
       name     = "46th Division" 
       type     = infantry 
	   model    = 5
       strength = 5
      }   
    } 
   landunit = 
   {  name     = "Southern Command" 
     location = 19 
     id       = {  type = 12700 id = 6  } 
     Division = 
     {  id       = {  type = 12700 id = 7  } 
       name     = "3rd Infantry Division" 
       type     = infantry 
       strength = 100
	   model    = 8
	   extra    = artillery 
       brigade_model = 4
      } 
     Division = 
     {  id       = {  type = 12700 id = 505  } 
       name     = "43rd (Wessex) Division" 
       type     = infantry 
	   model    = 5
       strength = 10
      }  
     Division = 
     {  id       = {  type = 12700 id = 506  } 
       name     = "48th (South Midland) Division" 
       type     = infantry 
	   model    = 5
       strength = 10
      }  
     Division = 
     {  id       = {  type = 12700 id = 507  } 
       name     = "45th Division" 
       type     = infantry 
	   model    = 5
       strength = 5
      }  
     Division = 
     {  id       = {  type = 12700 id = 508  } 
       name     = "61st Division" 
       type     = infantry 
	   model    = 5
       strength = 5
      }  
    } 
   landunit = 
   {  name     = "Scottish Command" 
     location = 12 
     id       = {  type = 12700 id = 509  } 
     Division = 
     {  id       = {  type = 12700 id = 510  } 
       name     = "51st (Highland) Division" 
       type     = infantry 
	   model    = 5
       strength = 10
      }  
     Division = 
     {  id       = {  type = 12700 id = 511  } 
       name     = "52nd (Lowland) Division" 
       type     = infantry 
	   model    = 5
       strength = 10
      }  
     Division = 
     {  id       = {  type = 12700 id = 512  } 
       name     = "9th (Highland) Division" 
       type     = infantry 
	   model    = 5
       strength = 5
      }  
     Division = 
     {  id       = {  type = 12700 id = 513  } 
       name     = "15th (Scottish) Division" 
       type     = infantry 
	   model    = 5
       strength = 5
      }  
    } 
   landunit = 
   {  name     = "Western Command" 
     location = 17 
     id       = {  type = 12700 id = 514  } 
     Division = 
     {  id       = {  type = 12700 id = 515  } 
       name     = "42nd (East Lancashire) Division" 
       type     = infantry 
	   model    = 5
       strength = 10
      }  
     Division = 
     {  id       = {  type = 12700 id = 516  } 
       name     = "53rd (Welsh) Division" 
       type     = infantry 
	   model    = 5
       strength = 10
      }  
     Division = 
     {  id       = {  type = 12700 id = 517  } 
       name     = "55th (West Lancashire) Division" 
       type     = infantry 
	   model    = 5
       strength = 10
      }  
     Division = 
     {  id       = {  type = 12700 id = 518  } 
       name     = "38th (Welsh) Division" 
       type     = infantry 
	   model    = 5
       strength = 5
      }  
     Division = 
     {  id       = {  type = 12700 id = 519  } 
       name     = "59th (Staffordshire) Division" 
       type     = infantry 
	   model    = 5
       strength = 5
      }  
     Division = 
     {  id       = {  type = 12700 id = 520  } 
       name     = "66th Division" 
       type     = infantry 
	   model    = 5
       strength = 5
      }  
    } 
   landunit = 
   {  name     = "Eastern Command" 
     location = 25 
     id       = {  type = 12700 id = 521  } 
     Division = 
     {  id       = {  type = 12700 id = 522  } 
       name     = "4th Infantry Division" 
       type     = infantry 
       strength = 100
	   model    = 8
	   extra    = anti_air
       brigade_model = 2
      } 
     Division = 
     {  id       = {  type = 12700 id = 523  } 
       name     = "44th (Home Counties) Division" 
       type     = infantry 
	   model    = 5
       strength = 10
      }  
     Division = 
     {  id       = {  type = 12700 id = 524  } 
       name     = "54th (East Anglian) Division" 
       type     = infantry 
	   model    = 5
       strength = 10
      }  
     Division = 
     {  id       = {  type = 12700 id = 525  } 
       name     = "12th (Eastern) Division" 
       type     = infantry 
	   model    = 5
       strength = 5
      }  
     Division = 
     {  id       = {  type = 12700 id = 526  } 
       name     = "18th Division" 
       type     = infantry 
	   model    = 5
       strength = 5
      }  
    } 
   landunit = 
   {  name     = "London District" 
     location = 29 
     id       = {  type = 12700 id = 527  } 
     Division = 
     {  id       = {  type = 12700 id = 528  } 
       name     = "1st (London) Division" 
       type     = infantry 
	   model    = 5
       strength = 10
      }  
     Division = 
     {  id       = {  type = 12700 id = 529  } 
       name     = "2nd (London) Division" 
       type     = infantry 
	   model    = 5
       strength = 5
      }  
    } 
   landunit = 
   {  name     = "China Command" 
     location = 1371 
     id       = {  type = 12700 id = 8  } 
     Division = 
     {  id       = {  type = 12700 id = 9  } 
       name     = "Hong Kong Defence Force" 
       type     = garrison 
	   model    = 3
       strength = 75
       locked   = yes 
      } 
    } 
   landunit = 
   {  name     = "Malaya Command" 
     location = 1432 
     id       = {  type = 12700 id = 10  } 
     Division = 
     {  id       = {  type = 12700 id = 11  } 
       name     = "Singapore Fortress" 
       type     = garrison
	   model    = 3
       strength = 35
       locked   = yes 
      } 
    } 
   landunit = 
   {  name     = "Royal West African Frontier Force" 
     location = 929 
     id       = {  type = 12700 id = 282  } 
     Division = 
     {  id       = {  type = 12700 id = 283  } 
       name     = "The Nigeria Regiment" 
       type     = militia 
	   model    = 3
       strength = 70
      } 
    } 
   landunit = 
   {  name     = "British Troops on Gibraltar" 
     location = 348 
     id       = {  type = 12700 id = 12  } 
     Division = 
     {  id       = {  type = 12700 id = 13  } 
       name     = "Gibraltar Defence Force" 
       type     = garrison 
	   model    = 3
       strength = 25
       locked   = yes 
      } 
    } 
   landunit = 
   {  name     = "Ceylon Command" 
     location = 1511 
     id       = {  type = 12700 id = 14  } 
     Division = 
     {  id       = {  type = 12700 id = 15  } 
       name     = "Ceylon Defence Force" 
       type     = militia 
	   model    = 3
       strength = 80
      } 
    } 
   landunit = 
   {  name     = "Malta Command" 
     location = 429 
     id       = {  type = 12700 id = 16  } 
     Division = 
     {  id       = {  type = 12700 id = 17  } 
       name     = "Malta Defence Force" 
       type     = garrison 
	   model    = 3
       strength = 35
       locked   = yes 
      } 
    } 
   landunit = 
   {  name     = "Middle East Command" 
     location = 789 
     id       = {  type = 12700 id = 18  } 
     Division = 
     {  id       = {  type = 12700 id = 19  } 
       name     = "7th Infantry Division" 
       type     = infantry 
	   model    = 7
       strength = 60
	   extra    = light_armor_brigade
	   brigade_model	= 3
      } 
    }
   landunit = 
   {  name     = "British Forces in Palestine and Transjordan" 
     location = 1172 
     id       = {  type = 12700 id = 530  } 
     Division = 
     {  id       = {  type = 12700 id = 531  } 
       name     = "8th Infantry Division" 
       type     = infantry 
	   model    = 8
       strength = 100
      }
    }
 landunit = 
   {  name     = "Gold Coast Defence Force" 
     location = 956 
     id       = {  type = 12700 id = 43  } 
     Division = 
     {  id       = {  type = 12700 id = 44  } 
       name     = "The Gold Coast Regiment" 
       type     = militia 
	   model    = 3
       strength = 30
      } 
    } 
   landunit = 
   {  name     = "British troops in the Sudan" 
     location = 810 
     id       = {  type = 12700 id = 45  } 
     Division = 
     {  id       = {  type = 12700 id = 46  } 
       name     = "Sudan Defence Force" 
       type     = militia 
	   model    = 3
       strength = 40
      } 
    } 
   landunit = 
   {  name     = "Southern Rhodesia Defence Force" 
     location = 867 
     id       = {  type = 12700 id = 47  } 
     Division = 
     {  id       = {  type = 12700 id = 48  } 
       name     = "Southern Rhodesia Defence Force" 
       type     = militia 
	   model    = 3
       strength = 30
      } 
    } 
   landunit = 
   {  name     = "East Africa Force" 
     location = 841 
     id       = {  type = 12700 id = 55  } 
     Division = 
     {  id       = {  type = 12700 id = 56  } 
       name     = "King's African Rifles" 
       type     = militia 
	   model    = 3
       strength = 70
      } 
    } 
   # ################# 
   # Royal Navy # 
   # ################# 
	navalunit = { 
		id = { type = 12700 id = 84 } 
		name = "Home Fleet" 
		location = 5 
		base = 5 
		division = { 
			id = { type = 12700 id = 85 } 
			name = "HMS Nelson" 
			type = battleship 
			model = 6 
			experience = 20
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 86 } 
			name = "HMS Rodney" 
			type = battleship 
			model = 6 
			experience = 20 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 87 } 
			name = "HMS Royal Sovereign" 
			type = battleship 
			model = 3 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 88 } 
			name = "HMS Royal Oak" 
			type = battleship 
			model = 3 
			experience = 20 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 89 } 
			name = "HMS Resolution" 
			type = battleship 
			model = 3 
			experience = 20 
			} 
		division = {
			id = { type = 12700 id = 255 }
			name = "HMS Pegasus"
			type = escort_carrier
			model = 0
			experience = 20
			}
		division = { 
			id = { type = 12700 id = 96 } 
			name = "HMS Cairo" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 97 } 
			name = "HMS Galatea" 
			type = light_cruiser 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 98 } 
			name = "HMS Dunedin" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 99 } 
			name = "HMS Neptune" 
			type = light_cruiser 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 100 } 
			name = "HMS Orion" 
			type = light_cruiser 
			model = 4 
			experience = 20 
			} 
		} 
	navalunit = { 
		id = { type = 12700 id = 104 } 
		name = "Home Fleet Carrier Force" 
		location = 5 
		base = 5 
		division = { 
			id = { type = 12700 id = 105 } 
			name = "HMS Argus" 
			type = escort_carrier 
			model = 1 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 93 } 
			name = "HMS Furious" 
			type = carrier 
			extra1 = cag 
			brigade_model1 = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2223 } 
			name = "Destroyer Division 35" 
			type = destroyer 
			model = 3
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2224 } 
			name = "Destroyer Division 36" 
			type = destroyer 
			model = 3
			experience = 20 
			} 
		} 
	navalunit = { 
		id = { type = 12700 id = 106 } 
		name = "2nd Submarine Squadron" 
		location = 5 
		base = 5 
		division = { 
			id = { type = 12700 id = 107 } 
			name = "3rd Submarine Flotilla" 
			type = submarine 
			model = 3 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 108 } 
			name = "4th Submarine Flotilla" 
			type = submarine 
			model = 3 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 109 } 
			name = "5th Submarine Flotilla" 
			type = submarine 
			model = 3 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 110 } 
			name = "6th Submarine Flotilla" 
			type = submarine 
			model = 3 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 111 } 
			name = "7th Submarine Flotilla" 
			type = submarine 
			model = 2
			experience = 20 
			} 
		} 
	navalunit = { 
		id = { type = 12700 id = 112 } 
		name = "1st Transport Squadron" 
		location = 1517 
		base = 1517 
		division = { 
			id = { type = 12700 id = 113 } 
			name = "Suffolk Flotilla" 
			type = transport 
			model = 1 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 114 } 
			name = "Trojan Star Flotilla" 
			type = transport 
			model = 1 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2227 } 
			name = "Destroyer Division 37" 
			type = destroyer 
			model = 3
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2228 } 
			name = "Destroyer Division 38" 
			type = destroyer
			model = 3 			
			experience = 20 
			} 
		} 
	navalunit = { 
		id = { type = 12700 id = 115 } 
		name = "2nd Transport Squadron" 
		location = 27 
		base = 27 
		division = { 
			id = { type = 12700 id = 116 } 
			name = "Empire Arquebus Flotilla" 
			type = transport 
			model = 1 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 117 } 
			name = "Hororata Flotilla" 
			type = transport 
			model = 1 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 122 } 
			name = "Empire Charmain Flotilla" 
			type = transport 
			model = 1 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 222 } 
			name = "HMS Dauntless" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 224 } 
			name = "Destroyer Division 31" 
			type = destroyer 
			model = 3
			experience = 20 
			} 
		} 
	navalunit = { 
		id = { type = 12700 id = 118 } 
		name = "3rd Transport Squadron" 
		location = 27 
		base = 27 
		division = { 
			id = { type = 12700 id = 119 } 
			name = "Clan Macauley Flotilla" 
			type = transport 
			model = 1 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 120 } 
			name = "Empire Captain Flotilla" 
			type = transport 
			model = 1 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 121 } 
			name = "Andes Flotilla" 
			type = transport 
			model = 1 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 144 } 
			name = "Destroyer Division 14" 
			type = destroyer 
			model = 3
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 145 } 
			name = "Destroyer Division 15" 
			type = destroyer 
			model = 3
			experience = 20 
			} 
		} 
	navalunit = { 
		id = { type = 12700 id = 123 } 
		name = "4th Transport Squadron" 
		location = 5 
		base = 5 
		division = { 
			id = { type = 12700 id = 124 } 
			name = "Essex Flotilla" 
			type = transport 
			model = 1 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 125 } 
			name = "Maloja Flotilla" 
			type = transport 
			model = 1 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2221 } 
			name = "Destroyer Division 8" 
			type = destroyer 
			model = 3
			experience = 20 
			} 
		} 
	navalunit = { 
		id = { type = 12700 id = 126 } 
		name = "5th Transport Squadron" 
		location = 20 
		base = 20 
		division = { 
			id = { type = 12700 id = 127 } 
			name = "Empire Splendour Flotilla" 
			type = transport 
			model = 1 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 128 } 
			name = "Sam Torch Flotilla" 
			type = transport 
			model = 1 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 129 } 
			name = "Resolution Flotilla" 
			type = transport 
			model = 1 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 131 } 
			name = "Destroyer Division 5" 
			type = destroyer 
			model = 3
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 132 } 
			name = "Destroyer Division 6" 
			type = destroyer 
			model = 3
			experience = 20 
			} 
		} 
	navalunit = { 
		id = { type = 12700 id = 134 } 
		name = "Destroyer Squadron 2" 
		location = 17 
		base = 17 
		division = { 
			id = { type = 12700 id = 135 } 
			name = "Destroyer Division 8" 
			type = destroyer 
			model = 5 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 136 } 
			name = "Destroyer Division 9" 
			type = destroyer 
			model = 5
			experience = 20 
			} 
		} 
	navalunit = { 
		id = { type = 12700 id = 137 } 
		name = "Destroyer Squadron 3" 
		location = 17 
		base = 17 
		division = { 
			id = { type = 12700 id = 138 } 
			name = "Destroyer Division 10" 
			type = destroyer 
			model = 4
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 139 } 
			name = "Destroyer Division 11" 
			type = destroyer 
			model = 4
			experience = 20 
			} 
		} 
	navalunit = { 
		id = { type = 12700 id = 140 } 
		name = "Destroyer Squadron 4" 
		location = 27 
		base = 27 
		division = { 
			id = { type = 12700 id = 141 } 
			name = "Destroyer Division 12" 
			type = destroyer 
			model = 4
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 142 } 
			name = "Destroyer Division 13" 
			type = destroyer 
			model = 4
			experience = 20 
			} 
		} 
	navalunit = { 
		id = { type = 12700 id = 147 } 
		name = "Mediterranean Fleet" 
		location = 789 
		base = 789 
		division = { 
			id = { type = 12700 id = 148 } 
			name = "HMS Queen Elizabeth" 
			type = battleship 
			model = 4 
			experience = 20 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 153 } 
			name = "HMS Revenge" 
			type = battleship 
			model = 3 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 156 } 
			name = "HMS Devonshire" 
			type = heavy_cruiser 
			model = 3 
			experience = 20 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 160 } 
			name = "HMS Exeter" 
			type = heavy_cruiser 
			model = 4 
			experience = 20 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 161 } 
			name = "HMS York" 
			type = heavy_cruiser 
			model = 4 
			experience = 20 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 162 } 
			name = "HMS Coventry" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 163 } 
			name = "HMS Curlew" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 164 } 
			name = "HMS Delhi" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 165 } 
			name = "HMS Despatch" 
			type = light_cruiser 
			model = 2
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 166 } 
			name = "HMS Durban" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 167 } 
			name = "HMS Arethusa" 
			type = light_cruiser 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 149 } 
			name = "HMS Barham" 
			type = battleship 
			model = 4 
			experience = 20 
			extra1 = naval_anti_air_l
			extra2 = naval_fire_controll_l
			extra3 = floatplane
			brigade_model3 = 4
			} 
		} 
	navalunit = { 
		id = { type = 12700 id = 174 } 
		name = "1st Submarine Squadron" 
		location = 789 
		base = 789 
		division = { 
			id = { type = 12700 id = 175 } 
			name = "1st Submarine Flotilla" 
			type = submarine 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 176 } 
			name = "2nd Submarine Flotilla" 
			type = submarine 
			model = 3 
			experience = 20 
			} 
		} 
	navalunit = { 
		id = { type = 12700 id = 177 } 
		name = "America & West Indies Station" 
		location = 1773 
		base = 1773 
		division = { 
			id = { type = 12700 id = 178 } 
			name = "HMS Dragon" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 179 } 
			name = "HMS Ajax" 
			type = light_cruiser 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 180 } 
			name = "Destroyer Division 23" 
			type = destroyer 
			model = 2
			experience = 20 
			} 
		} 
	navalunit = { 
		id = { type = 12700 id = 182 } 
		name = "Africa Station" 
		location = 964 
		base = 964 
		division = { 
			id = { type = 12700 id = 183 } 
			name = "HMS Leander" 
			type = light_cruiser 
			model = 4 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 184 } 
			name = "HMS Carlisle" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 185 } 
			name = "Destroyer Division 25" 
			type = destroyer 
			model = 2
			experience = 20 
			} 
		} 
	navalunit = { 
		id = { type = 12700 id = 187 } 
		name = "East Indies Station" 
		location = 1511 
		base = 1511 
		division = { 
			id = { type = 12700 id = 188 } 
			name = "HMS Norfolk" 
			type = heavy_cruiser 
			model = 3 
			experience = 20 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 189 } 
			name = "HMS Diomede" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 190 } 
			name = "HMS Emerald" 
			type = light_cruiser 
			model = 3 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 191 } 
			name = "HMS Enterprise" 
			type = light_cruiser 
			model = 3 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 192 } 
			name = "Destroyer Division 27" 
			type = destroyer 
			model = 4
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 193 } 
			name = "Destroyer Division 28" 
			type = destroyer 
			model = 4
			experience = 20 
			} 
		} 
	navalunit = { 
		id = { type = 12700 id = 194 } 
		name = "China Station" 
		location = 1371 
		base = 1371 
		division = { 
			id = { type = 12700 id = 195 } 
			name = "HMS Eagle" 
			type = escort_carrier 
			model = 1 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 196 } 
			name = "HMS Capetown" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 197 } 
			name = "Destroyer Division 29" 
			type = destroyer 
			model = 4
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 198 } 
			name = "Destroyer Division 30" 
			type = destroyer 
			model = 4 
			experience = 20 
			} 
		} 
	navalunit = { 
		id = { type = 12700 id = 199 } 
		name = "3rd Submarine Squadron" 
		location = 1371 
		base = 1371 
		division = { 
			id = { type = 12700 id = 200 } 
			name = "8th Submarine Flotilla" 
			type = submarine 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 201 } 
			name = "9th Submarine Flotilla" 
			type = submarine 
			model = 2 
			experience = 20 
			} 
		} 
	navalunit = { 
		id = { type = 12700 id = 239 } 
		name = "4th Submarine Squadron" 
		location = 27 
		base = 27 
		division = { 
			id = { type = 12700 id = 240 } 
			name = "10th Submarine Flotilla" 
			type = submarine 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 241 } 
			name = "11th Submarine Flotilla" 
			type = submarine 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 242 } 
			name = "12th Submarine Flotilla" 
			type = submarine 
			model = 2 
			experience = 20 
			} 
		} 
	navalunit = { 
		id = { type = 12700 id = 202 } 
		name = "Reserve Fleet" 
		location = 27 
		base = 27 
		division = { 
			id = { type = 12700 id = 208 } 
			name = "HMS Berwick" 
			type = heavy_cruiser 
			model = 3 
			experience = 20 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 209 } 
			name = "HMS Cornwall" 
			type = heavy_cruiser 
			model = 3 
			experience = 20 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 210 } 
			name = "HMS Cumberland" 
			type = heavy_cruiser 
			model = 3 
			experience = 20 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 211 } 
			name = "HMS Suffolk" 
			type = heavy_cruiser 
			model = 3 
			experience = 20 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 212 } 
			name = "HMS Kent" 
			type = heavy_cruiser 
			model = 3 
			experience = 20 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 217 } 
			name = "HMS Colombo" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 218 } 
			name = "HMS Cardiff" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 219 } 
			name = "HMS Ceres" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 220 } 
			name = "HMS Curacao" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 221 } 
			name = "HMS Danae" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			} 
		}         
	navalunit = { 
		id = { type = 12700 id = 2219 } 
		name = "Force A" 
		location = 5 
		base = 5 
		division = { 
			id = { type = 12700 id = 90 } 
			name = "HMS Ramillies" 
			type = battleship 
			model = 3 
			experience = 20 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 91 } 
			name = "HMS Hood" 
			type = battlecruiser 
			model = 2 
			experience = 20 
			extra1 = floatplane
			extra2 = naval_fire_controll_l
			brigade_model1 = 4
			brigade_model2 = 1
			} 
		division = { 
			id = { type = 12700 id = 92 } 
			name = "HMS Renown" 
			type = battlecruiser 
			model = 1 
			experience = 20 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 94 } 
			name = "HMS Repulse" 
			type = battlecruiser 
			model = 1 
			experience = 20 
			extra1 = naval_anti_air_l
			extra2 = naval_fire_controll_l
			extra3 = naval_improved_hull_l
			extra4 = floatplane
			brigade_model4 = 4
			} 
		division = { 
			id = { type = 12700 id = 103 } 
			name = "Destroyer Division 3" 
			type = destroyer 
			model = 3 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 102 } 
			name = "Destroyer Division 2" 
			type = destroyer 
			model = 3
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 95 } 
			name = "Destroyer Division 4" 
			type = destroyer 
			model = 3 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 101 } 
			name = "Destroyer Division 1" 
			type = destroyer 
			model = 3
			experience = 20 
			} 
		} 
	navalunit = { 
		id = { type = 12700 id = 2229 } 
		name = "Force C" 
		location = 789 
		base = 789 
		division = { 
			id = { type = 12700 id = 2231 } 
			name = "Destroyer Division 39" 
			type = destroyer
			model = 3		
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 2232 } 
			name = "Destroyer Division 40" 
			type = destroyer 
			model = 3
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 154 } 
			name = "HMS Courageous" 
			type = carrier 
			extra1 = cag 
			brigade_model1 = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 155 } 
			name = "HMS Glorious" 
			type = carrier 
			extra1 = cag 
			brigade_model1 = 2 
			experience = 20 
			} 
		} 
	navalunit = { 
		id = { type = 12700 id = 2334 } 
		name = "Force B" 
		location = 27 
		base = 27 
		division = { 
			id = { type = 12700 id = 203 } 
			name = "HMS Hermes" 
			type = escort_carrier 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 223 } 
			name = "HMS Achilles" 
			type = light_cruiser 
			model = 4 
			experience = 20 
			} 
		} 
	navalunit = { 
		id = { type = 12700 id = 2338 } 
		name = "Force D" 
		location = 27 
		base = 27 
		division = { 
			id = { type = 12700 id = 204 } 
			name = "HMS Effingham" 
			type = heavy_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 205 } 
			name = "HMS Frobisher" 
			type = heavy_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 206 } 
			name = "HMS Dorsetshire" 
			type = heavy_cruiser 
			model = 3 
			experience = 20 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 207 } 
			name = "HMS Hawkins" 
			type = heavy_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 564 } 
			name = "HMS Erebus" 
			type = heavy_cruiser 
			model = 2 
			experience = 20 
			extra1 = naval_fire_controll_s
			brigade_model1 = 0
			} 
		division = { 
			id = { type = 12700 id = 565 } 
			name = "HMS Terror" 
			type = heavy_cruiser 
			model = 2 
			experience = 20 
			extra1 = naval_fire_controll_s
			brigade_model1 = 0
			} 
		division = { 
			id = { type = 12700 id = 213 } 
			name = "HMS Caledon" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 214 } 
			name = "HMS Calypso" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 215 } 
			name = "HMS Caradoc" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 216 } 
			name = "HMS Calcutta" 
			type = light_cruiser 
			model = 2 
			experience = 20 
			} 
		} 
	navalunit = { 
		id = { type = 12700 id = 2342 } 
		name = "Force E" 
		location = 789 
		base = 789 
		division = { 
			id = { type = 12700 id = 150 } 
			name = "HMS Valiant" 
			type = battleship 
			model = 4 
			experience = 20 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 151 } 
			name = "HMS Malaya" 
			type = battleship 
			model = 4 
			experience = 20 
			extra1 = naval_anti_air_l
			extra2 = naval_fire_controll_l
			extra3 = floatplane
			brigade_model3 = 4
			} 
		division = { 
			id = { type = 12700 id = 157 } 
			name = "HMS London" 
			type = heavy_cruiser 
			model = 3 
			experience = 20 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 158 } 
			name = "HMS Shropshire" 
			type = heavy_cruiser 
			model = 3 
			experience = 20 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 159 } 
			name = "HMS Sussex" 
			type = heavy_cruiser 
			model = 3 
			experience = 20 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 12700 id = 173 } 
			name = "Destroyer Division 22" 
			type = destroyer 
			model = 3
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 172 } 
			name = "Destroyer Division 21" 
			type = destroyer 
			model = 3
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 171 } 
			name = "Destroyer Division 20" 
			type = destroyer 
			model = 3
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 170 } 
			name = "Destroyer Division 19" 
			type = destroyer 
			model = 3
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 169 } 
			name = "Destroyer Division 18" 
			type = destroyer 
			model = 3
			experience = 20 
			} 
		division = { 
			id = { type = 12700 id = 168 } 
			name = "Destroyer Division 17" 
			type = destroyer 
			model = 3
			experience = 20 
			} 
		} 
   # ################# 
   # Royal Airforce # 
   # ################# 
   airunit = 
   {  location = 18 
     base     = 18 
     id       = {  type = 12700 id = 67  } 
     name     = "1st Tactical Wing" 
     Division = 
     {  id       = {  type = 12700 id = 64  } 
       name     = "No.1 RAF Tactical Group" 
       type     = tactical_bomber 
       model    = 5 
       strength = 20
      } 
    } 
   airunit = 
   {  location = 25 
     base     = 25 
     id       = {  type = 12700 id = 65  } 
     name     = "RAF Strategic Bomber Command" 
     Division = 
     {  id       = {  type = 12700 id = 66  } 
       name     = "No.2 RAF Strategic Group" 
       type     = strategic_bomber 
       model    = 2
       strength = 20
      } 
     Division = 
     {  id       = {  type = 12700 id = 68  } 
       name     = "no.3 RAF Strategic Group" 
       type     = strategic_bomber 
       model    = 3
       strength = 20
      } 
     Division = 
     {  id       = {  type = 12700 id = 69  } 
       name     = "no.4 RAF Strategic Group" 
       type     = strategic_bomber 
       model    = 3
       strength = 20
      } 
    } 
   airunit = 
   {  location = 27 
     base     = 27 
     id       = {  type = 12700 id = 70  } 
     name     = "2nd Tactical Wing" 
     Division = 
     {  id       = {  type = 12700 id = 71  } 
       name     = "No.5 RAF Tactical Group" 
       type     = tactical_bomber 
       model    = 5 
       strength = 20
      } 
    } 
   airunit = 
   {  location = 18 
     base     = 18 
     id       = {  type = 12700 id = 72  } 
     name     = "1st Fighter Wing" 
     Division = 
     {  id       = {  type = 12700 id = 73  } 
       name     = "No.11 RAF Fighter Group" 
       type     = interceptor 
       model    = 7
       strength = 20
      } 
    } 
   airunit = 
   {  location = 27 
     base     = 27 
     id       = {  type = 12700 id = 74  } 
     name     = "2nd Fighter Wing" 
     Division = 
     {  id       = {  type = 12700 id = 75  } 
       name     = "No.12 RAF Fighter Group" 
       type     = Multi_role
       model    = 3
       strength = 20
      } 
    } 
   airunit = 
   {  location = 27 
     base     = 27 
     id       = {  type = 12700 id = 76  } 
     name     = "3rd Fighter Wing" 
     Division = 
     {  id       = {  type = 12700 id = 77  } 
       name     = "No.13 RAF Fighter Group" 
       type     = interceptor 
       model    = 7
       strength = 20
      } 
    } 
   airunit = 
   {  location = 1008 
     base     = 1008 
     id       = {  type = 12700 id = 78  } 
     name     = "Middle East Air Command" 
     Division = 
     {  id       = {  type = 12700 id = 79  } 
       name     = "Middle East Group" 
       type     = tactical_bomber 
       model    = 5 
       strength = 20
      } 
    } 
   airunit = 
   {  location = 1432 
     base     = 1432 
     id       = {  type = 12700 id = 82  } 
     name     = "Far East Air Command" 
     Division = 
     {  id       = {  type = 12700 id = 83  } 
       name     = "Far East Group" 
       type     = tactical_bomber
       model    = 5
       strength = 20
      } 
    } 
	
	
	# Warships Under Construction# 
	division_development = {
		name  = "HMS Warspite" # 1934-37 refit
		type  = battleship 
		model = 4 
		new_model = no
		cost  = 0.5 
		unitcost = no
		id    = {  type = 12700 id = 152  } 
		date  = {  year = 1937 month = january day = 1  } 
		extra1 = naval_anti_air_l
		extra2 = naval_fire_controll_l
		extra3 = floatplane
		brigade_model3 = 4
	} 
	division_development = {
		name  = "Destroyer Division 33" 
		type  = destroyer 
		model = 5 
		cost  = 0.1 
		id    = {  type = 12700 id = 226  } 
		date  = {  year = 1936 month = march day = 1  } 
	} 
	division_development = {
		name  = "Destroyer Division 34" 
		type  = destroyer 
		model = 5 
		cost  = 0.1 
		id    = {  type = 12700 id = 227  } 
		date  = {  year = 1936 month = april day = 1  } 
	} 
   division_development = 
   {  name  = "13th Submarine Flotilla" 
     type  = submarine 
     model = 4 
     cost  = 0.1 
     id    = {  type = 12700 id = 228  } 
     date  = {  year = 1936 month = march day = 1  } 
    }
   division_development = 
   {  name  = "HMS Aurora" 
     type  = light_cruiser 
     model = 4 
     new_model = no
     cost  = 0.1 
     id    = {  type = 12700 id = 229  } 
     date  = {  year = 1937 month = november day = 12  } 
    }
   division_development = 
   {  name  = "HMS Birmingham" 
     type  = light_cruiser 
     model = 5
     new_model = no
     cost  = 0.1 
     id    = {  type = 12700 id = 230  } 
     date  = {  year = 1937 month = november day = 18  } 
    }
   division_development = 
   {  name  = "HMS Glasgow" 
     type  = light_cruiser 
     model = 5
     new_model = no
     cost  = 0.1 
     id    = {  type = 12700 id = 231  } 
     date  = {  year = 1937 month = september day = 9  } 
    }
   division_development = 
   {  name  = "HMS Newcastle" 
     type  = light_cruiser 
     model = 5
     new_model = no
     cost  = 0.1 
     id    = {  type = 12700 id = 232  } 
     date  = {  year = 1937 month = march day = 5  } 
    }
   division_development = 
   {  name  = "HMS Penelope" 
     type  = light_cruiser 
     model = 4 
     new_model = no
     cost  = 0.1 
     id    = {  type = 12700 id = 233  } 
     date  = {  year = 1936 month = november day = 13  } 
    }
   division_development = 
   {  name  = "HMS Sheffield" 
     type  = light_cruiser 
     model = 5 
     new_model = no
     cost  = 0.1 
     id    = {  type = 12700 id = 234  } 
     date  = {  year = 1937 month = august day = 25  } 
    }
   division_development = 
   {  name  = "HMS Southampton" 
     type  = light_cruiser 
     model = 5 
     new_model = no
     cost  = 0.1 
     id    = {  type = 12700 id = 235  } 
     date  = {  year = 1937 month = march day = 6  } 
    }
   division_development = 
   {  name  = "HMS Ark Royal" 
     type  = carrier 
     model = 2
     new_model = no
     cost  = 0.1
     id    = {  type = 12700 id = 236  } 
     date  = {  year = 1939 month = march day = 1  } 
      extra = cag  
      brigade_model = 2  
    } 

# Historically, these two ships were gifted to Australia.  
# Including them, because they were commissioned into the RN in 1936.
# Maybe we can add an event to transfer them, I think WIF did that.
   division_development = 
   {  name  = "HMS Amphion" 
     type  = light_cruiser 
     model = 4 
     new_model = no
     cost  = 0.1 
     id    = {  type = 12700 id = 237  } 
     date  = {  year = 1936 month = june day = 15  } 
    }
   division_development = 
   {  name  = "HMS Apollo" 
     type  = light_cruiser 
     model = 4 
     new_model = no
     cost  = 0.1 
     id    = {  type = 12700 id = 238  } 
     date  = {  year = 1936 month = january day = 13  } 
    }


landdivision = { dormant = yes id = { type = 12700 id = 10001 }  name = "1. Home Guard"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 12700 id = 10002 }  name = "2. Home Guard"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 12700 id = 10003 }  name = "3. Home Guard"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 12700 id = 10004 }  name = "4. Home Guard"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 12700 id = 10005 }  name = "5. Home Guard"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 12700 id = 10006 }  name = "6. Home Guard"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 12700 id = 10007 }  name = "7. Home Guard"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 12700 id = 10008 }  name = "8. Home Guard"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 12700 id = 10009 }  name = "9. Home Guard"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 12700 id = 10010 }  name = "10. Home Guard"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 12700 id = 10011 }  name = "11. Home Guard"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 12700 id = 10012 }  name = "12. Home Guard"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 12700 id = 10013 }  name = "13. Home Guard"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 12700 id = 10014 }  name = "14. Home Guard"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 12700 id = 10015 }  name = "15. Home Guard"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 12700 id = 10016 }  name = "16. Home Guard"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 12700 id = 10017 }  name = "17. Home Guard"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }
landdivision = { dormant = yes id = { type = 12700 id = 10018 }  name = "18. Home Guard"  type = garrison model = 5 extra = artillery brigade_model = 9 locked  = yes }

	convoy_development = { 
		id = { type = 14500 id = 543 } 
		cost = 0.1
		size = 100 
		type = escorts 
		date  = {  year = 1964 } 
		} 
	convoy_development = { 
		id = { type = 14500 id = 544 } 
		cost = 0.1
		size = 100
		type = transports 
		date  = {  year = 1964 } 
		} 
	convoy_development = { 
		id = { type = 14500 id = 545 } 
		cost = 0.1
		size = 100
		type = transports 
		date  = {  year = 1964 } 
		} 		
  } 
 
