 	   
   ##############################   
   # Country definition for USA #   
   ##############################   
      
   #####################   
   # Country main data #   
   #####################   
      
   country =   
   {  tag                    = USA   
     # Resource Reserves   
	free = {
		ic = -250
		oil = -250
		metal = -250
		energy = -250
		rare_materials = -250
		money = 0.0
	}
	ai_settings = { flags = {   legitIndie = 1 } }
energy                 = 30060
metal                  = 15030
rare_materials         = 7515  
     oil                    = 5000   
     supplies               = 5000   
     money                  = 100   
     manpower               = 102   
     transports             = 660   
     escorts                = 53   
     dissent = 15
     research_mod = 0.75
	peacetime_ic_mod       = 0.8
     
     capital                = 1809   
     diplomacy =   
     {  relation =   
       {  tag        = ARG   
         value      = 75   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation = {  tag = AST value = 125  }   
       relation = {  tag = BEL value = 75  }   
       relation = {  tag = BHU value = 100  }   
       relation =   
       {  tag        = BOL   
         value      = 85   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation =   
       {  tag        = BRA   
         value      = 120   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation =   
       {  tag        = CAN   
         value      = 175   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation =   
       {  tag        = CHL   
         value      = 100   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation =   
       {  tag        = COL   
         value      = 75   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation =   
       {  tag        = COS   
         value      = 100   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation =   
       {  tag        = CUB   
         value      = 200   
         guaranteed = {  day = 30 month = december year = 1935  }   
         access     = yes   
        }   
       relation = {  tag = DEN value = 75  }   
       relation =   
       {  tag        = DOM   
         value      = 125   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation =   
       {  tag        = ECU   
         value      = 75   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation = {  tag = ENG value = 150  }   
       relation = {  tag = FIN value = 90  }   
       relation = {  tag = FRA value = 65  }   
       relation = {  tag = GER value = -10  }   
       relation =   
       {  tag        = GUA   
         value      = 125   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation =   
       {  tag        = HAI   
         value      = 100   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation = {  tag = HOL value = 70  }   
       relation =   
       {  tag        = HON   
         value      = 100   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation = {  tag = IRE value = 75  }   
       relation = {  tag = IRQ value = 120  }   
       relation = {  tag = JAP value = 15  }   
       relation = {  tag = LIB value = 200 access = yes  }   
	   relation = {  tag = LIT value = 65  }
	   relation = {  tag = LAT value = 65  }
	   relation = {  tag = EST value = 65  }
       relation = {  tag = MAN value = 1  }   
       relation =   
       {  tag        = MEX   
         value      = 125   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation = {  tag = NEP value = 100  }   
       relation =   
       {  tag        = NIC   
         value      = 100   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation = {  tag = NOR value = 75  }   
       relation = {  tag = NZL value = 125  }   
       relation = {  tag = OMN value = 100  }   
       relation =   
       {  tag        = PAN   
         value      = 175   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation =   
       {  tag        = PAR   
         value      = 75   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation = {  tag = PHI value = 200 access = yes  }   
       relation =   
       {  tag        = PRU   
         value      = 75   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation = {  tag = SAF value = 125  }   
       relation =   
       {  tag        = SAL   
         value      = 100   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation = {  tag = SOV value = 35  }   
       relation =   
       {  tag        = SCH   
         value      = 1   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation = {  tag = SWE value = 75  }   
       relation =   
       {  tag        = URU   
         value      = 100   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation =   
       {  tag        = VEN   
         value      = 125   
         guaranteed = {  day = 30 month = december year = 1935  }   
        }   
       relation = {  tag = YEM value = 100  }   
      }   
     SpyInfo                = {  country = "USA" NumberOfSpies = 11  }   
        
claimedprovinces = {

	#Philippines
	1567 #Baguio=>Lingay Gulf
	1570 #Tuguegarao=>Apari
	1569 #Olongapo=>Bataan
	1566 #Cabanatuan=>ClarkField
	1565 #Manila/Lamon Bay
	1568 #Legazpi=>Legaspi
	1571 #Mindoro
	1576 #Panay
	1575 #Samar
	1573 #Leyte
	1574 #Bacolod=>Negros
	1580 #Zamboanga
	1578 #Cagayan de Oro=>Cagayan
	1579 #Dabaw=>Davao
	1572 #Palawan
	1577 #Jolo

	#Spanish/Mexicans
	1922
	1926
	#1927
	1923
	#1903
	1905
	#1906
	1901
	#1900
	#1892
	1886
	#1887
	1883
	1891
	#1888

	#Non-European and other areas
	#Black belt
	1816
	#1815
	1814
	#1813
	1812
	1961
	1962
	#1963
	1960
	#1958
	1957
	#1959
	1954
	1947
	#1946
	1936
	1950
	1935
	1937
	1938
	#1939
	1940
	#1915
	#1933
	#1929
	#1932
	#1934
	#1930
	#1944
	#1807

	#Native tribes
	#1911
	1912
	#1913
	#1916

	1904
	1897
	1899
	#1902
	1860

	#Hawaii/Pacific
	1736
	1737
	1734
	1735
	1739
	1673
	1683
	1738
	1747
	1745
	1751
	1733
	
	#Puerto Rico
	1765

	#Alaska
	2143
	2139
	2144
	2146
	2145
	2140
	2174
	
#Mormonland
	1869
	1870
	1893
	1894
	1895
	1896
	1897
	1898
	1899
	
#CSA
	1810
	1811
	1813
	1814
	1815
	1816
	1817
	1818
	1819
	1820
	1823
	1827
	1828
	1833
	1836
	1900
	1902
	1903
	1906
	1909
	1910
	1911
	1912
	1913
	1915
	1916
	1917
	1918
	1919
	1920
	1921
	1924
	1927
	1928
	1929
	1930
	1933
	1939
	1941
	1942
	1943
	1944
	1945
	1946
	1948
	1949
	1950
	1951
	1952
	1953
	1955
	1956
	1958
	1959
	1962
	1963
	1964
	
	#Louisiana French
	1931
	1932
	1934
	1937
	#1944
	
	#External claims

	#Panama
	889

	#Cuba
	1776 1779 1775 1777 1778
	
	#Canada
	2089 2092 2090 2093 2095 2103 2104 2105 2102 2099 2091 2096 2097 2098 2094 2100 2101 2106 2107 2115 2108 2109  
     2110 2129 2113 2114 2148 2149 2112 2127 2130 2111 2116 2123 2122 2121 2120 2125 2124 2117 2118 2119 2128 2135 2136 2138 2137 2132 2131 2134 2126 2133
}

    nationalprovinces      = {
	#USA
		#Non-Germanic/Protestant Europeans
	#North-East Immigrants
	#1786
	#1789
	1794
	#1795
	1796
	#1797
	1799
	#1805
	1841
	
		#Anglo-Saxon Europeans (English, Scottish, Irish, Scots-Irish)
#New England
	1784
	1785
	1786
	1787
	1788
	1789
	1790
	1792
	1793
	1795
	1797
	1805
	1807

#West coast
	1876
	1878
	1879
	1880
	1881
	1882
	1884
	1885
	1887
	1888
	1889
	1890
	1892
	
	1809
	1792
	1797
	1805
	1807
	1823
	1827
	1828
	1876
	1878
	1879
	1882
	
	1909
	1910
	1912
	1913
	1948
	1949
	1953
	
	1844 #Flint#
	1849 #Duluth#
	1854 #Grand Forks=>Moorehead
	1852 #Minot#=>Fargo(split)
	1853 #Fort Peck#
	1864 #Great Falls=>GreatFalls/Dodson(merge)#
	1865 #Missoula#
	1861 #Coeur d'Alene=>Lewiston#
	1875 #Wenatchee=>Spokane(split)#
	1874 #Seattle#
	1877 #Tacoma#
	1873 #Yakima=>Richland#
	1872 #Spokane#
	1863 #Helena=>Anaconda#
	1862 #Bozeman=>Butte#
	1867 #Glendive=>Billings#
	1856 #Bismarck#
	1855 #Fargo#
	1847 #Minneapolis#
	1850 #Saint Paul=>Duluth#
	1848 #Superior=>Greenbay#
	1840 #Eau Claire#
	#1841 #Greenbay#
	1842 #Grand Rapids#
	1843
	1845 #Detroit#
	1791 #Buffalo#
	1800 #Binghampton=>Syracuse#
	1804 #Scranton#
	1803 #Williamsport=>Altoona(split)#
	1801 #Harrisburg#
	1808 #Baltimore#
	1802 #Altoona#
	1798 #Warren=>Pittsburgh#
	1824 #Erie=>Cleveland#
	1825 #Cleveland#
	1821 #Columbus#
	1806 #Pittsburgh#
	1822 #Toledo=>Cleveland#
	1826 #Fort Wayne#
	1831
	1832 #Chicago#
	1839 #Milwaukee#
	1829 #Peoria#
	1830 #Decatur#
 	1835 #Saint Chalres#
	1837 #Cedar Rapids#
	1846 #Rochester=>Cedar Rapids(split)#
	1838 #Des Moines#
	1834 #Saint Joseph=>Des Moines(split)#
	1914 #Kansas City#
	1859 #Lincoln=>Kansas City(split)#
	1857 #Sioux Falls#
	1851 #Miles City#
	1858 #Rapid City#
	1871
	1908 #Denver#
	1907 #Cheyenne=>Aspen#
	1866 #Casper#
	1868 #Billings#
	1925 #Austin#

#Alaska#
	2141 #Juneau#
	2147 #Valdez=>Anchorage(split)#
	2142 #Anchorage#
	2150 #Adak=>Amchitka/Kiska/Andreanof#
	2151 #Dutch Habor=>Unimak/Unalaska/Umnak/Yunaska#
}  

    ownedprovinces         = {  
	1786 #Presque Isle
	1784 #Bangor
	1787 #Concord 
	1785 #Lewiston
	1790 #Burlington
	1794 #Watertown
	1844 #Flint
	1843 #Marquette
	1849 #Duluth
	1854 #Grand Forks
	1852 #Minot
	1853 #Fort Peck
	1864 #Great Falls
	1865 #Missoula
	1861 #Coeur d'Alene
	1875 #Wenatchee
	1874 #Seattle
	1877 #Tacoma
	1873 #Yakima 
	1872 #Spokane
	1876 #Walla Walla
	1871 #Boise
	1863 #Helena
	1862 #Bozeman
	1867 #Glendive
	1856 #Bismarck
	1855 #Fargo
	1847 #Minneapolis
	1850 #Saint Paul
	1848 #Superior
	1840 #Eau Claire
	1841 #Greenbay
	1842 #Grand Rapids
	1845 #Detroit
	1791 #Buffalo
	1792 #Syracuse
	1793 #Albany
	1788 #Hartford
	1789 #Boston
	1796 #Providence
	1799 #Newburgh
	1800 #Binghampton
	1797 #Newark
	1804 #Scranton
	1795 #New York
	1803 #Williamsport
	1801 #Harrisburg
	1805 #Philadelphia
	1807 #Cape Charles 
	1809 #Washington 
	1808 #Baltimore
	1802 #Altoona
	1798 #Warren
	1824 #Erie
	1825 #Cleveland
	1821 #Columbus
	1806 #Pittsburgh
	1810 #Clakrsburg
	1814 #Arlington
	1813 #Richmond
	1812 #Norfolk
	1815 #Danville
	1816 #Charlottesville
	1818 #Roanoke
	1817 #Beckley
	1811 #Huntington
	1822 #Toledo
	1823 #Cincinnati
	1820 #Lexington
	1819 #Louisville
	1827 #Evansville
	1828 #Indianapolis 
	1826 #Fort Wayne
	1832 #Chicago
	1839 #Milwaukee
	1829 #Peoria 
	1830 #Decatur
	1831 #Belleville
	1833 #Saint Louis
    1835 #Saint Chalres
	1837 #Cedar Rapids
	1846 #Rochester
	1838 #Des Moines
	1834 #Saint Joseph
	1836 #Springfield 
	1912 #Tulsa
	1914 #Kansas City
	1859 #Lincoln
	1860 #Omaha
	1857 #Sioux Falls
	1851 #Miles City
	1858 #Rapid City
	1908 #Denver
	1910 #Wichita
	1909 #Colorado Springs
	1907 #Cheyenne
	1866 #Casper
	1868 #Billings
	1898 #Rock Springs
	1897 #Grand Junction
	1899 #Saint George
	1896 #Salt Lake City
	1869 #Idaho Falls
	1870 #Rexburg
	1881 #Twin Falls
	1894 #Elko
	1893 #Las Vegas
	1895 #Reno
	1880 #Klamath Falls
	1882 #Bend
	1878 #Portland
	1879 #Eugene
	1890 #Eureka
	1884 #Santa Rosa
	1885 #Redding
	1888 #Sacramento
	1889 #San Francisco
	1891 #Santa Barbara
	1883 #Fresno
	1887 #Los Angeles
	1886 #San Diego
	1892 #San Bernardino
	1901 #Tucson
	1900 #Phoenix 
	1902 #Flagstaff
	1904 #Albuquerque
	1906 #Santa Fe 
	1905 #Roswell
	1903 #Carlsbad
	1923 #El Paso
	1927 #Abilene
	1920 #Lubbock
	1921 #Amarillo
	1913 #Oklahoma City
	1911 #Lawton
	1924 #Dallas
	1925 #Austin
	1926 #San Antonio 
	1922 #Corpus Christi
	1928 #Houston
	1916 #Ardmore
	1919 #Tyler
	1917 #Fort Smith
	1918 #Little Rock
	1930 #Shreveport
	1932 #Baton Rouge
	1934 #Lafayette
	1929 #Monroe
	1933 #Pine Bluff
	1915 #Jonesboro 
	1938 #Vicksburg
	1937 #Natchez
	1931 #New Orleans
	1944 #Mobile
	1939 #Jackson
	1935 #Tupelo
	1940 #Memphis
	1943 #Nashville
	1941 #Chattanooga
	1946 #Birmingham Al
	1950 #Pensacola
	1947 #Montgomery
	1945 #Gadsden
	1942 #Knoxville
	1964 #Asheville
	1955 #Atlanta
	1959 #Augusta
	1954 #Macon
	1951 #Tallahassee 
	1948 #Tampa 
	1936 #Tuscaloosa
    1953 #Miami  
	1949 #Orlando
	1952 #Jacksonville 
	1956 #Savannah
	1960 #Charleston
	1958 #Greenville
	1957 #Columbia 
	1962 #Charlotte
	1963 #Wilmington
	1961 #Raleigh
	#Alaska#
	2141 #Juneau
	2147 #Valdez
	2140 #Fairbanks
	2142 #Anchorage
	2146 #Tanana
    2145 #Nome
	2144 #Bethel
	2139 #Dillingham
	2143 #Chignik
	2150 #Unalaska
	2151 #Dutch Habor
	2174 #Attu Island
	#Islands#	 
	1683 #Guam
	1673 #Wake
	1751 #Mayerton
	1733 #Pago Pago
	1745 #Jarvis Island
	1747 #Palmyra
	1738 #Johnston
	1739 #Midway
	1765 #Puerto Rico
	#Hawaii#
	1735 #Kauai
	1734 #Pearl Harbor
	1737 #Maui
	1736 #Hawaii
	#Panama canal#
	889 #Balboa
	#Guantanamo
    1778 #Guantanamo Bay Naval Base  
                              }  


    controlledprovinces    = {  
	1786 #Presque Isle
	1784 #Bangor
	1787 #Concord 
	1785 #Lewiston
	1790 #Burlington
	1794 #Watertown
	1844 #Flint
	1843 #Marquette
	1849 #Duluth
	1854 #Grand Forks
	1852 #Minot
	1853 #Fort Peck
	1864 #Great Falls
	1865 #Missoula
	1861 #Coeur d'Alene
	1875 #Wenatchee
	1874 #Seattle
	1877 #Tacoma
	1873 #Yakima 
	1872 #Spokane
	1876 #Walla Walla
	1871 #Boise
	1863 #Helena
	1862 #Bozeman
	1867 #Glendive
	1856 #Bismarck
	1855 #Fargo
	1847 #Minneapolis
	1850 #Saint Paul
	1848 #Superior
	1840 #Eau Claire
	1841 #Greenbay
	1842 #Grand Rapids
	1845 #Detroit
	1791 #Buffalo
	1792 #Syracuse
	1793 #Albany
	1788 #Hartford
	1789 #Boston
	1796 #Providence
	1799 #Newburgh
	1800 #Binghampton
	1797 #Newark
	1804 #Scranton
	1795 #New York
	1803 #Williamsport
	1801 #Harrisburg
	1805 #Philadelphia
	1807 #Cape Charles 
	1809 #Washington 
	1808 #Baltimore
	1802 #Altoona
	1798 #Warren
	1824 #Erie
	1825 #Cleveland
	1821 #Columbus
	1806 #Pittsburgh
	1810 #Clakrsburg
	1814 #Arlington
	1813 #Richmond
	1812 #Norfolk
	1815 #Danville
	1816 #Charlottesville
	1818 #Roanoke
	1817 #Beckley
	1811 #Huntington
	1822 #Toledo
	1823 #Cincinnati
	1820 #Lexington
	1819 #Louisville
	1827 #Evansville
	1828 #Indianapolis 
	1826 #Fort Wayne
	1832 #Chicago
	1839 #Milwaukee
	1829 #Peoria 
	1830 #Decatur
	1831 #Belleville
	1833 #Saint Louis
    1835 #Saint Chalres
	1837 #Cedar Rapids
	1846 #Rochester
	1838 #Des Moines
	1834 #Saint Joseph
	1836 #Springfield 
	1912 #Tulsa
	1914 #Kansas City
	1859 #Lincoln
	1860 #Omaha
	1857 #Sioux Falls
	1851 #Miles City
	1858 #Rapid City
	1908 #Denver
	1910 #Wichita
	1909 #Colorado Springs
	1907 #Cheyenne
	1866 #Casper
	1868 #Billings
	1898 #Rock Springs
	1897 #Grand Junction
	1899 #Saint George
	1896 #Salt Lake City
	1869 #Idaho Falls
	1870 #Rexburg
	1881 #Twin Falls
	1894 #Elko
	1893 #Las Vegas
	1895 #Reno
	1880 #Klamath Falls
	1882 #Bend
	1878 #Portland
	1879 #Eugene
	1890 #Eureka
	1884 #Santa Rosa
	1885 #Redding
	1888 #Sacramento
	1889 #San Francisco
	1891 #Santa Barbara
	1883 #Fresno
	1887 #Los Angeles
	1886 #San Diego
	1892 #San Bernardino
	1901 #Tucson
	1900 #Phoenix 
	1902 #Flagstaff
	1904 #Albuquerque
	1906 #Santa Fe 
	1905 #Roswell
	1903 #Carlsbad
	1923 #El Paso
	1927 #Abilene
	1920 #Lubbock
	1921 #Amarillo
	1913 #Oklahoma City
	1911 #Lawton
	1924 #Dallas
	1925 #Austin
	1926 #San Antonio 
	1922 #Corpus Christi
	1928 #Houston
	1919 #Tyler
	1916 #Ardmore
	1917 #Fort Smith
	1918 #Little Rock
	1930 #Shreveport
	1932 #Baton Rouge
	1934 #Lafayette
	1929 #Monroe
	1933 #Pine Bluff
	1915 #Jonesboro 
	1938 #Vicksburg
	1937 #Natchez
	1931 #New Orleans
	1944 #Mobile
	1939 #Jackson
	1935 #Tupelo
	1940 #Memphis
	1943 #Nashville
	1941 #Chattanooga
	1946 #Birmingham Al
	1950 #Pensacola
	1947 #Montgomery
	1945 #Gadsden
	1942 #Knoxville
	1964 #Asheville
	1955 #Atlanta
	1959 #Augusta
	1954 #Macon
	1951 #Tallahassee 
	1948 #Tampa 
	1936 #Tuscaloosa
    1953 #Miami  
	1949 #Orlando
	1952 #Jacksonville 
	1956 #Savannah
	1960 #Charleston
	1958 #Greenville
	1957 #Columbia 
	1962 #Charlotte
	1963 #Wilmington
	1961 #Raleigh
	#Alaska#
	2141 #Juneau
	2147 #Valdez
	2140 #Fairbanks
	2142 #Anchorage
	2146 #Tanana
    2145 #Nome
	2144 #Bethel
	2139 #Dillingham
	2143 #Chignik
	2150 #Unalaska
	2151 #Dutch Habor
	2174 #Attu Island
	#Islands#	 
	1683 #Guam
	1673 #Wake
	1751 #Mayerton
	1733 #Pago Pago
	1745 #Jarvis Island
	1747 #Palmyra
	1738 #Johnston
	1739 #Midway
	1765 #Puerto Rico
	#Hawaii#
	1735 #Kauai
	1734 #Pearl Harbor
	1737 #Maui
	1736 #Hawaii
	#Panama canal#
	889 #Balboa
	#Guantanamo
    1778 #Guantanamo Bay Naval Base
	}  
    # early esc car  
    # USA 1936 techs  
    # ######################  
    techapps = {
		#Static Defense
		6680
  
#Improved Light carrier 
12100 12110 12120	
#Early Fighter  
4500 4510 4520 4530 4540 4550 4010 4020	
#Early Bomber 
4600 4610 4620 4630 4120 4130	
#Basic Air Transport 
4290 4250	
#Basic Strategic Bomber 
4800 4810 4820 4220 	
#Armoured Cars 
2860 2870 2880 2020
#Great War Tank 
7600 7610 2620 2010 2630
#Great War Heavy Field Artillery 
2290 2300 2310 	
#Early Static Anti-Air Artillery 
2800 2450 21180 21190 21200
#Basic Anti-Air Artillery Brigade 
2810 2820 2510
#Great War Infantry Division  
1010  1020 1030 1040 1050 1060 
#1930 Cavalry Division  
13060 13070 13080 1310 1320 1330 1340 1350 1360 1370
#Interbellum 1930 Supply 
1910 1920 1930 1940 1950 1960 1970 1980
#Mechanized Agriculture 
5700 5710 5010 5020
#Basic Machine Tools 
5810 5820 5050 5830 5060 5070
#Improved Construction Engineering 
5800 5080 5090 
#Computers and cryptografi
5310 54010 54020 54030 5316 5326 5327
#Refining
5190
#Faculty of Atomic Research 
5470
#Medicine
5600 5610 5620 5630
#Exp. Rocket
5560
#Multirole fighter
4300 4310 4320 4330 4340
#ww1 strategic bomber
4800 4810 4820
#ww1 navalbomber
4700 4710
#Naval Infantry
1560 1570 1580
#Mountain
1160  1170  1180  1190  
#Seaplanes
4740  4750  4760  4770
#Engineers
1830 1840 1850 1860
#CAG 34
4900 4910 4920
#Torpedo & ASW 18
3720 3730 3736 3740 3750 3900
#Improved Destroyer 
3010 3020 3030 3040 3050 3060
#Interwar Light Cruiser 
3110 3120 3130 3140 3150 3160
#Improved Heavy Cruiser 
3210 3220 3230 3240 3250 3260
#Improved Heavy Cruiser 
3210 3220 3230 3240 3250 3260
#Heavy Battlecruiser
3310 3320 3330
#Early Battleship 
3410 3420 3430 3440 3450 3456 3460 3470
#Fleet Carrier 
3510 3520 3530
#Short Range Submarine 
3610 3620 3630 3640 3650
#Great War Hospital System 
14000 14010 14020
#Troopships
3810 5820

# WWI Land Doctrines - Entente: eng fra ita usa bel hol jap 
6500 6510  6530 6540 6580 6600 6610 6620 6630 6640 6650 6660 6670 6910
# WWII Land Doctrines - Firepower Focus
6010 6020

#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 9140

# Engagement Theories
8010 8020 8030 8040 8050 8060 8070 8080
# Naval Supremacy
8100 8110 8120 8150 8160 8200
# Naval Interdiction
8500 8510 8550 8600
# Engagement Tactics - Fleet-in-Being colum
8900 8910 8920 8930 8940 8950
# Subsidiary Carrier Role
81650
# Carrier - Scouting Focus
81850
# Logistic Support
82500  
# Amphibious Warfare
82300

} 

blueprints = { 81880 81890 }

inventions = { 3000027 }
    policy =  
    {  date              = {  year = 1942 month = january day = 0  }  
     democratic        = 9 
      political_left    = 7
      freedom           = 9  
      free_market       = 9
      professional_army = 2  
      defense_lobby     = 3  
      interventionism   = 2  
     }  
    headofstate            = {  type = 9 id = 240001  }  
    headofgovernment       = {  type = 9 id = 240232  } # Harry Hopkins  
    foreignminister        = {  type = 9 id = 240003  }  
    armamentminister       = {  type = 9 id = 240004  }  
    ministerofsecurity     = {  type = 9 id = 240005  }  
    ministerofintelligence = {  type = 9 id = 240006  }  
    chiefofstaff           = {  type = 9 id = 240007  }  
    chiefofarmy            = {  type = 9 id = 240008  }  
    chiefofnavy            = {  type = 9 id = 240121  }  
    chiefofair             = {  type = 9 id = 240010  }  
    landunit =  
    {  location = 1789  
      name     = "I Corps"  
      id       = {  type = 14800 id = 601  }  
      Division =  
      {  id   = {  type = 14800 id = 602  }  
        name = "26th 'Yankee' Division"
		strength = 10		
        type = infantry  
		model    = 6
       }  
      Division =  
      {  id   = {  type = 14800 id = 603  }  
        name = "43rd 'Winged Victory' Division"
		strength = 10		
        type = infantry  
		model    = 6
       }  
     }  
    landunit =  
    {  location = 1795  
      name     = "II Corps"  
      id       = {  type = 14800 id = 604  }  
      Division =  
      {  id   = {  type = 14800 id = 605  }  
        name = "1st 'Big Red One' Division" 
		strength = 100
		type = infantry  
		model    = 7
		extra = artillery
		brigade_model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 606  }  
        name = "21st Cavalry Division"  
		strength = 10
        type = cavalry  
		model    = 5
       }  
      Division =  
      {  id   = {  type = 14800 id = 607  }  
        name = "44th Infantry Division"
		strength = 10		
        type = infantry  
		model    = 6
       }  
      Division =  
      {  id   = {  type = 14800 id = 608  }  
        name = "78th 'Lightning' Division"
		strength = 5		
        type = infantry  
		model    = 5
       }  
     }  
    landunit =  
    {  location = 1808  
       leader   = 240112 # Craig
      name     = "III Corps"  
      id       = {  type = 14800 id = 609  }  
     Division = 
     {  id       = {  type = 13500 id = 610  } 
       name     = "U.S. Army General Staff" 
       type     = hq 
       model    = 2 
       strength = 100 
      } 
      Division =  
      {  id   = {  type = 14800 id = 611  }  
        name = "28th 'Keystone' Division"
		strength = 10		
        type = infantry  
		model    = 6
       }  
      Division =  
      {  id   = {  type = 14800 id = 612  }  
        name = "29th 'Blue and Gray' Division"
		strength = 10		
        type = infantry  
		model    = 6
       }  
     }  
    landunit =  
    {  location = 1955  
      name     = "IV Corps"  
      id       = {  type = 14800 id = 613  }  
      Division =  
      {  id   = {  type = 14800 id = 614  }  
        name = "23rd Cavalry Division"  
		strength = 10
        type = cavalry  
		model    = 5
       }  
      Division =  
      {  id   = {  type = 14800 id = 615  }  
        name = "31st Infantry Division"
		strength = 10		
        type = infantry  
		model    = 6
       }  
     }  
    landunit =  
    {  location = 1821  
      name     = "V Corps"  
      id       = {  type = 14800 id = 616  }  
      Division =  
      {  id   = {  type = 14800 id = 617  }  
        name = "22nd Cavalry Division"  
		strength = 10
        type = cavalry  
		model    = 5
       }  
      Division =  
      {  id   = {  type = 14800 id = 618  }  
        name = "37th 'Buckeye' Division"
		strength = 10		
        type = infantry  
		model    = 6
       }  
      Division =  
      {  id   = {  type = 14800 id = 619  }  
        name = "100th 'Century' Division"
		strength = 5		
        type = infantry  
		model    = 5
       }  
     }  
    landunit =  
    {  location = 1832  
      name     = "VI Corps"  
      id       = {  type = 14800 id = 620  }  
      Division =  
      {  id   = {  type = 14800 id = 621  }  
        name = "94th 'Pilgrim' Division"
		strength = 5		
        type = infantry  
		model    = 5
       }  
     }  
    landunit =  
    {  location = 1859  
      name     = "VII Corps"  
      id       = {  type = 14800 id = 622  }  
      Division =  
      {  id   = {  type = 14800 id = 623  }  
        name = "24th Cavalry Division"  
		strength = 10
        type = cavalry  
		model    = 6
       }  
      Division =  
      {  id   = {  type = 14800 id = 624  }  
        name = "34th 'Red Bull' Division"
		strength = 10		
        type = infantry  
		model    = 6
       }  
      Division =  
      {  id   = {  type = 14800 id = 625  }  
        name = "35th 'Santa Fe' Division"
		strength = 10		
        type = infantry  
		model    = 6
       }  
     }  
    landunit =  
    {  location = 1926  
      name     = "VIII Corps"  
      id       = {  type = 14800 id = 626  }  
      Division =  
      {  id   = {  type = 14800 id = 627  }  
        name = "2nd 'Indianhead' Division" 
		strength = 100
		type = infantry  
		model    = 7
		extra = artillery
		brigade_model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 628  }  
        name = "1st Cavalry 'The 1st Team' Div."  
		strength = 100
        type = cavalry  
		model    = 7
	extra = armored_car
		brigade_model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 629  }  
        name = "45th 'Thunderbird' Division"
		strength = 10		
        type = infantry  
		model    = 6
       }  
      Division =  
      {  id   = {  type = 14800 id = 630  }  
        name = "95th 'Victory' Division"
		strength = 5		
        type = infantry  
		model    = 5
       }  
     }  
    landunit =  
    {  location = 1889  
      name     = "IX Corps"  
      id       = {  type = 14800 id = 631  }  
      Division =  
      {  id   = {  type = 14800 id = 632  }  
        name = "3rd 'Rock of the Marne' Division" 
		strength = 100
		type = infantry  
		model    = 7
		extra = artillery
		brigade_model = 3
       }  
      Division =  
      {  id   = {  type = 14800 id = 633  }  
        name = "40th 'Sunshine' Division"
		strength = 10		
        type = infantry  
		model    = 6
       }  
      Division =  
      {  id   = {  type = 14800 id = 634  }  
        name = "41st 'Sunsetters' Division"
		strength = 10		
        type = infantry  
		model    = 6
       }  
      Division =  
      {  id   = {  type = 14800 id = 635  }  
        name = "91st 'Wild West' Division"
		strength = 5		
        type = infantry  
		model    = 5
       }  
      Division =  
      {  id   = {  type = 14800 id = 636  }  
        name = "104th 'Timberwolf' Division"
		strength = 5		
        type = infantry  
		model    = 5
       }  
     }  
	landunit = {
		location = 1886  
		name     = "1st US Marine 'The Old Breed' Div."  
		id       = {  type = 14800 id = 641  }  
		division = {
			id       = {  type = 14800 id = 642  }  
			name     = "1st US Marine 'The Old Breed' Div." 
			strength = 35
			type     = marine
			model    = 2
		}  
	}  
    landunit = {
		location = 1886  
		name     = "2nd US Marine 'Follow Me' Division"  
		id       = {  type = 14800 id = 639  }  
		division = {
			id       = {  type = 14800 id = 640  }  
			name     = "2nd US Marine 'Follow Me' Division" 
			strength = 35
			type     = marine
			model    = 2
		}  
	}
    landunit =  
    {  location = 1734  
      name     = "Hawaiian Department"  
      id       = {  type = 14800 id = 643  }  
      Division =  
      {  id     = {  type = 14800 id = 644  }  
        name   = "Hawaiian Division"  
        type   = infantry  
		model    = 7
        strength = 100 
	extra = engineer
		brigade_model = 3
		locked = yes  
       }  
     }  
    landunit =  
    {  location = 1565  
      name     = "Philippine Department"  
      id       = {  type = 14800 id = 645  }  
      Division =  
      {  id     = {  type = 14800 id = 646  }  
        name   = "Philippine Division"  
        type   = infantry  
		model    = 7
        strength = 100 
	extra = engineer
		brigade_model = 3
		locked = yes  
       }  
     }  
    landunit =  
    {  id       = {  type = 14800 id = 647  }  
      name     = "Panama Canal Department"  
      location = 889  
      Division =  
      {  id     = {  type = 14800 id = 648  }  
        name   = "Panama Canal Garrison"  
		strength = 100
        type   = garrison  
        model  = 3
        locked = yes  
       }  
     }  
	 
	# US PACIFIC FLEET-SAN DIEGO, CALIFORNIA  
	# Battleship Division 1  
	navalunit =  {
		name = "USN Battleship Fleet 1"  
		id = {  type = 14800 id = 26  }  
		location = 1886  
		base     = 1886  
		division = {
			id = {  type = 14800 id = 28  }  
			name = "USS Nevada"  
			type = battleship  
			model = 4
			extra1 = floatplane
			brigade_model1 = 4
			extra2 = naval_anti_air_l
			extra3 = naval_improved_hull_l
			extra4 = naval_fire_controll_l
		}
		division = {
			id = {  type = 14800 id = 29  }  
			name  = "USS Arizona"  
			type  = battleship  
			model = 4
			extra1 = floatplane
			brigade_model1 = 4
			extra2 = naval_anti_air_l
			extra3 = naval_improved_hull_l
		}  
		division = {
			id    = {  type = 14800 id = 30  }  
			name  = "USS Pennsylvania"  
			type  = battleship
			model = 4  
			extra1 = floatplane
			brigade_model1 = 4
			extra2 = naval_anti_air_l
			extra3 = naval_improved_hull_l
		}  
		division = {
			id    = {  type = 14800 id = 49  }  
			name  = "USS Chicago"  
			type  = heavy_cruiser  
			model = 3
			extra1 = floatplane
			brigade_model1 = 4	
		}  
		division = {
			id    = {  type = 14800 id = 50  }  
			name  = "USS Indianapolis"  
			type  = heavy_cruiser  
			model = 3  
			extra1 = floatplane
			brigade_model1 = 4
		}  
		division = {
			id    = {  type = 14800 id = 52  }  
			name  = "USS Northampton"  
			type  = heavy_cruiser  
			model = 3  
			extra1 = floatplane
			brigade_model1 = 4
		}
		division = {
			id    = {  type = 14800 id = 2291  }  
			name  = "Destroyer Division 11"  
			type  = destroyer  
			model = 3  
		} 
		division = {
			id    = {  type = 14800 id = 2292  }  
			name  = "Destroyer Division 12"  
			type  = destroyer  
			model = 3  
		}
		division = {
			id    = {  type = 14800 id = 2293  }  
			name  = "Destroyer Division 28"  
			type  = destroyer  
			model = 3  
		}
		division = {
			id    = {  type = 14800 id = 2294  }  
			name  = "Destroyer Division 30"  
			type  = destroyer  
			model = 3
		}  
		division = {
			id    = {  type = 14800 id = 2295  }  
			name  = "Destroyer Division 33"  
			type  = destroyer  
			model = 3  
		}
	}
    # Battleship Division 2  
	navalunit = {
		name     = "USN Battleship Fleet 2"  
		id       = {  type = 14800 id = 31  }  
		location = 1886  
		base     = 1886  
		division = {
			id    = {  type = 14800 id = 33  }  
			name  = "USS Oklahoma"  
			type  = battleship  
			model = 4  
			extra1 = floatplane
			brigade_model1 = 4
			extra2 = naval_anti_air_l
		}  
		division = {
			id    = {  type = 14800 id = 34  }  
			name  = "USS Tennessee"  
			type  = battleship  
			model = 5
			extra1 = floatplane
			brigade_model1 = 4		
			extra2 = naval_anti_air_l
		}  
		division = {
			id    = {  type = 14800 id = 35  }  
			name  = "USS California"  
			type  = battleship  
			model = 5
			extra1 = floatplane
			brigade_model1 = 4 
			extra2 = naval_anti_air_l
			extra3 = naval_fire_controll_l
		}  
		division = {
			id    = {  type = 14800 id = 53  }  
			name  = "USS Chester"  
			type  = heavy_cruiser  
			model = 3  
			extra1 = floatplane
			brigade_model1 = 4
		}  
		division = {
			id    = {  type = 14800 id = 54  }  
			name  = "USS Louisville"  
			type  = heavy_cruiser  
			model = 3  
			extra1 = floatplane
			brigade_model1 = 4
		}  
		division = {
			id    = {  type = 14800 id = 2297  }  
			name  = "Destroyer Division 35"  
			type  = destroyer  
			model = 3  
		}
		division = {
			id    = {  type = 14800 id = 2298  }  
			name  = "Destroyer Division 36"  
			type  = destroyer  
			model = 3  
		}
		division = {
			id    = {  type = 14800 id = 2299  }  
			name  = "Destroyer Division 37"  
			type  = destroyer  
			model = 3  
		}
	}
	# Battleship Division 4  
	navalunit = {
		name     = "USN Battleship Fleet 4"  
		id       = {  type = 14800 id = 36  }  
		location = 1886  
		base     = 1886  
		division = {
			id    = {  type = 14800 id = 37  }  
			name  = "USS Colorado"  
			type  = battleship  
			model = 6  
			extra1 = floatplane
			brigade_model1 = 4
			extra2 = naval_anti_air_l
		}
		division = {
			id    = {  type = 14800 id = 38  }  
			name  = "USS West Virginia"  
			type  = battleship  
			model = 6
			extra1 = floatplane
			brigade_model1 = 4
			extra2 = naval_anti_air_l
		}
		division = {
			id    = {  type = 14800 id = 39  }  
			name  = "USS Maryland"  
			type  = battleship  
			model = 6
			extra1 = floatplane
			brigade_model1 = 4
			extra2 = naval_anti_air_l
		}
		division = {
			id    = {  type = 14800 id = 57  }  
			name  = "USS New Orleans"  
			type  = heavy_cruiser  
			model = 4  
			extra1 = floatplane
			brigade_model1 = 4
		}
		division = {
			id    = {  type = 14800 id = 58  }  
			name  = "USS Astoria"  
			type  = heavy_cruiser  
			model = 4 
			extra1 = floatplane
			brigade_model1 = 4		
		}
		division = {
			id    = {  type = 14800 id = 59  }  
			name  = "USS Minneapolis"  
			type  = heavy_cruiser  
			model = 4  
			extra1 = floatplane
			brigade_model1 = 4
		}
		division = {
			id    = {  type = 14800 id = 41  }  
			name  = "USS Richmond"  
			type  = light_cruiser  
			model = 3  
		}
		division = {
			id    = {  type = 14800 id = 42  }  
			name  = "USS Trenton"  
			type  = light_cruiser  
			model = 3  
		}
		division = {
			id    = {  type = 14800 id = 43  }  
			name  = "USS Concord"  
			type  = light_cruiser  
			model = 3  
		}
		division = {
			id    = {  type = 14800 id = 44  }  
			name  = "USS Raleigh"  
			type  = light_cruiser  
			model = 3  
		}
		division = {
			id    = {  type = 14800 id = 45  }  
			name  = "USS Detroit"  
			type  = light_cruiser  
			model = 3  
		}
		division = {
			id    = {  type = 14800 id = 63  }  
			name  = "Destroyer Division 2"  
			type  = destroyer  
			model = 3  
		}  
	}
	# Cruiser Division 3  
	navalunit = {
		name     = "USN Cruiser Fleet 3"  
		id       = {  type = 14800 id = 40  }  
		location = 1886  
		base     = 1886  
		division = {
			id    = {  type = 14800 id = 47  }  
			name  = "USS Pensacola"  
			type  = heavy_cruiser  
			model = 3  
			extra1 = floatplane
			brigade_model1 = 4
		}
		division = {
			id    = {  type = 14800 id = 48  }  
			name  = "USS Salt Lake City"  
			type  = heavy_cruiser  
			model = 3  
			extra1 = floatplane
			brigade_model1 = 4
		}
		division = {
			id    = {  type = 14800 id = 60  }  
			name  = "USS San Francisco"  
			type  = heavy_cruiser  
			model = 4  
			extra1 = floatplane
			brigade_model1 = 4		
		}
		division = {
			id    = {  type = 14800 id = 2303  }  
			name  = "Destroyer Division 47"  
			type  = destroyer  
			model = 3
		}
		division = {
			id    = {  type = 14800 id = 2304  }  
			name  = "Destroyer Division 43"  
			type  = destroyer  
			model = 3
		}
		division = {
			id    = {  type = 14800 id = 2305  }  
			name  = "Destroyer Division 42"  
			type  = destroyer  
			model = 3
		}
	}
	navalunit = {
		name     = "USN Carrier Fleet 1"  
		id       = {  type = 14800 id = 46  }  
		location = 1886  
		base     = 1886  
		division = {
			id            = {  type = 14800 id = 27  }  
			name          = "USS Lexington"  
			type          = carrier  
			model         = 0  
			extra         = CAG  
			brigade_model = 2  
		}
		division = {
			id   = {  type = 14800 id = 162  }  
			name = "USS Langley"  
			type = escort_carrier  
			model = 1
		}
		division = {
			id    = {  type = 14800 id = 2308  }  
			name  = "Destroyer Division 31"  
			type  = destroyer  
			model = 3  
		}
		division = {
			id    = {  type = 14800 id = 62  }  
			name  = "Destroyer Division 1"  
			type  = destroyer  
			model = 3  
		}
		division = {
			id    = {  type = 14800 id = 64  }  
			name  = "Destroyer Division 3"  
			type  = destroyer  
			model = 3  
		}
	}
	navalunit = {
		name     = "Pacific Transport Fleet 1"  
		id       = {  type = 14800 id = 51  }  
		location = 1886  
		base     = 1886  
		division = {
			id   = {  type = 14800 id = 147  }  
			name = "Charles Goodyear Flotilla"  
			type = transport  
			model = 1
		}  
		division = {
			id   = {  type = 14800 id = 148  }  
			name = "Anthony Wayne Flotilla"  
			type = transport  
			model = 1
		}
		division = {
			id   = {  type = 14800 id = 149  }  
			name = "John Hancock Flotilla"  
			type = transport  
			model = 1
		}
		division = {
			id    = {  type = 14800 id = 2306  }  
			name  = "Destroyer Division 41"  
			type  = destroyer  
			model = 3
		}
		division = {
			id    = {  type = 14800 id = 2307  }  
			name  = "Destroyer Division 32"  
			type  = destroyer  
			model = 3  
		}
		division = {
			id    = {  type = 14800 id = 2309  }  
			name  = "Destroyer Division 29"  
			type  = destroyer  
			model = 3  
		}
	}
	navalunit = {
		name     = "Pacific Transport Fleet 2"  
		id       = {  type = 14800 id = 56  }  
		location = 1886  
		base     = 1886  
		division = {
			id   = {  type = 14800 id = 153  }  
			name = "George A. Custer Flotilla"  
			type = transport  
			model = 1
		}  
		division = {
			id   = {  type = 14800 id = 154  }  
			name = "August Belmont Flotilla"  
			type = transport  
			model = 1
		}
		division = {
			id   = {  type = 14800 id = 156  }  
			name = "Emily Dickinson Flotilla"  
			type = transport  
			model = 1
		}
		division = {
			id    = {  type = 14800 id = 2310  }  
			name  = "Destroyer Division 25"  
			type  = destroyer  
			model = 3
		}
		division = {
			id    = {  type = 14800 id = 2311  }  
			name  = "Destroyer Division 22"  
			type  = destroyer  
			model = 3  
		}
		division = {
			id    = {  type = 14800 id = 2312  }  
			name  = "Destroyer Division 15"  
			type  = destroyer  
			model = 3
		}
	}
    navalunit = {
		name     = "Pacific Transport Fleet 3"  
		id       = {  type = 14800 id = 61  }  
		location = 1886  
		base     = 1886  
		division = {
			id   = {  type = 14800 id = 150  }  
			name = "Samuel Dexter Flotilla"  
			type = transport  
			model = 1
		}
		division = {
			id   = {  type = 14800 id = 151  }  
			name = "Stephen C. Crane Flotilla"  
			type = transport  
			model = 1
		}
		division = {
			id   = {  type = 14800 id = 152  }  
			name = "William McKinley Flotilla"  
			type = transport  
			model = 1
		}
	}
	navalunit = {
		name     = "Pacific Submarine Fleet"  
		id       = {  type = 14800 id = 74  }  
		location = 1886  
		base     = 1886  
		division = {
			id    = {  type = 14800 id = 75  }  
			name  = "Submarine Division 1"  
			type  = submarine  
			model = 2  
		}
		division = {
			id    = {  type = 14800 id = 76  }  
			name  = "Submarine Division 2"  
			type  = submarine  
			model = 2  
		}
		division = {
			id    = {  type = 14800 id = 77  }  
			name  = "Submarine Division 3"  
			type  = submarine  
			model = 2
		}
	}
	navalunit = {
		location = 1565  
		base     = 1565  
		id       = {  type = 14800 id = 81  }  
		name     = "Asiatic Fleet"  
		division = {
			id    = {  type = 14800 id = 112  }  
			name  = "USS Augusta"  
			type  = heavy_cruiser  
			model = 3  
			extra1 = floatplane
			brigade_model1 = 4			
		}
		division = {
			id    = {  type = 14800 id = 82  }  
			name  = "Destroyer Division 13"  
			type  = destroyer  
			model = 2
		}
		division = {
			id    = {  type = 14800 id = 83  }  
			name  = "Destroyer Division 14"  
			type  = destroyer  
			model = 2
		}
	}
	navalunit = {
		location = 1874  
		base     = 1874  
		id       = {  type = 14800 id = 89  }  
		name     = "USN Seattle Fleet"  
		division = {
			id       = {  type = 14800 id = 90  }  
			name     = "USS Marblehead"  
			strength = 100  
			type     = light_cruiser  
			model    = 3  
		}
		division = {
			id    = {  type = 14800 id = 91  }  
			name  = "Destroyer Division 16"  
			type  = destroyer  
			model = 2  
		}
	}
	navalunit = {
		location = 1874  
		base     = 1874  
		id       = {  type = 14800 id = 92  }  
		name     = "3rd USN Submarine Fleet"  
		division = {
			id    = {  type = 14800 id = 94  }  
			name  = "Submarine Division 10"  
			type  = submarine  
			model = 2
		}
	}
	navalunit = {
		location = 889  
		base     = 889  
		id       = {  type = 14800 id = 95  }  
		name     = "USN Carribean Fleet"  
		division = {
			id    = {  type = 14800 id = 96  }  
			name  = "Destroyer Division 17"  
			type  = destroyer  
			model = 2 
		}
	}
	navalunit = {
		location = 889  
		base     = 889  
		id       = {  type = 14800 id = 2322  }  
		name     = "4th USN Submarine Fleet"  
		division = {
			id    = {  type = 14800 id = 97  }  
			name  = "Submarine Division 11"  
			type  = submarine  
			model = 2 
		}
	}
	navalunit = {
		location = 1812  
		base     = 1812  
		id       = {  type = 14800 id = 98  }  
		name     = "USN Battleship Fleet 3"  
		division = {
			id    = {  type = 14800 id = 103  }  
			name  = "USS Arkansas"  
			type  = battleship  
			model = 2 
			extra1 = floatplane
			brigade_model1 = 4
			extra2 = naval_improved_hull_l
		}
		division = {
			id    = {  type = 14800 id = 993  }  
			name  = "USS Wyoming"  
			type  = battleship  
			model = 2 
			extra1 = floatplane
			brigade_model1 = 4
			extra2 = naval_improved_hull_l
		}
		division = {
			id    = {  type = 14800 id = 107  }  
			name  = "USS Omaha"  
			type  = light_cruiser  
			model = 3  
		}
		division = {
			id    = {  type = 14800 id = 110  }  
			name  = "USS Memphis"  
			type  = light_cruiser  
			model = 3  
		}
		division = {
			id    = {  type = 14800 id = 194  }  
			name  = "Destroyer Division 45"  
			type  = destroyer  
			model = 3
		}
		division = {
			id    = {  type = 14800 id = 195  }  
			name  = "Destroyer Division 46"  
			type  = destroyer  
			model = 3  
		}
	}
	navalunit = {
		location = 1812  
		base     = 1812  
		id       = {  type = 14800 id = 102  }  
		name     = "Atlantic Transport Fleet 1"  
		division = {
			id   = {  type = 14800 id = 143  }  
			name = "Dolly Madison Flotilla"  
			type = transport  
			model = 1
		}
		division = {
			id   = {  type = 14800 id = 144  }  
			name = "Frederick Douglass Flotilla"  
			type = transport  
			model = 1
		}
		division = {
			id   = {  type = 14800 id = 145  }  
			name = "Clara Barton Flotilla"  
			type = transport  
			model = 1
		}
		division = {
			id    = {  type = 14800 id = 117  }  
			name  = "Destroyer Division 19"  
			type  = destroyer  
			model = 3
		}
		division = {
			id    = {  type = 14800 id = 118  }  
			name  = "Destroyer Division 20"  
			type  = destroyer  
			model = 3  
		}
	}
	navalunit = {
		location = 1812  
		base     = 1812  
		id       = {  type = 14800 id = 106  }  
		name     = "USN Cruiser Fleet 2"  
		division = {
			id       = {  type = 14800 id = 93  }  
			name     = "USS Houston"  
			strength = 100  
			type     = heavy_cruiser  
			model    = 3  
			extra1 = floatplane
			brigade_model1 = 4
		}
		division = {
			id    = {  type = 14800 id = 113  }  
			name  = "USS Tuscaloosa"  
			type  = heavy_cruiser  
			model = 4  
			extra1 = floatplane
			brigade_model1 = 4
		}
		division = {
			id    = {  type = 14800 id = 193  }  
			name  = "Destroyer Division 44"  
			type  = destroyer  
			model = 3
		}
		division = {
			id    = {  type = 14800 id = 176  }  
			name  = "Destroyer Division 27"  
			type  = destroyer  
			model = 3
		}
	}
	navalunit = {
		location = 1812  
		base     = 1812  
		id       = {  type = 14800 id = 111  }  
		name     = "Atlantic Transport Fleet 2"  
		division = {
			id   = {  type = 14800 id = 134  }  
			name = "Abner Doubleday Flotilla"  
			type = transport
			model = 1
		}
		division = {
			id   = {  type = 14800 id = 135  }  
			name = "Brigham Young Flotilla"  
			type = transport  
			model = 1
		}
		division = {
			id   = {  type = 14800 id = 136  }  
			name = "William B. Travis Flotilla"  
			type = transport  
			model = 1
		}
		division = {
			id    = {  type = 14800 id = 121  }  
			name  = "Destroyer Division 23"  
			type  = destroyer  
			model = 3
		}
		division = {
			id    = {  type = 14800 id = 172  }  
			name  = "Destroyer Division 24"  
			type  = destroyer  
			model = 3  
		}
	}
	navalunit = {
		location = 1812  
		base     = 1812  
		id       = {  type = 14800 id = 114  }  
		name     = "USS Ranger Taskforce"  
		division = {
			id            = {  type = 14800 id = 115  }  
			name          = "USS Ranger"  
			type          = carrier  
			model         = 1  
			extra         = cag  
			brigade_model = 2  
		}
		division = {
			id    = {  type = 14800 id = 116  }  
			name  = "Destroyer Division 18"  
			type  = destroyer  
			model = 3  
		}
	}
	navalunit = {
		location = 1812  
		base     = 1812  
		id       = {  type = 14800 id = 122  }  
		name     = "Atlantic Submarine Fleet"  
		division = {
			id    = {  type = 14800 id = 123  }  
			name  = "Submarine Division 12"  
			type  = submarine  
			model = 2
		}
		division = {
			id    = {  type = 14800 id = 124  }  
			name  = "Submarine Division 13"  
			type  = submarine  
			model = 2  
		}
		division = {
			id    = {  type = 14800 id = 125  }  
			name  = "Submarine Division 14"  
			type  = submarine  
			model = 2  
		}
	}
	navalunit = {
		location = 1812  
		base     = 1812  
		id       = {  type = 14800 id = 133  }  
		name     = "Atlantic Transport Fleet 3"  
		division = {
			id   = {  type = 14800 id = 137  }  
			name = "Peter Stuyvesant Flotilla"  
			type = transport  
			model = 1
		}
		division = {
			id   = {  type = 14800 id = 138  }  
			name = "Henry L. Benning Flotilla"  
			type = transport  
			model = 1
		}
		division = {
			id   = {  type = 14800 id = 139  }  
			name = "Casimir Pulaski Flotilla"  
			type = transport  
			model = 1
		}
		division = {
			id    = {  type = 14800 id = 119  }  
			name  = "Destroyer Division 21"  
			type  = destroyer  
			model = 3  
		}
		division = {
			id    = {  type = 14800 id = 174  }  
			name  = "Destroyer Division 26"  
			type  = destroyer  
			model = 3  
		}
	}
	navalunit = {
		location = 1812  
		base     = 1812  
		id       = {  type = 14800 id = 2323  }  
		name     = "Atlantic Transport Fleet 4"  
		division = {
			id   = {  type = 14800 id = 140  }  
			name = "Sam Houston Flotilla"  
			type = transport  
			model = 1
		}
		division = {
			id   = {  type = 14800 id = 141  }  
			name = "Francis Scott Key Flotilla"  
			type = transport  
			model = 1
		}
		division = {
			id   = {  type = 14800 id = 142  }  
			name = "Walter Reed Flotilla"  
			type = transport  
			model = 1
		}
		division = {
			id    = {  type = 14800 id = 2315  }  
			name  = "Destroyer Division 5"  
			type  = destroyer  
			model = 3
		}
		division = {
			id    = {  type = 14800 id = 2316  }  
			name  = "Destroyer Division 6"  
			type  = destroyer  
			model = 3  
		}
	}
	navalunit = {
		location = 1886  
		base     = 1886  
		id       = {  type = 14800 id = 146  }  
		name     = "Pacific Transport Fleet 4"  
		division = {
			id   = {  type = 14800 id = 157  }  
			name = "Molly Pitcher Flotilla"  
			type = transport  
			model = 1
		}
		division = {
			id   = {  type = 14800 id = 158  }  
			name = "Antonin Dvorak Flotilla"  
			type = transport  
			model = 1
		}
		division = {
			id   = {  type = 14800 id = 159  }  
			name = "J. E. B. Stuart Flotilla"  
			type = transport  
			model = 1
		}
		division = {
			id    = {  type = 14800 id = 2318  }  
			name  = "Destroyer Division 8"  
			type  = destroyer  
			model = 3
		}
		division = {
			id    = {  type = 14800 id = 2319  }  
			name  = "Destroyer Division 9"  
			type  = destroyer  
			model = 2
		}
	}

	airunit = {
		location = 1886  
		base     = 1886  
		id       = {  type = 14800 id = 13  }  
		name     = "1st USAAF Fighter Wing"  
		division = {
			id    = {  type = 14800 id = 14  }  
			name  = "6th USAAF Fighter Wing"  
			type  = interceptor  
			model = 4
		}
	}
	airunit = {
		location = 1809  
		base     = 1809  
		id       = {  type = 14800 id = 17  }  
		name     = "1st USAAF Bombardment Wing"  
		division = {
			id    = {  type = 14800 id = 18  }  
			name  = "1st USAAF Dive Bomb. Wing"  
			type  = tactical_bomber  
			model = 3
		}
	}
	airunit = {
		location = 889  
		base     = 889  
		id       = {  type = 14800 id = 19  }  
		name     = "5th USAAF Bombardment Wing"  
		division = {
			id    = {  type = 14800 id = 20  }  
			name  = "5th USAAF Tactical Bomb. Wing"  
			type  = tactical_bomber  
			model = 3
		}
	}
	airunit = {
		location = 1795  
		base     = 1795  
		id       = {  type = 14800 id = 23  }  
		name     = "US Army Airforce"  
		division = {
			id    = {  type = 14800 id = 24  }  
			name  = "9th USAAF Fighter Wing"  
			type  = interceptor  
			model = 4
		}
		division = {
			id    = {  type = 14800 id = 25  }  
			name  = "2nd USAAF Tactical Bomb. Wing"  
			type  = tactical_bomber  
			model = 4
		}
	}


	# Starting Build Queue
	
	division_development = {
		name  = "USS Yorktown"  
		type  = carrier  
		model = 2  
		new_model = no
		cost  = 0.5  
		id    = {  type = 14800 id = 500  }  
		date  = {  year = 1937 month = september day = 30  }  
		extra = cag  
		brigade_model = 2  
	}
	division_development = {
		name  = "USS Enterprise"  
		type  = carrier  
		model = 2  
		new_model = no
		cost  = 0.5  
		id    = {  type = 14800 id = 501  }  
		date  = {  year = 1938 month = may day = 12  }  
		extra = cag  
		brigade_model = 2  
	}
	division_development = {
		name  = "USS Quincy"  
		type  = heavy_cruiser  
		model = 4  
		new_model = no
		cost  = 0.3  
		id    = {  type = 14800 id = 502  }  
		date  = {  year = 1936 month = june day = 9  } 
		extra1 = floatplane
		brigade_model1 = 4		  
	}
	division_development = {
		name  = "USS Vincennes"  
		type  = heavy_cruiser  
		model = 4  
		new_model = no
		cost  = 0.3  
		id    = {  type = 14800 id = 592  }  
		date  = {  year = 1937 month = february day = 24  } 
		extra1 = floatplane
		brigade_model1 = 4		  
	}
	division_development = {
		name  = "USS Wichita"  
		type  = heavy_cruiser  
		model = 5  
		new_model = no
		extra1 = floatplane
		brigade_model1 = 4
		cost  = 0.3  
		id    = {  type = 14800 id = 503  }  
		date  = {  year = 1939 month = february day = 16  }  
	}
	division_development = {
		name  = "USS Brooklyn"  
		type  = light_cruiser  
		model = 5  
		new_model = no
		cost  = 0.3  
		id    = {  type = 14800 id = 504  }  
		date  = {  year = 1937 month = september day = 30  }  
	}
	division_development = {
		name  = "USS Philadelphia"  
		type  = light_cruiser  
		model = 5  
		new_model = no
		cost  = 0.3  
		id    = {  type = 14800 id = 505  }  
		date  = {  year = 1937 month = september day = 23  }  
	}
	division_development = {
		name  = "USS Savannah"  
		type  = light_cruiser  
		model = 5  
		new_model = no
		cost  = 0.3  
		id    = {  type = 14800 id = 506  }  
		date  = {  year = 1938 month = march day = 10  }  
	}
	division_development = {
		name  = "USS Nashville"  
		type  = light_cruiser  
		model = 5  
		new_model = no
		cost  = 0.3  
		id    = {  type = 14800 id = 507  }  
		date  = {  year = 1938 month = june day = 6  }  
	}
	division_development = {
		name  = "USS Phoenix"  
		type  = light_cruiser  
		model = 5  
		new_model = no
		cost  = 0.3  
		id    = {  type = 14800 id = 508  }  
		date  = {  year = 1938 month = october day = 3  }  
	}
	division_development = {
		name  = "USS Boise"  
		type  = light_cruiser  
		model = 5  
		new_model = no
		cost  = 0.3  
		id    = {  type = 14800 id = 509  }  
		date  = {  year = 1938 month = august day = 12  }  
	}
	division_development = {
		name  = "USS Honolulu"  
		type  = light_cruiser  
		model = 5  
		new_model = no
		cost  = 0.3  
		id    = {  type = 14800 id = 510  }  
		date  = {  year = 1938 month = june day = 15  }  
	}
	division_development = {
		name  = "Destroyer Division 48"  
		type  = destroyer  
		model = 5  
		cost  = 0.1  
		id    = {  type = 14800 id = 511  }  
		date  = {  year = 1936 month = february day = 1  }  
	}
	division_development = {
		name  = "Destroyer Division 49"  
		type  = destroyer  
		model = 5  
		cost  = 0.1  
		id    = {  type = 14800 id = 512  }  
		date  = {  year = 1936 month = march day = 1  }  
	}
	division_development = {
		name  = "Submarine Division 19"  
		type  = submarine  
		model = 4  
		cost  = 0.1  
		id    = {  type = 14800 id = 513  }  
		date  = {  year = 1936 month = may day = 1  }  
	}
	division_development = {
		name  = "Submarine Division 20"  
		type  = submarine  
		model = 4  
		cost  = 0.1  
		id    = {  type = 14800 id = 514  }  
		date  = {  year = 1936 month = june day = 1  }  
	}
	
}  
  
